### ISSUE TITLE
[MELHORIA]Cadastro de PA - Enquadramento de Despesa

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1000]
Somente na tela de Cadastro de PA (PA FNC não).

- [ ] Na tela de Cadastro de PA (Antigo Cadastro de PI), deixar opção de <b>Enquadramento de Despesa</b> marcada por padrão como <b>Não Orçamentária</b>

Demandante:  Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1000-planejamento-cadastro-pa-enquadramento

**Comment by dougs007** [comment]
Testado em homologação:

# Com PA existente -> Finalístico
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10914

# Um PA novo
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A
