### ISSUE TITLE
[MELHORIA]Planejamento-Alterações de nomes

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1003]
Segue lista de alterações a serem feitas:

- MÓDULO PLANEJAMENTO
Página de cadastro do Projeto:
- [x]  No campo “Produto PI”, alterar o nome para “Produto PA”
- [x] No campo “Dados do Plano Interno”, alterar o nome para “Dados do Plano de Ação”
- [x]  No campo Detalhamento Orçamentário, alterar o nome da coluna “Detalhado em PI pela Unidade” por “Detalhado em PA pela Unidade”
- [x] Alterar na janela de tramitação “Cancelar PI” para “Cancelar PA”
- [ ] Na janela de histórico de tramitações, alterar “PI ...” por “PA ...”
- [x] Na janela de histórico de alterações, alterar “Não há histórico de alterações nesse PI” por “Não há histórico de alterações nesse PA”
- [x] Na aba monitoramento, alterar “Acompanhamento do PI” por “Acompanhamento do PA”

Página de pesquisa/lista de Planos de Ação:
- [x] No espelho do PA, acionado pela coluna código, alterar “Plano Interno” por “Plano de Ação”
- [x] No espelho do PA, campo “Dados do Plano Interno”, alterar o nome para “Dados do Plano de Ação”

Barra lateral SIMINC:
- [x] Alterar “Produtos PI” por “Produtos PA”

- MÓDULO MONITORAMENTO:
Página Painel de Acompanhamento:
- [x] No campo Minhas Metas PPA, alterar o nome da coluna “PIs” para “PAs”
- [x] No campo Minhas Metas PNC, alterar o nome da coluna “PIs” para “PAs”

Página Monitorar PPA:
- [x] Alterar o nome do gráfico “PIs associados à Meta” para “PAs associados à Meta”
- [x] Alterar o nome do campo “Planos Internos (PI’s)” para “Planos de Ação (PA’s)”

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1003-planejamento-alteracoes-nome

**Comment by dougs007** [comment]
- [ ] Estudar solução para alterar nome de PI para PA, motivo: Dado vindo da base de dados.
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/4f4917e4-ba18-49ec-8bad-9c534a471700)

**Comment by leossb36** [comment]
testado em homologação
