### ISSUE TITLE
[MELHORIA]Planejamento - Lista PA Não Orçamentário

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1004]
**Análoga a tela lista PA**, porém vai mostrar só os **PA´s não orçamentários**.
Mudar filtros:
- [x] Mudar texto "Código PI ou ID PA" para "ID PA"
- [x] Excluir filtros: ptres, enquadramento, emenda, id beneficiario

Mudar colunas:
- [x] Excluir: código, funcional e todas de valor (total, provisionado, empenhado, liquido e pago)
- [x] Incluir: quantidade, Unidade de Medida e Produto.

Demandante: Sr. Marcelo Cavalheiro

**Comment by leossb36** [comment]
branch:
hotfix-1004-planejamento-lista-pa-nao-orcamentario

**Comment by dougs007** [comment]
Testado em homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapa-nao-orcamentaria&acao=A
