### ISSUE TITLE
[MELHORIA]Planejamento - Cadastro PA Não Orçamentário

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1005]
Na tela de "Cadastro de Plano de Ação", realizar as seguintes alterações no formulário para quando o tipo de "Enquadramento de Despesa" for <b>Não Orçamentário</b>.

- [x] Mudar nome do Box de "Metas" para "Planejamento Estratégico";

- [x] Remover campo "Programa";

- [x] Trocar nome de "Objetivo PPA" para "Objetivo Estratégico";

- [x] Trocar campo de "Meta PPA" para "Diretriz Estratégica";

- [x] Trocar campo "Inciativa PPA" para "Meta".

Demandante: Sr. Marcelo Cavalheiro

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1005-planejamento-cadastro-pa-nao-orcamentario

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A
