### ISSUE TITLE
[CORREÇÃO] Planejamento-Cadastro de Plano de Ação

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1009]
Ao tentar salvar um Anexo, o sistema lista o nome com caracteres estranhos caso o mesmo possua acentuação.

- [x] Corrigir sistema para que salve arquivos com nome contendo acentuação. (Não sei se é geral ou só não orçamentário)

Demandante: Sr. Marcelo Cavalheiro

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1009-planejamento-cadastro-pa-anexos
