### ISSUE TITLE
[CORREÇÃO]Cadastro PA-Aba Monitoramento 

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1010]
Id: 11386 problema ao gravar aba de monitoramento na tela de Cadastro de Plano de Ação.
"Informou msg de salvo, mas não salvou"

- [x] Investigar e corrigir o ocorrido.
Demandante: Sr. Marcelo Cavalheiro

**Comment by rafaeljcg20** [comment]
<b>SCRIPT ENVIADO PRA PUBLICAÇÃO Chamado#8218894</b>
