### ISSUE TITLE
[MELHORIA]Planejamento-Lista de PA Não Orçamentário

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1011]
- [x] Na coluna "unidade", remover o código, exibir somente seu nome.

Demandante: Sr. Marcelo Cavalheiro

**Comment by dougs007** [comment]
Nome da branch: 

hotfix-1011-planejamento-lista-pa-nao-orcamentario

**Comment by dougs007** [comment]
Oi @macavalheiro, corrigir também na exportação do xls dessa página?

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapa-nao-orcamentaria&acao=A
