### ISSUE TITLE
[MELHORIA]Planejamento-Cadastro PA Não Orçamentário

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1012]
<b>Obs:</b> Para o formulário de Plano de Ação do tipo <b>Enquadramento Não Orçamentário</b>:

- [x] Retirar botão vermelho "Criar PA por proposta";

- [x] Trocar o gráfico por um gráfico simples que compare o previsto físico, com o executado do campo de executado;

- [x] Trocar nome do gráfico de "Percentual de Empenho" para "Percentual de Execução";

- [x] Retirar aba alterações orçamentárias.

Demandante: Sr. Marcelo Cavalheiro

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1012-planejamento-cadastro-pa-nao-orcamentario

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10917
