### ISSUE TITLE
[MELHORIA]Planejamento-Botões do Painel

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1014]
Na tela Painel de Acompanhamento:
- [x] Retirar Atualizar SIOP  e Painel FNC da tela principal;
- [x] Criar o menu Atualizar SIOP;
- [x] Mudar o menu "Lista PA não orçamentária" para "Ações não Orçamentárias"
- [x] Criar o Botão "Ações não Orçamentárias" ao lado do botão Lista de PA.

Demandante: Sr. Marcelo Cavalheiro

**Comment by dougs007** [comment]
Nome da Branch:

hotfix-1014-planejamento-melhoria-botoes

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C

**Comment by macavalheiro** [comment]
show de bola @dougs007 

tem como mudar a cor só pra não ficar a mesma? acho q um azul como tava os botões anteriores serai de boa

**Comment by dougs007** [comment]
oi @macavalheiro, tem sim, já estamos publicando!
