### ISSUE TITLE
[MELHORIA]Planejamento-Formulário PA(reduzido e normal).

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1015]
Retirar a obrigatoriedade dos seguintes campos:

 - [x] Objetivo PPA
 - [x] Meta PPA
 - [x] Meta PNC (que inclusive sumiram, mas não faz mal, pode deixar fora por ora, só tirar a obrigatoriedade senão não consigo gravar)
 - [x] Indicador PNC (que inclusive sumiram, mas não faz mal, pode deixar fora por ora, só tirar a obrigatoriedade senão não consigo gravar)

 - [x] Área Cultural (se for mais fácil tirar o campo todo, pode tirar)
 - [x] Segmento Cultural (se for mais fácil tirar o campo todo, pode tirar)

 - [x] Localização do Projeto
 - [x] Responsáveis

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1015-planejamento-formulario-pa

**Comment by dougs007** [comment]
Testado em homologação:


http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A

**Comment by rafaeljcg20** [comment]
teste
