### ISSUE TITLE
[MELHORIA]Planejamento-Cadastro PA Aba Monitoramento

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1020]
Na tela de cadastro de Plano de Ação, na aba de Monitoramento, retirar casas após a virgula dos seguintes campos:

- [x] Quantidade
- [x] Quantidade Prevista até a data
- [x] Executado

Demandante: Marcelo Cavalheiro

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1020-planejamento-cadastro-pa-aba-monitoramento

**Comment by leossb36** [comment]
testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&aba=1&pliid=10941&acoid=132
