### ISSUE TITLE
[MELHORIA]Planejamento-Cadastro PA

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1030]
Fazer seguintes alterações quando o <b>Enquadramento</b> for do tipo <b>Não Orçamentária</b>:

Trocar só a descrição dos seguintes campos:

- [x] Trocar nome campo de "Diretriz Estratégica"  para "Meta";
- [x] Trocar nome do campo de "Meta" para "Diretriz Estratégica"

Demantante: Sr. Marcelo Cavalheiro

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1030-planejamento-cadastro-pa

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A
