### ISSUE TITLE
[MELHORIA]Painel de acompanhamento-Acompanhamento de Funcionais

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1036]
Na tela Painel de Acompanhamento, na lista Acompanhamento de Funcionais, mudar a tela pra exibir duas abas, onde em uma será mantido o conteúdo atual(Lista de PAs da Unidade e Lista de PAs Delegados) e na outra aba será exibido duas listas sendo uma lista com os PAs Não Orçamentários Aprovados da Unidade e na outra uma lista com PAs Não orçamentários Delegados.

As colunas da Lista de PAs Não orçamentários e Delegados seriam:
Ações(com o lápis de entrar na edição), Id, Título, Quantidade Produto

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da Branch:

hotfix-1036-planejamento-acompanhamento-funcionais

**Comment by leossb36** [comment]
testado em homologação:
http://local.siminc2:8082/planacomorc/planacomorc.php?modulo=inicio&acao=C
