### ISSUE TITLE
[MELHORIA]Planejamento-Lista de Ações Não Orçamentárias

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1038]
- [x] Na tela de "Lista de PA Não Orçamentárias", ao filtrar por unidade, trazer também PA's Não Orçamentárias que foram delegados a execução para essa unidade (Unidade Delegada), diferenciando-o dos demais (Cor, ícone ou lugar de exibição).

- [x] Mesma coisa para tela lista de PA's para PA's de qualquer tipo.

exemplo: o PA de Id: 11386 está delegado para a "Secretaria Nacional de Futebol e defesa dos direitos do torcedor" então ao filtrar essa secretaria deve ser exibido também, (porém com alguma diferenciação dos demais que são dela mesmo)

Obs: Foi definido que a sinalização será o ícone de compartilhado usado na Tela Painel de Acompanhamento

Demandante: Sr. Marcelo Cavalheiro

**Comment by macavalheiro** [comment]
@dougs007

**Comment by leossb36** [comment]
branch:
hotfix-1038-planejamento-lista-pa

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapa-nao-orcamentaria&acao=A
