### ISSUE TITLE
[MELHORIA]Planejamento-Painel de Acompanhamento

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1039]
- [x] Retirar o Código da UG que é informada entre ().
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/992b0c82-bfb8-498e-a470-3b9cc4539bf0)

**Comment by macavalheiro** [comment]
no painel de acompanhamento (tela inicial do módulo planejamento) aparece na parte d ebaixo o nome da unidade e seu código entre parenteses

esse código que deseja-se retirar

**Comment by macavalheiro** [comment]
@dougs007

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1039-planejamento-painel-acompanhamento

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C
