### ISSUE TITLE
[MELHORIA]Painel de Acompanhamento-Minhas Metas do Planejamento Estratégico

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1040]
Na tela Painel de Acompanhamento, desenvolver uma nova lista com o título "Minhas Metas do Planejamento Estratégico" com os mesmos botões e colunas semelhantes a lista "Minhas Metas PPA".

- [x] Criar nova tela de Monitoramento Planejamento Estratégico semelhante a tela de Monitoramento PPA pra inserir os dados de executado, classificação e medidas a serem tomadas;

- [x] Corrigir funcionalidade de salvar da tela de Apoio -> Janela. Obs: Não está sendo possível salvar uma nova janela na tabela de apoio, mesmo a do PPA (que já tinha); <b>solicitado a publicação pelo Chamado 8219355</b>

- [x] Na tela Construtor de Relatório e tela de Relatório geral retirar implementação que exibia Objetivo PPA, Meta e Iniciativa PPA como Objetivo Estratégico, Meta e Diretriz quando o enquadramento era do tipo "Não Orçamentário" e acrescentar as novas informações de Objetivo Estratégico, Meta e Diretriz pra todos os PAs.

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1040-monitoramento-minhas-metas

**Comment by dougs007** [comment]
ALTER TABLE acompanhamento.acompanhamento ADD COLUMN meuid integer;
COMMENT ON COLUMN acompanhamento.acompanhamento.meuid IS 'Meta Unidade';


ALTER TABLE acompanhamento.acompanhamento
  ADD CONSTRAINT fk_planacomorc_meuid FOREIGN KEY (meuid)
      REFERENCES planacomorc.meta_unidade (meuid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

**Comment by dougs007** [comment]
SCRIPTS PARA TESTE APÓS ATUALIZAREM HOMOLOGA:

// Abrir Janela para testes.
 insert into acompanhamento.janela (jandsc, janinicio, janfim, prsano, tipid )
 values ( 'Monitoramento Planejamento Estratégico', '2019-05-21', '2019-12-31', '2019', '4' );

**Comment by rafaeljcg20** [comment]
Erro em fase de teste da equipe de desenvolvimento:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/2df9cc7d-5343-4edd-9985-e5ab2891e25d)

**Comment by dougs007** [comment]
Feita a correção !

**Comment by leossb36** [comment]
Ao mudar de janela apresenta o seguinte erro:
![image.png](https://images.zenhubusercontent.com/59f463e48a75884b908527c3/811644a7-377c-4c24-aa1f-e2f34e879c32)

**Comment by dougs007** [comment]
Corrigida novamente !

**Comment by leossb36** [comment]
testado em homologação: 
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=inicio&acao=C
