### ISSUE TITLE
[MELHORIA]Painel de Acompanhamento-Meus Planos de Ação Não Orçamentários

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1041]
Na tela Painel de Acompanhamento:
- [x] Desenvolver uma nova lista com o título "Meus Planos de Ação Não Orçamentários" com os mesmos botões e colunas semelhantes a lista "Meus Projetos" com as seguintes colunas: status, id, título, Qtidade Prevista, Executado, Produto, Classificação.

- [x] Criar nova tela de Monitoramento Planejamento Estratégico semelhante a tela de Monitoramento PPA pra inserir os dados de executado, classificação e medidas a serem tomadas;

- [x] Trocar nome de "Meus projetos" para "meus Planos de Ação".

**Comment by rafaeljcg20** [comment]
Branch: hotfix-1041-monitoramento-pa-nao-orcamentario

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=principal/monitorar-pi&acao=A&pliid=11386

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/3d5d6b79-6cfb-4d20-b381-a96ecea56856)

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/26688407-4551-4f1e-ac98-1968e8a8177d)

**Comment by macavalheiro** [comment]
as colunas estão um pouco diferentes as colunas corretas seriam
status, id, título, Qtidade Prevista, Executado, Produto, Classificação.


não consegui entrar para monitorar tb, mesmo abrindo janela

**Comment by rafaeljcg20** [comment]
Corrigindo colunas da tabela:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/bf0c3361-bcec-481b-97c8-516aa32f924b)

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=inicio&acao=C&suoid=63

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro , poderia verificar novamente?
