### ISSUE TITLE
[MELHORIA]Monitoramento-Relatórios

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1042]
Trocar nomes no Gerador de Relatório e Relatório Geral:

- [x] Onde tiver "Meta PPA" para "Meta"
- [x] Onde tiver "Produto PI" para "Produto"
- [x] Onde tiver "Meta Física" para "Quantidade"

Demandante: Sr. Marcelo Cavalheiro

**Comment by macavalheiro** [comment]
@dougs007  salve Douglas! acho q essa é fácil. se for mesmo e tu puder tocar para mim, seria massa. valeu

**Comment by dougs007** [comment]
Nome da branch ->

hotfix-1042-monitoramento-relatorios

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A
