### ISSUE TITLE
[MELHORIA]Monitoramento-Construtor de Relatórios

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1043]
- [x] Ativar o Gerador de Relatórios para o Perfil Unidade, filtrando só a unidade da pessoa PS: Atualmente não está.

Demandante: Sr. Marcelo Cavalheiro

**Comment by macavalheiro** [comment]
@dougs007

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A

unidade: Adam

**Comment by macavalheiro** [comment]
entrei em homologa e simulei o usuário rafael da sav e não consegui e o relatório veio sem informações. 

tentei filtrar só sav e tb não consegui.

**Comment by macavalheiro** [comment]
para o exercício de 2018 funcionou

para 2019 não

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro , poderia testar novamente? Testei com o Perfil do Rafael e ele possui a mesma quantidade de PAs(7) que é possível visualizar no módulo Planejamento.

**Comment by macavalheiro** [comment]
é um detalhe, mas descobri o que não está rolando

quando entro com o usuário Rafael Gazzola e estou no exercicio de 2018, ma peço um relatório com a base de 2019 ele não funciona colocar a unidade.  O contrário tb acontece.  Só consigo tirar relatorio de 2019 se entrar com o exercicio de 2019 (em cima) e para 2018 a mesma coisa.

**Comment by rafaeljcg20** [comment]
Olá @macavalheiro, poderia verificar novamente? Corrigimos ao aplicar o filtro por Unidade e tentar gerar o relatório de ano diferente ao exercício selecionado.

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A

**Comment by rafaeljcg20** [comment]
Branch: hotfix-1043-monitoramento-construtor-relatorios

**Comment by macavalheiro** [comment]
permanece o mesmo erro

quando entro com o usuário Rafael Gazzola e estou no exercicio de 2018, ma peço um relatório com a base de 2019 ele não funciona colocar a unidade. O contrário tb acontece. Só consigo tirar relatorio de 2019 se entrar com o exercicio de 2019 (em cima) e para 2018 a mesma coisa.

**Comment by rafaeljcg20** [comment]
Erro:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/309eb83e-9cf5-47e0-a383-0c64d0b57de5)

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro, o problema foi corrigido... quando tiver um tempo, poderia verificar novamente?

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A

**Comment by rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/038c849e-08d5-460c-bd0f-ca637fbb701c)
