### ISSUE TITLE
[CORREÇÃO]Planejamento-Cadastro PA Não Orçamentário

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1044]
Ao tentar inserir um registro novo, após preencher os campos mínimos de aceitação (obrigatórios), o sistema exibe no campo de "Recursos Necessários" o mesmo valor inserido no campo de "Descrição / Finalidade"

Erro relatado pela unidade SEINFRA, que recentemente gravou vários PA's não Orçamentários.
Na segunda vez, (alteração) diz que grava certo. Erro acontece só na primeira vez (inserção).

Demandante: Sr. Marcelo Cavalheiro

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1044-planejamento-cadastro-pa-nao-orcamentario

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=11406
