### ISSUE TITLE
[CORREÇÃO]Cadastro de PA-Botão Voltar

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1046]
Na tela de Cadastro de PA, ao clicar no botão Voltar o sistema está sempre voltando pra lista de PA normal. Corrigir o botão Voltar pra voltar para a tela anterior(Lista de PA ou Lista de PA Não Orçamentário) independente do tipo de enquadramento.

Dica de código: usar função nativa javascript pra voltar pra tela anterior.

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
hotfix-1046-planejamento-botao-voltar

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A
