### ISSUE TITLE
[CORREÇÃO]Tramitação em Lote-Não orçamentário

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1047]
Na tela Tramitação em Lote o sistema não está listando PAs que são do enquadramento Não Orçamentário inviabilizando a tramitação em lote pra esses casos. Corrigir a lista de PAs para exibir PAs do enquadramento não orçamentário.,

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1047-planejamento-tramitacao-lote

Observações:

- [ ] Ativar menu em produção.

**Comment by dougs007** [comment]
Testado em homologação:


http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/tramitacao-nao-orcamentario&acao=A

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/tramitacao-lote&acao=A
