### ISSUE TITLE
[MELHORIA]Monitoramento PNC-Cadastro de acompanhamento do Indicador PNC

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1054]
Na tela de Monitoramento das Metas PNC, o sistema deverá ser modificado pra permitir que se possa avançar do passo(1.Indicadores) pra o próximo passo(2.Atividades) sem a necessidade de preencher todos os indicadores do ano do exercício selecionado no módulo.

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1054-monitoramento-indicador-pnc

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=principal/monitorar-pnc&acao=A&suoid=533&janid=4&mpnid=982
