### ISSUE TITLE
[MELHORIA]Monitoramento PNC-Indicadores PNC Ordenar lista

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1055]
Na tela de Monitoramento PNC, no passo 1.Indicadores, ordenar a lista de indicadores pela coluna descrição do indicador em ordem alfabética.

**Comment by dougs007** [comment]
hotfix-1055-monitoramento-indicadores-pnc

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=principal/monitorar-pnc&acao=A&suoid=518&janid=4&mpnid=938
