### ISSUE TITLE
[MELHORIA]Monitoramento PNC-Retirar Casas Decimais

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1056]
Na tela Monitoramento PNC, retirar a formatação de número com valores decimais tanto da quantidade do indicador, como dos valores de execução orçamentárias e também da janela modal contendo a lista de PAs conforme sinalizado nas imagens abaixo:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/59402199-d484-469b-9003-1d75bfda1d3a)

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/94f66cd1-7bb5-4569-b5c5-c49233f24430)

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/ba32fa73-5ad9-41f4-93a3-271d9a53b087)

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1056-monitoramento-retirar-casas-decimais

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=principal/monitorar-pnc&acao=A&suoid=522&janid=4&mpnid=984
