### ISSUE TITLE
[CORREÇÃO]Planejamento-Lista PA Não Orçamentária

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#1058]
- [ ] Corrigir consulta para filtrar a Lista de PA Não Orçamentária.

**Comment by dougs007** [comment]
Dica de Teste:

Logar com o CPF : 47135018168, pois sobre o mesmo que estava chegando e-mail de erro sobre a consulta.

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapa-nao-orcamentaria&acao=A
