### ISSUE TITLE
[MELHORIA]Cadastro de PA-Layout Não orçamentário

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1067]
Na tela Cadastrar PA realizar as seguintes melhorias:
- [x] Colocar o box "vinculações eventuais do projeto" acima do box "Localização do projeto" para reduzir os buracos

- [x] Se possível dar ver ser dar para reduzir os buracos do formulário geral tb (não não orçamentário)

Demandante: Sr. Marcelo

**Comment by macavalheiro** [comment]
@dougs007

**Comment by rafaeljcg20** [comment]
Branch: feature-1067-planejamento-cadastro-pi-layout

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A
