### ISSUE TITLE
[MELHORIA]Criação de exercício 2019

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1086]
Desenvolver o script de criação do exercício 2019 e cargas iniciais de dados(excerto os dados que serão importados pela planilha) pra o sistema ficar operante.

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1086-emendas-exercicio

**Comment by dougs007** [comment]
- [ ] Alterar url do menu de código 1010 para os dados da imagem abaixo.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/867df6a4-9ac6-4404-90a6-d4257334db60)

**Comment by dougs007** [comment]
- [ ] Script para otrs após validação da demanda.

INSERT INTO emendas.programacaoexercicio 
(prsano, prsdata_inicial, prsdata_termino, prsexerccorrente, prsstatus, prsativo, prsexercicioaberto)
VALUES
('2019', '2019-01-01', '2019-12-31', 'f', 'A', '1', 't');

UPDATE emendas.programacaoexercicio
    SET prsexerccorrente = 'f'
WHERE
    prsano = '2017';
