### ISSUE TITLE
[CORREÇÃO]Cadastro de PA-Descrição

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1087]
Na tela de Cadastro de PA, limitar a quantidade de preenchimento pra 1000 caracteres tanto da opção Descrição / Finalidade quanto da opção Recursos Necessários.

Obs: O sistema está apresentando erro em produção, erro recebido por e-mail.

Demandante: Rafael J

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1086-planejamento-cadastro-pa

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A
