### ISSUE TITLE
[CORREÇÃO]Cadastrar PA-Meta Estratégica

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1095]
Na tela de Cadastrar PA, após salvar as informações de Planejamento Estratégico(Objetivo, Meta e dimensão) se o usuário voltar pra tela de Listar PA e depois voltar a editar o PA gravado o sistema não persiste <b>as opções de Metas filtradas por Subunidade</b>.

Observações do Demandante:
Filtro de metas do planejamento estratégico por unidade objetivo;
Qdo marca o objetivo a primeira vez funciona, qdo salva e volta para o menu, não faz mais o filtro;
Ao alterar o objetivo o sistema perde o filtro por unidade.

Demandante: Sr. Marcelo

**Comment by rafaeljcg20** [comment]
Demanda concluída com a entrega da nova estrutura de planejamento estratégico implementada na demanda #1114.

Portanto a demanda será fechada.
