### ISSUE TITLE
[CORREÇÃO]Cadastro Beneficiários-Subunidade

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1106]
Na tela de cadastro de beneficiários estão aparecendo a lista de subunidades diferentes das unidades 2019.

**Comment by rafaeljcg20** [comment]
O detalhamento não foi suficiente pra reproduzir e resolver o problema. Quando o demandante retornar de férias vamos acrescentar informações pra poder executar a implementação.

**Comment by leossb36** [comment]
branch:
hotfix-1106-emendas-cadastro-beneficiario-subunidade

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8874
