### ISSUE TITLE
[MELHORIA]Cadastrar PA-Recursos necessários

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#1109]
Na tela de Cadastrar PA, retirar a opção Recursos necessários de todas as formas de exibição(Enquadramentos).

**Comment by rafaeljcg20** [comment]
BRANCH: hotfix-1109-planejamento-recursos
SCRIPT:
ALTER TABLE monitora.pi_planointerno DROP COLUMN plirecursosnecessarios;

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=11419
