### ISSUE TITLE
[MELHORIA]CADASTRAR PA-METAS UNIDADE

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1114]
Na tela de Cadastrar PA, fazer as seguintes alterações:
- [x] Remover as opções Objetivo Estratégico, Meta Estratégica, Diretriz Estratégica;
- [x] Inserir a Opção Metas Unidade e quando o usuário preencher um item dessa opção o sistema deverá mostrar as seguintes opções Objetivo, Dimensão Estratégica, Meta Estratégica, conforme as informações anexadas por e-mail.

Demandante: Sr. Marcelo
- Perguntar pra o Marcelo se as Metas da Unidade e seus relacionamentos serão anualizados.

**Comment by dougs007** [comment]
Nome da branch : hotfix-1114-planejamento-plano-acao-metas

**Comment by leossb36** [comment]
Trazer os texto descritivos dos campos junto com os campos na hora que seleciona Meta Unidade
![image.png](https://images.zenhubusercontent.com/59f463e48a75884b908527c3/68bd9c2d-0c69-4891-bfc0-8e0851ededdc)

**Comment by dougs007** [comment]
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=11388
