### ISSUE TITLE
[CORREÇÃO]Estrutura de Arquivos do Sistema-Ajustes

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#1118]
Ajustes de informações que vieram do MEC e que **não é utilizado no sistema**

- [x] Remover arquivos que não são utilizados pelos módulos ativos e nem por nenhuma parte importante do sistema.

Motivo da demanda: Optimizar o sistema e facilitar a manutenção.

**Comment by dougs007** [comment]
- [ ] Remover casos de schemas que não tem mais no sistema. (arquivo -> /www/geral/workflow/alterar_estado.php)

**Comment by leossb36** [comment]
Todos os módulos foram testados com sucesso.
Alguns erros foram apresentados, porem estes ja foram resolvidos na Issue [#1040](https://app.zenhub.com/workspaces/siminc2-5a974f9d25b7373ceb1e20d5/issues/culturagovbr/siminc2/1040)

**Comment by rafaeljcg20** [comment]
Obs: Testar todos os módulos. Demanda critica.

**Comment by rafaeljcg20** [comment]
Erro ao acessar a tela Sistema >> Usuários e clicar em editar usuário.

**Comment by leossb36** [comment]
Teste concluido de todas as telas

**Comment by rafaeljcg20** [comment]
Foi solicitado a publicação parcial do script de banco de dados: <b>Chamado#8222484</b>

**Comment by rafaeljcg20** [comment]
Refatoração da estrutura de dados do módulo Gestão Estratégica: <b>Chamado#8222487</b>
