### ISSUE TITLE
[CORREÇÃO]ROTINA DIÁRIA-Execução Orçamentária Liquidado

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1120]
Na funcionalidade de importar dados de execução orçamentária via WS SIOP, alterar a formula de cálculo da informação "Liquidado" conforme as orientações do demandante:

Orientação do demandante: Como eu havia comentado com você, a equipe do orçamento falou que os dados relativos à execução do empenhado no Siminc deveriam ser puxados do campo “Empenhado/liquidado (excl.. inscr.. RAP NP)” e não do campo “Empenhado/Liquidado”, do SIOP. Estou encaminhando para você o extrator SIOP com ambos os campos (colunas H e I), para você ver a diferença de valores.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/26566c91-9c27-4a3f-8e6f-afc637f082e9)

Demandante: Sr. Joel

**Comment by rafaeljcg20** [comment]
Branch: hotfix-1120-planejamento-execucao-inscr-rap

**Comment by rafaeljcg20** [comment]
Testado em homologação de acordo com a planilha exportada do SIOP:
![1120-evidencia-de-teste.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/c60c422f-afa5-42e7-8170-495df9d0def2)

**Comment by rafaeljcg20** [comment]
Demandante informou que o calculo que deveria ser mudado era da informação de "Liquidado" e não "Empenhado".

**Comment by rafaeljcg20** [comment]
Correção efetuada e teste realizando em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapimanter&acao=A
![1120-evidencia-de-teste-2.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/3893946b-53a5-4b43-8092-a571d228beb6)

**Comment by rafaeljcg20** [comment]
Demandante solicitou um prazo até semana que vêm pra verificar junto a equipe a conferência dos dados, porém deixou o contato de e-mail do Sr. Lucas Silveira que pode antecipar o aceite dessa demanda.

**Comment by rafaeljcg20** [comment]
O Demandante conferiu os valores e solicitou investigação sobre a diferença do total de liquidado da ação 0005 do ano de 2018, via e-mail e fornecendo todos os dados pra análise.

**Comment by rafaeljcg20** [comment]
O Plano de Ação número 10033 associado a funcional da ação 0005 não está mostrando o valor de execução orçamentária(Provisionado, Empenhado, Liquidado e Pago), porque o número de PI não foi cadastrado no sistema SIOP pra realização do empenho.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/8dbfb63d-629a-402c-bed4-34533f46c006)

**Comment by JoelSSilva** [comment]
Os valores do "Relatório de Funcionais" do SIMINC estão OK, batendo com os do SIOP, com pequena diferença decorrente do arredondamento que o SIMINC faz. 

Quanto aos valores de execução da tela "Listar PAs", não serão considerados para esta issue, visto que não mostram valores empenhados sem código PI, que é o caso do executado da ação 0005, como visto nas telas acima.

**Comment by rafaeljcg20** [comment]
Verificação de diferença de valores entre a planilha e a execução(Aprovisionado, Empenhado, Liquidado e Pago) do Painel:

![planilha-painel-execucao-2018.jpg](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/6a06ff9b-c7a5-479a-a6db-5d6c32b464fd)

**Comment by rafaeljcg20** [comment]
Correção dos valores que estavam com arredondamento errado:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/655cf452-403e-4874-972e-34033f70876a)
