### ISSUE TITLE
[MELHORIA] Administrar Objetivo Estratégico

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1121]
Desenvolver novas telas pra administrar Objetivo Estratégico.

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch: hotfix-1121-planejamento-objetivo-estrategico

OBS: Ajustar o antigo menu de "Objetivo do Planejamento Estratégico" para "Objetivo Estratégico" antes da publicação. Tanto a lista como o menu de cadastro.

Dica de url: "objetivo-estrategico" e "objetivo-estrategico-form".

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/objetivo-estrategico&acao=A
