### ISSUE TITLE
[MELHORIA] Administrar Dimensão Estratégica

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1122]
Desenvolver novas telas pra administrar Dimensão Estratégica.

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch: hotfix-1122-planejamento-dimensao-estrategica

OBS: Publicar menu's em prod antes da publicação.

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/dimensao-estrategica&acao=A
