### ISSUE TITLE
[MELHORIA] Administrar Meta Estratégica

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1123]
Desenvolver novas telas pra administrar Meta Estratégica.

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch: hotfix-1123-planejamento-meta-estrategica

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/meta-estrategica&acao=A
