### ISSUE TITLE
[MELHORIA] Administrar Meta da Unidade do Planejamento Estratégico

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1124]
Desenvolver novas telas pra administrar Meta Unidade do planejamento Estratégico.

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch:
hotfix-1124-planejamento-metaunidade

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/meta-unidade-form&acao=A&meuid=5

**Comment by rafaeljcg20** [comment]
- [ ] Alterar o formato da opção Nome para texto corrido(textarea).

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/7b4cfcdf-50d5-4411-bb7d-5e7ca280da19)

**Comment by rafaeljcg20** [comment]
- [ ] Alterar a opção Prioritário para o valor inicial/padrão ser igual a "Não".
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/78ca76e8-80ee-4c2c-b8a7-caf5c722816c)

**Comment by leossb36** [comment]
Correções feitas na branch:
hotfix-1114-planejamento-plano-acao-metas

OBS: Devido a branch hotfix-1124-planejamento-metaunidade não está atualizada conforme o necessário para alteração, foi tomada a decisão de realizar as correções em uma branch mais atualizada, cuja esta está vinculada a melhorias realizadas nesta issue. A decisão foi tomada a fim de evitar conflitos e problemas futuros.
