### ISSUE TITLE
[CORREÇÃO]Componente de Máscara

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#1129]
Corrigir componente de máscara utilizado em formulários de valores.

OBS: Ao ir digitando o número, o sistema conta os números de inteiro junto com a máscara, e não deveria.
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/895c8cd9-a1ef-497d-836b-e51d7cb9805e)

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/d87d0151-48bb-4b81-9c79-6d81c04072a0)

Demandante: Douglas
Obs: Débito técnico observado durante a etapa de implementação.

**Comment by leossb36** [comment]
branch: hotfix-1129-componente-mascara

**Comment by leossb36** [comment]
tela para simular erro: /acompanhamento.php?modulo=principal/monitorar-ppa&acao=A&mppid=648&suoid=522&janid=5

componente de mascara: /zimec/public/temas/simec/js/simec-mascaras.js

![image.png](https://images.zenhubusercontent.com/59f463e48a75884b908527c3/f80c36af-f8ce-45ab-a25f-55a9884d7e32)

**Comment by rafaeljcg20** [comment]
Branch: hotfix-1129-componente-moeda-inteiro

**Comment by rafaeljcg20** [comment]
Não foi possível reproduzir o erro. @dougs007 na segunda-feira me ajude a reproduzir o problema nessa tela.

**Comment by rafaeljcg20** [comment]
O problema acontecia por causa de dados passivos anteriores a mudança de valores decimais pra inteiros na tela de monitoramento das metas do Planejamento Estratégico. Como não existe necessidade de manutenção essa demanda será fechada.
