### ISSUE TITLE
[CORREÇÃO]Relatório Geral-Planejamento Estratégico

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1135]
Ao acessar o menu Relatório >> Geral o sistema gera um erro.

Erro recebido por e-mail:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/c8ccf52d-de89-489f-a4a5-7ee149d1c4e3)

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/fd41aa4a-04c3-467d-b4a6-bb2019cd8f18)

Demandante: Rafael

**Comment by rafaeljcg20** [comment]
branch: hotfix-1135-planejamento-relatorio-geral-estrategico

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A
 e relatorio geral de planejamento orçamentário
