### ISSUE TITLE
[CORREÇÃO] Planejamento - Tramitar PA em lote

### ISSUE THREAD

**Issue by leossb36** [culturagovbr/siminc2#1145]
Em planejamento, na tela de tramitar PA em lote, a listagem de PA's que foram cancelados não está apresentando os dados desejados.

#### Estado atual:

    Lista em Branco

#### Estado desejado:

    Trazer todos os PA's que foram Cancelados

PA - 11283 - Aprovado <=> cancelado
![image](https://user-images.githubusercontent.com/26796127/58487683-68570680-813e-11e9-83d4-dad5c533bcef.png)

Lista de PA's Cancelados
![image](https://user-images.githubusercontent.com/26796127/58487800-9a686880-813e-11e9-8682-cbf8623e412c.png)

**Comment by leossb36** [comment]
branch: hotfix-1145-planejamento-tramitar-pa-em-lote

**Comment by rafaeljcg20** [comment]
Parabéns Leo( @leossb36 )!!! Excelente documentação da atividade e procedimentos!

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/tramitacao-lote&acao=A
