### ISSUE TITLE
[MELHORIA]Gerenciar Exercício

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#1146]
- [x] Criar tela para gerenciamento de exercício de todos os módulos utilizados no sistema.

**Comment by dougs007** [comment]
Nome da branch: fix-administrar-exercicio


OBS: Configurar e inserir menus em produção.

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=sistema/exercicio/admexerc_form&acao=A&prsano=2020
