### ISSUE TITLE
[PNC - Formulário novo]

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#116]
![Prototipo_monitoramento_pnc.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/edb10abe-8032-44cc-835d-088d1d6666ce)

**Comment by Rafaeljcg20** [comment]
[PNC] obs: como os indicadores não tem um "número a se atingir" o referencial a se comparar é o número que foi feito nos anos anteriores. Essa tabela (tabela de apoio preenchida manualmente) deverá constar do formulário na hora de preencher o exercício corrente. "Exemplo anexo"

**Comment by Rafaeljcg20** [comment]
[PNC] obs: como os indicadores não tem um "número a se atingir" o referencial a se comparar é o número que foi feito nos anos anteriores. Essa tabela (tabela de apoio preenchida manualmente) deverá constar do formulário na hora de preencher o exercício corrente. "Exemplo anexo" hasno dependencies

**Comment by rafaeljcg20** [comment]
Demanda será fechada, porque provavelmente era uma anotação pra conceituar o projeto do módulo Monitoramento que já foi desenvolvido.
