### ISSUE TITLE
[CORREÇÃO]Relatório de Funcionais-Duplicações

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1160]
Na tela Relatório de funcionais corrigir os seguintes erros:
- [x] Há repetição de valores quando a funcional está em mais de uma unidade, ex: Unidade Orçamentária 42101;
- [x] Funcionais cuja unidade está dentro de outra(Ex: DEINT dentro da SEC), estão com todos os valores iguais no Relatório de funcionais(Dotação, previsto, provisionado, empenhado, liquidado e pago);
- [x] Funcionais de emendas estão aparecendo com valor duplicadas também como por exemplo 2027.14U2.0014.0787.EIND.

Demandante: Sr. Joel

**Comment by rafaeljcg20** [comment]
Branch: hotfix-1160-planejamento-rel-func

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=relatorio/funcionais&acao=A

**Comment by rafaeljcg20** [comment]
O demandante solicitou a correção do seguinte caso de duplicação relacionado dessa vez ao valor de Dotação:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/f865f5d1-8cc2-4f1e-a8df-5b87b92fcf8a)

**Comment by rafaeljcg20** [comment]
A duplicação de dotação foi um erro gerado pela funcionalidade de excluir PA do tipo emenda, essa funcionalidade precisa ser corrigida no futuro em outra demanda(issue).
Segue o script pra correção pontual do problema apresentado pelo demandante:
DELETE FROM spo.ptressubunidade ptressuo WHERE suoid = 528 AND ptrid = 1456;

**Comment by JoelSSilva** [comment]
A issue está sendo fechada, a partir do que foi demandado inicialmente. Observo, no entanto, que ainda há divergências de valores em relação ao SIOP, como por exemplo a funcional com ação.localizador 14U2.0035, em cuja dotação há diferença de 100.000,00 (Siop - 370.000,00, Siminc - 470.000,00).

![14U2.0035 - SIOP.JPG](https://images.zenhubusercontent.com/5aa81f454b5806bc2bcab2bc/895d24ac-e597-4075-9de0-10ba512f760d)

![14U2.0035 - SIMINC.JPG](https://images.zenhubusercontent.com/5aa81f454b5806bc2bcab2bc/29218db6-a908-4894-a112-dfefe3e96148)

**Comment by rafaeljcg20** [comment]
Obrigado Joel!
Conforme o combinado será necessário solicitar uma mudança no sistema para que possa ser possível "Vincular Funcional(PTRES)" e definir "Limites de Funcionais nas Subunidades" para casos de funcionais do tipo de Emendas. Dessa forma, o sistema possibilitará que o próprio usuário com perfil de Administrador possa corrigir as dotações conforme acontece para as Funcionais que não são de Emendas.
