### ISSUE TITLE
Desenvolver nova tela Relatório Geral

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#124]
Desenvolver nova tela de Relatório Geral contendo todos os dados do módulo emendas para que a área meio possa trabalhar esses dados em planilha do tipo xls.

**Comment by Rafaeljcg20** [comment]
Branch: feature-emenda-relatorio-geral

**Comment by macavalheiro** [comment]
apenas a coluna número ficou desconfigurada. 
e faltou a coluna id pi (id do módulo planejamento) (pode ser o código já tb, mas melhor é só o id)

**Comment by Rafaeljcg20** [comment]
RP pra master.

**Comment by Rafaeljcg20** [comment]
Publicada
