### ISSUE TITLE
[MELHORIA] Cadastro de Usuário SICONV

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#128]
- [x] Criar uma nova tela no menu "Configurações" "Usuário SICONV" para cadastrar um CPF e Senha para utilizar o webservice do sistema SICONV. Obs: Essa Tela só será visto e alterado pelo Super Usuário, Administrador do módulo;
- [x] Deletar informação de Configuração do WEBSERVICE SICONV usado pelo módulo Emendas a fim de retirar o Usuário e Senha de acesso das configurações gerais do sistema. Obs: Não esquecer de atualizar o aquivo config.inc-exemplo.
- [x] Na tela de Cadastro de Beneficiário, corrigir a funcionalidade de "Atualizar dados SICONV" para utilizar o nome de usuário e senha cadastrados na nova tela "Usuário SICONV" ao invés dos dados de usuário e senha informados no arquivo de configuração do sistema.
- [x] Na rotina diária de atualizar dados SINCONV(/seguranca/www/scripts_exec/spo_consultaSiconv.php) corrigir a implementação para acesso ao webservice pra utilizar o nome de usuário e senha cadastrados na nova tela "Usuário SICONV" ao invés dos dados de usuário e senha informados no arquivo de configuração do sistema.

**Comment by leossb36** [comment]
nome da branch: hotfix-128-emendas-siconv

OBS: 
- [ ] Inserir menu em produção

**Comment by leossb36** [comment]
testado em homologação: 
http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=configuracao/usuario_siconv_form&acao=A
