### ISSUE TITLE
Inserir colunas na Tela Lista de Emendas

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#134]
Incluir colunas na lista principal de Emendas: algum ID/ Sub-unidade / valor (custeio e capital); UF; impedimento (sim ou não); estado atual; valor empenhado e pago.

**Comment by Rafaeljcg20** [comment]
Branch: feature-emenda-lista-subunidade

**Comment by Rafaeljcg20** [comment]
Em fase de Teste.

**Comment by Rafaeljcg20** [comment]
Teste OK

**Comment by macavalheiro** [comment]
ficou faltando a coluna "custeio" e a coluna "capital". 

a coluna id pode ser suprimida e deixar só a coluna "id beneficiário" no incio.

**Comment by macavalheiro** [comment]
na coluna UF, creio que a musa quer a UF do parlamentar.  Sendo isso, não está puxando o dado

**Comment by macavalheiro** [comment]
galera, sugiro segurar essa aqui para o próximo sprint, que acho q ganhamos sinergia se eu juntar ela com outra demanda pra mexer nessa tela

**Comment by Rafaeljcg20** [comment]
Obrigado Marcelo, por informar os detalhes que passaram despercebidos. Foi retirado o Id da emenda, O Id do beneficiário foi movido pra o começo da tabela, o dado de UF está sendo buscado dos dados do Parlamentar e inserimos os dados que ficaram faltando de Capital e Custeio do beneficiário.

**Comment by macavalheiro** [comment]
Massa!

**Comment by Rafaeljcg20** [comment]
RP pra master

**Comment by Rafaeljcg20** [comment]
Publicada.
