### ISSUE TITLE
Inserir regra de negócio em Histórico/Observações

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#136]
Inserir regras de negócios na funcionalidade de inserir Observações na tela de Cadastro de Beneficiários:
* Os usuários com perfil de Unidade não podem ver as Observações feitas pelos usuários com perfis de ASPAR, ADMINISTRADOR E OU SUPER USUÁRIO.

Obs:
* Se possível(desejável), apenas o próprio usuário pode alterar ou excluir sua observação.

**Comment by Rafaeljcg20** [comment]
Existe uma tabela de observações com históricos na tela de Cadastro de Beneficiários. Hoje todos os usuários de todos os perfis podem ver esse formulário, temos que de desenvolver uma condição para que os usuários com perfil de unidade não possam visualizar essas observações e nem os históricos de outras unidades. Por exemplo: Usuário da Ancine não pode ver as observações da ASPAR.

**Comment by Rafaeljcg20** [comment]
Em fase de teste.

**Comment by Rafaeljcg20** [comment]
Nome da branch: feat-issue-136

**Comment by Rafaeljcg20** [comment]
Foram feitas correções no salvar para salvar o cpf correto, e também na funcionalidade de listar para listar corretamente sem duplicação.

**Comment by Rafaeljcg20** [comment]
Usuário ASPAR pra teste: Flavio 010.348.311-00
