### ISSUE TITLE
não consigo excluir itens da tabela de apoio "classificação"

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#139]
@oriontelesdemesquita agora consegui excluir mas não consigo mais gravar nova  - 1/03/2018

**Comment by Rafaeljcg20** [comment]
O sistema já possibilitar excluir, porém o usuário informou que agora não está inserindo corretamente. Corrigir o Inserir da tela de Cadastro de Classificação.

**Comment by RamonCanabarro** [comment]
A pedido P.O, essa demanda foi despriorizada dessa sprint.

**Comment by Rafaeljcg20** [comment]
Oi @g-adler, qual é a pendencia?

**Comment by g-adler** [comment]
@Rafaeljcg20 As funcionalidades parecem estar ok, consegui incluir e excluir os testes feitos.
Demanda jogada para Pending para realizar esta validação

**Comment by Rafaeljcg20** [comment]
Testar em produção

**Comment by Rafaeljcg20** [comment]
Esse era um caso especial de erro que só ocorria em produção por causa de um erro de sequence de banco de dados que estava desatualizada. Executamos um script de correção no ambiente de produção e foi constatado que o erro não acontece mais.

**Comment by Rafaeljcg20** [comment]
Publicada.
