### ISSUE TITLE
[ Monitoramento ] Relatório de Monitoramento PPA

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#141]
Desenvolver um relatório consolidado com informação por "referencia"(janela) e agrupado por meta

Unidade tem acesso do que preencheu.
Administrador tem acesso ao geral

**Comment by Rafaeljcg20** [comment]
relatório listando todas as meta ppa agrupado por janela e meta 

colunas

todos os campos do formulário (anexo, só listar arquivos) mais informações do cabeçalho (previsto, provisionado, empenhado,, liquidado pago) e unidade.

**Comment by macavalheiro** [comment]
Legal! 

Ficou faltando só o campo "unidade" no rol de informações de cada "box de monitoramento".

Pq assim, qdo eu tiver q inserir esses dados no siop eu vou meta a meta (e não unidade a unidade) e aí preciso saber o q cada unidade escreveu. 

Como está agora eu até consigo filtrar meta a meta, mas não consigo saber qual unidade escreveu o que. 

Só inserindo o campo unidade em baixo já resolve (não nos filtros)

**Comment by g-adler** [comment]
Inserido campo de unidade

**Comment by Rafaeljcg20** [comment]
Testado.

**Comment by Rafaeljcg20** [comment]
Publicada
