### ISSUE TITLE
[Painel (página inicial)] Meus Planos Orçamentários

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#142]
relação de PO´s da unidade (com base na tela tabela de apoio vincular PTRES)  

Colunas: " codigo da funcional", nome do PO, Físico,  Unidade, Produto, Monitorado, numero de projetos (com link)

**Comment by rafaeljcg20** [comment]
Demanda será fechada, porque provavelmente era uma anotação pra conceituar o projeto do módulo Monitoramento que já foi desenvolvido.
