### ISSUE TITLE
[Acompanhamento de Localizador/Ação] Formulário Excel - Usado esse ano

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#146]
Esse formulário foi usado esse ano para o processo de acompanhamento orçamentário, só com as unidades do MINC, pois as vinculadas entraram direto no siop

Não precisa se prender ao layout. Na verdade acho esse layout ruim até. Mas para ver os campos que eles fornecem para cada unidade e os que pedem (em branco)

[https://app.zenhub.com/files/114924704/3c886239-80d9-47cf-9ff1-b123d4554ead/download](https://app.zenhub.com/files/114924704/3c886239-80d9-47cf-9ff1-b123d4554ead/download)

**Comment by rafaeljcg20** [comment]
Demanda será fechada, porque provavelmente era uma anotação pra conceituar o projeto do módulo acompanhamento.
