### ISSUE TITLE
[Acompanhamento de Localizador/Ação] obs

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#147]
Ao contrário do PO, q a regra é cada unidade tem o seu. Aqui a maioria dos das ações tem PO´s de várias unidades dentro (a exceção das vinculadas). Eis a maior dificuldade. Penso que faz pouco sentido perguntar pra unidade sobre o produto de uma ação q ela só tem um PO dentro. Mas tem casos q a unidade tem a ação inteira. Aí faz sentido.

**Comment by rafaeljcg20** [comment]
Demanda será fechada, porque provavelmente era uma anotação pra conceituar o projeto do módulo Monitoramento que já foi desenvolvido.
