### ISSUE TITLE
Rotina Diária - Atualizar dados SICONV todos os dias

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#156]
Rotina Diária pra atualizar dados SINCONV dos beneficiários que são de contratos do tipo Convenio.

**Comment by macavalheiro** [comment]
não consigo testar, mas tenho fé q tá rolando. 

Que horário que ele atualiza?

**Comment by Rafaeljcg20** [comment]
Olá @macavalheiro , pra visualizar as rotinas diárias siga os passos: 
* Mudar de módulo para o módulo SIS
* Acessar o menu Principal -> Agendamento Scripts

Nessa tela você pode ver os horários e vários dados das rotinas(scrips) que estão sendo executados.

**Comment by Rafaeljcg20** [comment]
Publicado

**Comment by macavalheiro** [comment]
Massa!

Marcelo Cavalheiro
61 9287 0645


2018-03-28 15:14 GMT-03:00 Rafael <notifications@github.com>:
