### ISSUE TITLE
Inserir VALIDAÇÃO no botão Atualizar dados SICONV

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#157]
Exibir um aviso pra o usuário caso ele tentou atualizar os dados SICONV do beneficiário sem preencher o campo Modalidade de Pactuação com a opção Convenio.

Obs: Os beneficiários só tem dados no SICONV caso a modalidade de pactuação seja Convênio.

**Comment by Rafaeljcg20** [comment]
Testada!
Branch: feature-SICONV-VALIDACAO

**Comment by macavalheiro** [comment]
Musa, é só convênio mesmo que puxa dados do siconv?

e a novas modalidades, termo de fomento e as outras q tb tem siconv?

**Comment by Rafaeljcg20** [comment]
Publicado
