### ISSUE TITLE
[ POR E-MAIL ] Ao clicar em “Gerar PI”, surge uma mensagem com os itens a serem preenchidos. Mas até os que foram preenchidos também aparecem na mensagem. Tem como aparecer só os que realmente estão faltando? Acho que pode confundir as áreas.

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#192]
Ao clicar em “Gerar PI”, surge uma mensagem com os itens a serem preenchidos. Mas até os que foram preenchidos também aparecem na mensagem. Tem como aparecer só os que realmente estão faltando? Acho que pode confundir as áreas.

**Comment by macavalheiro** [comment]
colocar asterisco tb nos campos que são obrigatórios para geração do PI
