### ISSUE TITLE
[ POR E-MAIL ] Empenhado e Pago: ao invés do botão, tem como ser preenchido automaticamente o valor? Porque muitas vezes o valor empenhado e pago são menores que o valor total. Com o botão não da pra visualizar isso

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#194]
Empenhado e Pago: ao invés do botão, tem como ser preenchido automaticamente o valor? Porque muitas vezes o valor empenhado e pago são menores que o valor total. Com o botão não da pra visualizar isso

**Comment by macavalheiro** [comment]
será que é possível automatizar tb o botão "conveniado"
