### ISSUE TITLE
melhorias tela lista emendas

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#202]
- [x] FILTROS (seleção multipla) 
.
- [x] Unidade (Emenda)
- [x] Sub-unidade (Beneficiário)
- [x] Unidade Delegada (Emenda)
- [x] Sub-unidade Delegada (Beneficiário)
- [x] Situação
- [x] Situação Siconv
- [x] Impedimento (sim) (não) [desmarcados igual a qquer (default)
- [x] Aplicar filtros na lista
.
- [x] manter filtro geral ao retornar para tela manter a filtragem
.
- [x] COLUNAS
.
- [x] Emenda (número)
- [x] Unidade (só sigla)
- [x] Autor
- [x] UF (ver com a musa a real necessidade)
- [x] ID (beneficiário)
- [x] Beneficiário
- [x] Subunidade (só sigla)
- [x] Situação
- [x] Proposta (nº) (novo)
- [x] Situação Siconv
- [x] PI (id) (novo)
- [x] Valor (custeio + capital) (novo) 
- [x] Empenhado
- [x] Pago
.
- [x] HINT
.
- [x] Ao passar o mouse em cima de sub-unidade mostrar a subunidade delegada (se tiver)
- [x] Ao passar o mouse no valor (mostrar valor custeio e valor capital)
.
- [x] FORMATAÇÃO CONDICIONAL
.
- [x] ficar a linha toda vermelha se tiver impedimento
.
- [x] LINK´s
- [x] ao clicar no número da emenda ir para emenda e ao clicar no número do id do beneficiário ir para o beneficiário, ao clicar no id pi ir para o pi
.
- [x]  Dar para exportar p/ Excel aquilo que está filtrado.

**Comment by Rafaeljcg20** [comment]
Boa tarde @macavalheiro! Poderia validar pra nós?

**Comment by macavalheiro** [comment]
Muito massa! Parabéns!

Vamos aos ajustes

- Ainda não está aparecendo para o perfil unidade os beneficiários na situação de "PI Gerado" (aquela situação que já tinha comentado contigo)

- O filtro "unidade delegada" pode tirar (aqui basta subunidade delegada)
- Lá na parte de filtro trocar o texto "Unidade" para "Unidade Emenda"
- Lá na parte de filtros trocar o texto "SubUnidade" para "SubUnidade Beneficiário"


- O xls gerado está vindo o número da Emenda (primeira coluna) com os números fora de formatação 

Acho que é só isso. A tela ficou muito funcional! mal vejo de botar em produção e mostrar pro pessoal. Parabéns a toda equipe!

**Comment by Rafaeljcg20** [comment]
Excelente! Vou fazer os ajustes.

**Comment by Rafaeljcg20** [comment]
Corrigido.
