### ISSUE TITLE
[MELHORIA] Criação de nova tela de apoio item / subitem

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#203]

**Comment by macavalheiro** [comment]
tela nova, que vai alimentar os campos item e subitem dentro do formulário padrão do módulo planejamento (modulo planejamento > criar pi> seleção de algum enquadramento de despesa com formulário reduzido ( manutenção ou benefícios ao servidor por exemplo)

**Comment by dougs007** [comment]
Nome da branch :  hotfix-203-planejamento-tabela-apoio-item-subitem

**Comment by dougs007** [comment]
Testado em homologação :  http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/item-manutencao&acao=A

**Comment by macavalheiro** [comment]
Tudo ok! Só pequenas correções:

Excluir os seguintes enquadramentos da tela de " castrar novo":
Contribuição Patronal
Emendas
Finalistico
Financeira
Não Orçamentária
PAC

voltar o nome do menu para "Item/Subitem" (erro meu)

**Comment by rafaeljcg20** [comment]
@dougs007, por favor, cadastrar os novos menus em produção para os perfis de Super Usuário e Administrador.

**Comment by rafaeljcg20** [comment]
Testado em homologação após a refatoração e correção de Branch: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/item-manutencao&acao=A

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro, poderia validar a demanda para publicarmos?

**Comment by rafaeljcg20** [comment]
Observações do @leossb36 sobre itens pendentes pra completar a demanda:
 - [ ] Na tela de proposta alterar em Dados Financeiros os campos de input de Valor, Valor Expansão retirando as casas decimais de centavos e tambem na tabela a mesma coisa, Valor e VI.Expansão
