### ISSUE TITLE
relatório no perfil unidade

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#205]
só com as emendas que são das "unidades" atribuidas ao perfil da pessoa.

tanto as dela mesmo, quanto as delegadas

* Para o usuário do perfil Unidade o sistema só deve mostrar no relatório geral os dados referentes as emendas marcadas pra Unidade do usuário ou Unidades Delegadas dos usuários.

* Se o relatório foi retirado para as unidades, retornar o botão.

**Comment by dougs007** [comment]
Nome da branch :  hotfix-205-emendas-relatorio-unidade

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br
