### ISSUE TITLE
Correção na funcionalidade de Gerar PI - Emendas

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#221]
Ao clicar em  "Gerar PI", gerar o PI no módulo Planejamento, aparecer o ID planejamento lá em cima com o link pro PI Planejamento e enviar email para todos dos perfil planejamento dizendo que chegou emenda para aprovação.

Ao aprovar (lá no módulo planejamento) mudar situação do beneficiário/emenda para "PI aprovado".

- [x] Corrigir funcionalidade Gerar PIs
- [x] Exibir o Id do PI Gerado no Emendas
- [x] Criar estado de PI Aprovado no Emendas

**Comment by Rafaeljcg20** [comment]
Comentário do Marcelo pra auxiliar a correção:

Ao tentar gerar pi deu o seguinte erro
Parse error: syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION) in /var/www/html/treinamentosiminc2/monitora/classes/Pi_PlanoInterno.class.inc on line 1448

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br

**Comment by Rafaeljcg20** [comment]
Foi informado um erro ao gerar pi pelo P.O e a demanda está em correção.

**Comment by Rafaeljcg20** [comment]
[https://app.zenhub.com/files/114924704/965f5331-ed4e-4671-9633-df59834e77a5/download](https://app.zenhub.com/files/114924704/965f5331-ed4e-4671-9633-df59834e77a5/download)

Novo erro informado pelo P.O.

**Comment by Rafaeljcg20** [comment]
Corrigido

**Comment by macavalheiro** [comment]
Rafa, conforme falamos no telefone a parte principal foi! Pelo menos meus 3 últimos testes deram certo. 

Vou começar a fazer uns testes, complicando mais o padrão, pra ver se aparecem erros, e tenho algumas observações menores:

Programa tem aparecido vazio, sempre. 

...

**Comment by Rafaeljcg20** [comment]
Branch: hotfix-issue-221

**Comment by Rafaeljcg20** [comment]
Em conversa com P.O entramos em acordo de resolver essas últimas 4 pendências:
[ ] Novo erro ao gerar PI em função de manutenções recentes.
[ ] Inserir código do beneficiário no cadastro de PI e PI FNC
[ ] Inserir código da emenda concatenando com o titulo do pi na hora de criar o PI no módulo Planejamento.
[ ] Retirar dados orçamentários de execução dos gráficos e painel FNC dos PIs originados do módulo emendas

**Comment by Rafaeljcg20** [comment]
Corrigido.

**Comment by macavalheiro** [comment]
a parte de

"Inserir código do beneficiário no cadastro de PI e PI FNC" e 
"Inserir código da emenda concatenando com o titulo do pi na hora de criar o PI no módulo Planejamento."

ficou bem bom!

vi que parou de somar em uma das tabelas do FNC, mas na de cima (por unidade) ainda tá somando (creio que faltou replicar a solução para essa tabela de cima tb)

já no painel (sem ser fnc) vi q não está mais somando na coluna planejado, mas está somando na coluna dotação. e a funcional está aparecendo lá em baixo com valor zerado só na coluna planejado.
