### ISSUE TITLE
[MELHORIA]Monitoramento PNC

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#222]
![01.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/f53a3238-9c08-49c8-abd8-0f81815d33fe)

![02.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/38ef17af-3f4c-4a75-94cf-9aae2ca8329d)

![03.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/a5a77fb1-a65f-4bd2-bea5-e11da0206736)

![04.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/fe1d488a-9776-4b4f-a85e-3ad5ada58735)

![05.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/bed3badc-2771-4bc3-9973-0e009a54d0f8)

Desenvolver a nova tela de Monitoramento das metas PNC que o Moises conceituou através do protótipo e acrescentar as seguintes mudanças:
- [x] Um campo Plano Internos Associados: Número e link para os pi´s (igual formulário ppa)
- [x] No lugar do gráfico, tabela com a informações de "previsto, provisionado, empenhado, liquidada e pago para meta (igual a componente antiga (antes do gráfico) do formulário  ppa). Ao clicar ir para um pop up com o gráfico.
- [x] Botão de salvar versão final
- [x] Informação de histórico da seguinte forma: "Salvo por: João jose da silva  data e hora".
- [x] Exercício Corrente > editável para todos
- [x] Exercícios anteriores > editável só para perfil Super Usuário, Administrador e PNC(futuramente fazer esquema de deixar a unidade editar e submeter a aprovação do PNC, ou ter histórico)

**Comment by rafaeljcg20** [comment]
Obs: Resolver problema de performance(loop de requisições).

**Comment by dougs007** [comment]
Na fase de teste foram encontrado(s) o(s) seguinte(s) erro(s):
- [ ] Ao preencher indicadores, atividades e anexos e enviar para aprovação, ao retornar na meta, o sistema atualmente permite que seja enviado novamente o monitoramento. Soluções-> Não mostrar o botão ou exibir mensagem dizendo que já foi enviado.

**Comment by macavalheiro** [comment]
unidade deve poder editar só se tiver janela ativa (se a data atual estiver dentro da janela)

tentei alterar data de janela, ou incluir nova janela para o pnc e deu o erro em anexo:

[https://app.zenhub.com/files/114924704/1f2c97b8-b185-4cff-a660-4813cdab52eb/download](https://app.zenhub.com/files/114924704/1f2c97b8-b185-4cff-a660-4813cdab52eb/download)xo

**Comment by macavalheiro** [comment]
está disponível para unidade as opçoes de ditar janela, classificação do menu apoio e tb as opções do menu sistema. Isso não deve aparecer para unidade.

**Comment by macavalheiro** [comment]
ao clicar em editar indicador (2010 a 2017) não serem obrigatórios os campos data e justificativa

**Comment by macavalheiro** [comment]
em atividades inverter as colunas "produto ou serviço resultante" e "quantidade"

**Comment by macavalheiro** [comment]
Caros, acho q está ficando legal, mas tem algumas coisas para corrigir. Fiz algumas observações iniciais aí em cima, mas quero ver se consigo agendar com a coordenadora do pnc para colher os comentários dela ainda.

**Comment by rafaeljcg20** [comment]
- [ ] Unidade deve poder editar só se tiver janela ativa (se a data atual estiver dentro da janela)
- [ ] Tentei alterar data de janela, ou incluir nova janela para o pnc e deu o erro em anexo
- [ ] Está disponível para unidade as opçoes de ditar janela, classificação do menu apoio e tb as opções do menu sistema. Isso não deve aparecer para unidade.
- [ ] Ao clicar em editar indicador (2010 a 2017) não serem obrigatórios os campos data e justificativa
- [ ] Em atividades inverter as colunas "produto ou serviço resultante" e "quantidade"

**Comment by rafaeljcg20** [comment]
Obrigado @dougs007 por inserir a opção UF com o comportamento de filtrar as opções de Municípios.
