### ISSUE TITLE
Perfil Unidade não pode:

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#223]
- [x]  Excluir emenda
- [x]  Excluir beneficiário
- [ ]  excluir nenhuma observação (novo) (idealmente a edição e exclusão das observações só poderiam ser feita pela própria pessoa que escreveu) Obs: O perfil Super Usuário, Administrador ou ASPAR podem editar ou excluir as observações das Subunidades.
- [x]  Editar ou excluir qualquer informação da coluna dados financeiros
- [x] Gerenciar cadastro usuário
- [x]  Entrar em qualquer tabela de apoio
- [x]   Remover menu Auditoria

**Comment by g-adler** [comment]
Remover permissões do Perfil Unidade.

**Comment by dougs007** [comment]
Nome da Branch :  issue-223
