### ISSUE TITLE
Tela de vinculo Beneficiário com Proposta(SICONV)

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#227]
qdo tem 2 cnpj iguais dentro da mesma emenda sistema não puxa as informações

possível solução: campo manual para inserir manualmente o número de proposta nesses casos e fazer o busca por esse número. Esse campo só deve ser editavel para perfil aspar

Melhor se o campo for na tela lista. Mas se for dentro do formulário tb tá valendo.

**Comment by orionteles** [comment]
Um caso de exemplo: http://siminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8684

**Comment by g-adler** [comment]
Adicionar campo do número da proposta na listagem geral de Emendas.
Ao clicar no número, abrir um modal onde o usuário vai selecionar qual proposta faz parte daquele beneficiário.
Se não tiver o número incluir ícone de Editar (lápis).

**Comment by RamonCanabarro** [comment]
Branch : hotfix-issue-63

**Comment by Rafaeljcg20** [comment]
Observações:
* Retirar espaço da coluna ações;
* Mudar Título do modal para Selecionar Proposta;
* Inserir colunas(Objeto, Sequencial, Nº Convênio, Situação) conforme a lista de propostas da Tela de beneficiários.

**Comment by Rafaeljcg20** [comment]
Corrigida pelo @RamonCanabarro

**Comment by Rafaeljcg20** [comment]
Durante o teste foi encontrado um caso estranho onde na tela lista de emendas aparece um beneficiário com o ícone de botão, mas ao abrir o tela modal de Selecionar Proposta não lista nenhuma proposta.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/3feea5a2-8486-452d-a572-0c782af88d63)

**Comment by Rafaeljcg20** [comment]
Corrigido.

**Comment by macavalheiro** [comment]
qdo seleciono uma proposta, ela não está ficando marcada. 

a marcação funciona internamente. mas ao entrar novamente no menu de marcação, a seleção não fica, indicando qual foi marcada

**Comment by Rafaeljcg20** [comment]
Ola @macavalheiro, corrigimos o botão de selecionar e também a consulta principal de emendas para os casos de exceção que o botão Selecionar Proposta deve ser exibido. 

Poderia tentar validar novamente?

**Comment by macavalheiro** [comment]
caros, na primeira validação tinha o nº da proposta. agora saiu. Esse é o número mais importante.

Assim solicito tirar as colunas  "sequencial" e "nº convênio" e incluir "nº proposta"


A seleção está gravando, mas agora qdo se desmarca e salva uma opção, não está gravando essa "desmarcação"

**Comment by Rafaeljcg20** [comment]
Oi @macavalheiro , Corrigimos a funcionalidade. Poderia tentar validar novamente?
