### ISSUE TITLE
Perfil´s 

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#229]
- [x] Criar perfis
Administrador 
PNC
Unidade 
Consulta 

- [x] Configurar funcionalidade de sincronizar Perfis do Planejamento com o Monitoramento para que os usuários estejam com o mesmo Perfil e Unidade associada.
- [x] Perfil PNC ve o painel do jeito que está mas só pode entrar no detalhe das metas PNC
- [x] Perfil Admin vê tudo e entra em tudo
- [x] Perfil Unidade vê painel e edita só da sua unidade
- [x] Perfil Consulta vê tudo e entra em tudo mas não pode editar nada

- [x] É possível espelhar todos que tem perfil unidade lá no módulo planejamento, pra cá? Resp: Sim.

**Comment by dougs007** [comment]
Nome da branch: hotfix-222-monitoramento-pnc  (mesma branch da demanda do PNC)

**Comment by Rafaeljcg20** [comment]
@dougs007 , não esquece de fazer um git pull na branch hotfix-222-monitoramento-pnc pq eu atualizei ela agora.

**Comment by Rafaeljcg20** [comment]
@dougs007, vou precisar criar uma outra branch pra essa demanda e desvincular ela do monitoramento PNC.

**Comment by dougs007** [comment]
Nome da nova branch : hotfix-229-monitoramento-perfis

**Comment by Rafaeljcg20** [comment]
Oi @macavalheiro, dá pra espelhar inclusive o perfil consulta.
