### ISSUE TITLE
[CORREÇÃO] Consertar cor da fonte do simular usuário

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#235]
![image.png](https://images.zenhubusercontent.com/5a7098c54b5806bc2bc4e41d/b0368ff9-3735-4008-bb41-512a1b9ca832)

Na tela principal do módulo proposta, ao clicar em simular usuário é exibido um Popup modal e nesse modal o cabeçalho da lista de usuários não está visível conforme a imagem em anexo. Mudar a cor da fonte dos textos do cabeçalho para qualquer cor que fique visível para o usuário final.

Observação: Se possível consultar o Design Moises para escolher uma cor adequada.

**Comment by leossb36** [comment]
branch: hotfix-235-cor-de-fonte-simular-usuario

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=inicio&acao=C
