### ISSUE TITLE
Inserir link com acesso a tela popup "Espelho de PI" na Tela de Painel

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#237]
Inserir o link com acesso ao Popup nas telas modais do painel "PI's da Unidade" e "PI's da Funcional na Unidade".

**Comment by RamonCanabarro** [comment]
branch: hotfix-issue-237-espelho-pi

**Comment by Rafaeljcg20** [comment]
Corrigido os painéis. E as gerações de PI que envolviam erros com números do convenio e SEI.
