### ISSUE TITLE
[MELHORIA] Notificação de e-mail na tramitação de beneficiários

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#251]
- [x] E-mail para todos da Unidade > sempre que um beneficiário for tramitada para unidade dela. (qdo vai para situação  "em preenchimento pela unidade")

- [x] E-mail para todos do perfil  ASPAR > sempre que um beneficiário for devolvido para correção. (situação "em correção)

- [x] E-mail para todos do perfil Planejamento (módulo Planejamento) > sempre que gerar PI (estado PI Gerado)

Informações essenciais a se constar no e-mail (usar modelo módulo Planejamento)

Número da Emenda
Parlamentar
Funcional com PTRES

Id Beneficiário
Nome  Beneficiário
Nº Proposta; (caso tenha)
Valor Custeio e Capital

ID PI: (no caso de já ter PI)
Título do PI (no caso de já ter PI)

Tramitado por: XXXXX XXXX
Fone
Email:

**Comment by Rafaeljcg20** [comment]
Branch: hotfix-251-emendas-email

**Comment by Rafaeljcg20** [comment]
Olá @macavalheiro, quando puder, tente validar essa demanda pra nós.

**Comment by Rafaeljcg20** [comment]
Correções solicitadas:
- [ ] Mudar o texto do remetente do e-mail para: SIMINC2 - SPOA - Emendas.
 - [ ] Titulo da mensagem de email está com a descrição da ação do workflow errada.
 - [ ] Mudar Label de "Enviado para Preenchimento da Unidade por" para "PI Gerado por:" e também o texto do email de devolução.
 - [ ] Corrigir erro pq os PIs gerados que não são do tipo FNC estão sendo gerados com a situação de 'em cadastramento' ao invés de 'aguardando aprovação'.

**Comment by Rafaeljcg20** [comment]
![Captura de tela de 2018-05-25 19-30-46.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/35821d86-16f3-495e-9c20-e90cbc175dcd)
@macavalheiro, poderia validar a demanda novamente. As correções foram efetuadas e publicadas em homologação e produção.
