### ISSUE TITLE
tela lista ementa como principal (home)

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#255]
Criar o menu para o painel
Redirecionar as telas para que a tela inicial do sistema seja a Tela lista de emendas ao invés da Tela de Painel.

Instruções: 
- [x] Criar um novo arquivo separado chamado painel.inc com o código do arquivo inicio.inc
- [x] Criar item de menu para esse novo arquivo com o nome de Painel para os perfis Super Usuário, Administradores, Aspar
- [x] No arquivo inicio ter redirecionamento para o arquivo de Lista de Emendas.

**Comment by dougs007** [comment]
Nome da Branch:   issue-255

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/emenda&acao=A
