### ISSUE TITLE
unidade não deve poder excluir pi

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#256]
a unidade conseguiu excluir o pi 157
- [x] Não pode aparecer o botão de excluir pra o usuário do perfil Unidade.

**Comment by dougs007** [comment]
Nome da Branch : issue-256

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapimanter&acao=A
