### ISSUE TITLE
Funcionalidade de atualização da funcionais

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#259]
web service das funcionais.

**Comment by macavalheiro** [comment]
Funcionalidade para resolver o problema das funcionais zeradas do WS.

Criar uma tela que mostre as ultimas atualizações com as seguintes colunas

"Data ", "Horário", "valor total Empenhado", "valor total provisionado", "valor total pago" "valor total liquidado"


Ao clicar em cada atualização seria possível voltar o sistema para aquele momento (como o botão de desfazer do word) 

Deve existir acima ainda um botão de "atualizar agora" (como siop)

**Comment by rafaeljcg20** [comment]
De acordo com a verificação no sistema feito hoje dia 20/11/2018 a demanda foi concluída com a criação do botão de Atualizar SIOP no módulo Planejamento Orçamentário que permite atualizar os dados de execução a qualquer momento do dia.
