### ISSUE TITLE
[CORREÇÃO] Validação de valores financeiros dos beneficiários

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#264]
Na tela de Cadastro de Beneficiários, Inserir restrição para que não seja possível inserir dado financeiro superior a soma dos dados Financeiros da Emenda de mesmo GND. Semelhante a tela Cadastro de Proposta do módulo Proposta Orçamentária.

**Comment by dougs007** [comment]
Nome da branch:  hotfix-264-validacao-beneficiarios

**Comment by isaiassm** [comment]
Ao fazer o teste , Quando clicado em alterar os dados Financeiros não está alterando!

**Comment by dougs007** [comment]
Testado em : http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8420
