### ISSUE TITLE
[tela emenda] funcional da emenda

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#271]
não está vindo o objetivo (na maioria dos casos)

e a posição do objetivo está trocada com a do localizador (na funcional)

**Comment by Rafaeljcg20** [comment]
Tela de Emendas: http://siminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/emenda_form&acao=A&emeid=4745

 - [ ] No combo de ptres inverter a posição do objetivo com o localizador
 - [ ] No combo de ptres verificar se de fato não existem os objetivos quando não retorna o valor
 - [ ] Quando houver objetivo trazer marcado o objetivo na aba CADASTRO COMPLEMENTAR DO PI

**Comment by dougs007** [comment]
Boa tarde @macavalheiro, foi averiguado os casos em que não retornam os objetivos, e atualmente a funcionalidade não está visível por conta de campos em branco. Os objetivos que estão preenchidos ele lista normalmente.
Solução: Será desenvolvido um script para atualizar esses cadastros em branco para a funcionalidade ter uma maior visibilidade !

**Comment by macavalheiro** [comment]
Blz!

Marcelo Cavalheiro
61 9287 0645


Em 23 de abril de 2018 15:04, Douglas Santana <notifications@github.com>
escreveu:

**Comment by macavalheiro** [comment]
a posição do objetivo e do localizador continua invertida na tela de emenda

**Comment by macavalheiro** [comment]
feito

**Comment by Rafaeljcg20** [comment]
Branch: hotfix-271-emenda-funcional
