### ISSUE TITLE
aviso  e asterisco nos campos obrigatórios

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#278]
atualmente ao não preencher ele lista todos.

tb falta o asterisco para o usuário saber de antemão os campos obrigatórios

- [x] Adicionar um * vermelho nas labels dos campos obrigatórios, porém não deve colocar o atributo "required" para não bloquear o cadastro.
- [x] Alterar a mensagem ao gerar PI  caso todos os campos obrigatórios não forem preenchidos para: "Os campos com asterisco são obrigatórios. Favor preenchê-los e salvar o formulário antes de Gerar PI".

**Comment by macavalheiro** [comment]
Objetivo PPA
Meta PPA
Iniciativa PPA
Meta PNC
Indicador PNC

não são obrigatórios.

Marcelo Cavalheiro
61 9287 0645


Em 24 de abril de 2018 15:58, Leonardo Dos Santos Silva Barreiros <
notifications@github.com> escreveu:

**Comment by leossb36** [comment]
branch: hotfix-278-aviso-e-asterisco

**Comment by Rafaeljcg20** [comment]
Os campos <b>Unidade e Funcional</b> do formulário de Cadastro de Emendas não estavam com a sinalização de obrigatório pra gerar PI.

**Comment by Rafaeljcg20** [comment]
Corrigido.

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br

**Comment by macavalheiro** [comment]
Massa! Valeu! 

só uma coisa que notei é que dentro de observações "data" e "histórico" tb estão com asterisco. Se for fácil tirar o asterisco desses campos melhor para não confundir, de qquer forma já vou fechar essa demanda pq o resto ficou 100%
