### ISSUE TITLE
Cadastro de Proposta Orçamentária(Pré-PI)

### ISSUE THREAD

**Issue by orionteles** [culturagovbr/siminc2#295]

**Comment by macavalheiro** [comment]
* Na funcional é necessário constar o nome do PO tb  (Funcional - Nome da Ação - Nome do PO)
* Centralizar o valor de custeio da funcional  e os box de colocar valor (custeio e capital) do pré-pi
* Valor adicional de custeio e capital tirar os centavos
* Falta o "botão de importar projetos (PI´s) da captação executiva de 2018
* Mesmo com valor de Limite autorizado na unidade zerado, autorizou eu gravar e não travou
* após gravar e entrar no pré-pi puxou o valor de limite do módulo planejamento. Idealmente precisamos de uma tela de limite unidades dentro do modulo e funcionando de forma individualizada.
* Tinha imaginado uma tela de vincular funcionais independente do módulo planejamento tb. Inicialmente não vejo problema, mas temo que com a entrada do módulo Planejamento 2019 (lá por novembro) possa dar alguma incompatibilidade. 
* Na verdade tinha imaginado todas a tabelas de apoio independente dentro do próprio modulo, mas a outras creio que não há problemas em ser as mesas. Entretanto qdo criar o exercício de 2019 elas ficam separadas das tabelas de 2018, é isso?
* valor do campo "Limite Disponível na Unidade" ainda não está funcionando. Campo "Total Cadastrado na Funcional" tb não

**Comment by macavalheiro** [comment]
agora q vi q vc marcou o calculo como não feito. pode desconsiderara as observações de calculo, então.

**Comment by macavalheiro** [comment]
botão para puxar projeto da captação executiva 2018 (lindberg)

**Comment by orionteles** [comment]
@macavalheiro Os ajustes foram realizados. Alguns pontos coloquei uma observação no final e estão marcados com "***". Outros tirei o checklist e coloquei uma bolinha e justifiquei o motivo, ok?

**Comment by macavalheiro** [comment]
as ações finalisticas (programa 2027 não estão aparecendo, nem na tela de vincular funcional (ptres)

**Comment by orionteles** [comment]
@macavalheiro Foram importados em 06/05/2018 129 funcionais vindas do SIOP, dessas somente 68 foram vinculadas RP (e somente RP 0 e 1), pois como não temos a informação do SIOP, comparei as de 2018 com as de 2019 e usei a mesma informação. Sendo assim, ao selecionar uma unidade e o enquadramento, o combo de funcional traz poucos registros por conta do casamento entre ptres e RP. Temos que ver a melhor forma de vincular os RPs nessas funcionais.

**Comment by macavalheiro** [comment]
ok Orion! mas o problema será que é não estar vindo a funcional (por não estar no siop) ou só é a falta do rp?


outra coisa que notei é que 
o limite "setado" na tela de limite unidade não está vindo na maioria das unidades

**Comment by macavalheiro** [comment]
no ibram veio, mas na fcr e fbn por exemplo já não veio

**Comment by macavalheiro** [comment]
Fiz uma revisão e vou deixar aqui minhas observações: 


Falta funcionalidade de importar de PI 2018, (essa funcionalidade não é imprescindível mas é bem importante e estava especificada na demanda inicial) 

algumas sub-unidades não estão puxando o "limite autorizado na unidade" (exemplos que não puxaram FBN, FCR, Funarte, Cogep, SCDC etc) (erro)

campos valor do projeto  custeio e capital e quantidade´s  ser número inteiro, sem vírgulas (ajsute) 

Colocar campos do box "solicitação de valor adicional"  quantidade após custeio e capital
   	e colocar campos custeio e capital lado a lado (como é no "valor do projeto")  (ajuste)

**Comment by macavalheiro** [comment]
Meus comentários, após análise:

Não puxou produto e unidade do localizador e do PO  (Erro) (entrei no siop e a informação existe)

Colocar campo  "Limites Pré- PI" entre os campos Subunidade Vinculadas à Funcional e Quantidades (ajuste)

Campo Quantidade Expansão PO colocar acima de de Justificativa Expansão. (criar um box só pra expansão assim como no pré pi (ajuste)

Limites pré pi está trazendo valor total aberto em pré-pi, o valor correto é só dos pre-pis aprovados. (erro)

Inserir validação dos dados finaceiro. Respeitar os  valores  de limites pré-pi APROVADOS tanto para 
> valor custeio
> valor capital
> valor custeio expansão
> valor capital expansão (erro)



Exibição do valor de natureza de despesa está aparecendo número estranho e não o número selecionado (erro)

Exibição do valor de idoc está aparecendo número estranho e não o número selecionado (erro)

valor da quantidade do localizador não está salvando
