### ISSUE TITLE
Criação dos perfis

### ISSUE THREAD

**Issue by orionteles** [culturagovbr/siminc2#297]

**Comment by macavalheiro** [comment]
só falta espelhar os perfis do módulo planejamento. principalmente dos perfis unidade

**Comment by Rafaeljcg20** [comment]
Branch: feature-proposta-orcamentaria

**Comment by Rafaeljcg20** [comment]
Olá @macavalheiro, já configuramos o espelhamento. Poderia validar novamente? :)
