### ISSUE TITLE
[MELHORIA]Atualização de senha-Habilitar copiar e colar

### ISSUE THREAD

**Issue by moisesrlima** [culturagovbr/siminc2#299]
Na tela de alterar a senha do usuário, fazer as seguintes mudanças: 
- [x] Alterar o comportamento do campo de <b>senha atual</b> para permitir o recurso de copiar e colar.

Obs: Isso permite que os usuários mais avançados tenha mais celeridade em fazer o cadastro. Essa senha pode ser copiada porque ela será esquecida, já a nova senha deve ser digitada para ajudar a memorização.
- [x] Inserir funcionalidade de "toggle" para ocultar e exibir os caracteres da senha.
Obs: Isso também ajuda na memorização e garante que o usuário está colocando o carácter correto no momento da digitação.

**Comment by dougs007** [comment]
Nome da branch :   hotfix-299-recuperacao-senha

OBS: Para simular a funcionalidade aplicada na demanda, deve ser solicitado a troca de senha em
Sistema > Usuário > Alterar Senha.

**Comment by leossb36** [comment]
testada em homologação: 
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=sistema/usuario/altsenha&acao=X
