### ISSUE TITLE
Organizar menu a apoio da seguinte maneira

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#311]
Tabela de Apoio
  * Reunião FNC
  * Modalidade de Pactuação
  * PPA
      - Objetivo
      - Meta
  * Meta PNC
  * Unidade/Subunidade (antiga Unidade Orçamentária)
  * Área Cultural
  * Enquadramento de Despesa
  * Ação

Configuração:
  * Limite Subunidade
  * Vincular Meta PPA
  * Vincular Meta PNC
  * Vincular Indicador PNC
  * Vincular Funcional (PTRES)
  * Vincular Enquadramento/RP

**Comment by dougs007** [comment]
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/47fadfc4-2346-48fb-8eb0-5afc0ea58b69)

**Comment by dougs007** [comment]
Boa tarde @macavalheiro, por favor, poderia validar a demanda?
