### ISSUE TITLE
botão de impedimento ter a opção de marcar Não

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#320]

**Comment by Rafaeljcg20** [comment]
- [ ] Substituir o input radio do impedimento para checkbox com valores Sim e Não. QUando marcar "Sim", continuar com a inteligência de exibição dos campos ocultos de impedimento, da mesma forma que a opção "Não" os oculta.
- [ ] No relatório geral, esse campo de impedimento deve trazer "Sim", "Não" ou deixar em branco de acordo com o que for selecionado.

**Comment by macavalheiro** [comment]
módulo emendas > formulário padrão de beneficiário (que pode ser acessado clicando sobre o número da  coluna "id beneficiario "> impedimento

**Comment by dougs007** [comment]
Nome da Branch :  hotfix-320-botao-de-impedimento

**Comment by dougs007** [comment]
Segue Scripts a serem revisados e caso não haja ressalvas, publicados em produção ao fechamento da demanda :

- [ ] Script para adicionar na tabela do banco a coluna do botão de não se aplica.

BEGIN;
--ROLLBACK;

ALTER TABLE emendas.beneficiario ADD COLUMN benimpedimento integer; 

COMMENT ON COLUMN emendas.beneficiario.benimpedimento IS 'Possui Impedimento:
0 - Não
1 - Sim
2 - Não se Aplica';

--COMMIT;


- [ ] Script para atualizar no banco os registros existentes de acordo com a nova funcionalidade
/*
SELECT 
             benid, 
             impid, 
             benimpedimento  
FROM emendas.beneficiario
WHERE 
             impid = 0; -- 208 registros

SELECT 
             * 
FROM emendas.beneficiario -- 655 registros
*/
BEGIN;
--ROLLBACK;

UPDATE emendas.beneficiario set benimpedimento = 1 
WHERE impid <> 0;

UPDATE emendas.beneficiario set benimpedimento = 0 
WHERE impid = NULL;

COMMIT;
