### ISSUE TITLE
ao marcar TED sim, não exigir preenchimento de modalidade de pactuação

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#321]
Ao marcar TED sim, não exigir preenchimento de modalidade de pactuação para gera PI

**Comment by macavalheiro** [comment]
modulo emendas  no formulário padrão de beneficiario 

modulo emendas > "clicar sobre o campo numero da coluna "id beneficiário"

**Comment by isaiassm** [comment]
Testado em Homologação: http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8420

**Comment by rafaeljcg20** [comment]
Branch: hotfix-321-emendas-nao-obrigatoriedade-pactuacao
