### ISSUE TITLE
[tela lista emendas] pesquisar por número de beneficiário 

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#322]

**Comment by Rafaeljcg20** [comment]
[Uploading... 2.png ]

**Comment by Rafaeljcg20** [comment]
[Uploading... 2.png ]

**Comment by Rafaeljcg20** [comment]
![2.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/14b50d8b-71b6-41a3-a306-e7071ea7a7d3)

**Comment by dougs007** [comment]
Nome da branch :  hotfix-322-planejamento-beneficiarios

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br

**Comment by macavalheiro** [comment]
tentei no id 8486 não funcionou
