### ISSUE TITLE
Cadastro de Proposta LOA

### ISSUE THREAD

**Issue by orionteles** [culturagovbr/siminc2#323]

**Comment by macavalheiro** [comment]
Parte da ação:
* Falta campo RP (apresentado pelo sistema a partir do enquadramento)
* Faltam campos Unidade e Produto da Ação (a partir do siop)
* A Funcional está indo até PO.  A caixa de seleção de PO deve ser individualizada abaixo. Com código e descrição

Parte PO´s (a partir da caixa de seleção):
* Falta a idicação da Sub-unidade ligada aquele PO (creio que aqui precisaremos de uma tabela de apoio vincular PTREs própria do módulo, uma vez que no outro módulo as vezes vinculamos mais de uma subunidade)
*Falta campo quantidade PO (a ser preenchido pelo usuario) e campos Unidade e Produto Intermediário (SIOP)

*Campo Quantidade Expansão somente ligado ao PO selecionado
* falta campo informando Limite valor (custeio e capital) e limite expansão (custeio e capital).
* Só estão aparecendo os dados financeiros ao salvar. O ideal seria que ao selecionar o PO já aparecessem. 
* Colocar campos Valor e Valor Expansão, após o IDOC.



a principal questão é a parte da estrutura, que a seleção do PO ainda não está individualizada possibilitando inserir tanto as os dados referente a ação, quanto os dados referentes ao PO individualmente.

**Comment by orionteles** [comment]
@macavalheiro @Rafaeljcg20 Os ajustes foram realizados. Alguns pontos coloquei uma observação no final e estão marcados com "***". Outros tirei o checklist e coloquei uma bolinha e justifiquei o motivo, ok?

**Comment by macavalheiro** [comment]
favor colocar troca "produto" por "Produto" (iniciando com letra maiuscula)

**Comment by Rafaeljcg20** [comment]
Oi @macavalheiro, corrigimos. Poderia validar pra gente? : )

**Comment by Rafaeljcg20** [comment]
Não puxou produto e unidade do localizador e do PO  (Erro) (entrei no siop e a informação existe)

**Comment by macavalheiro** [comment]
Meus comentários, após análise (agora colando no lugar certo):

Colocar campo "Limites Pré- PI" entre os campos Subunidade Vinculadas à Funcional e Quantidades (ajuste)

Campo Quantidade Expansão PO colocar acima de de Justificativa Expansão. (criar um box só pra expansão assim como no pré pi (ajuste)

Limites pré pi está trazendo valor total aberto em pré-pi, o valor correto é só dos pre-pis aprovados. (erro)

Inserir validação dos dados finaceiro. Respeitar os valores de limites pré-pi APROVADOS tanto para

valor custeio valor capital valor custeio expansão valor capital expansão (erro)

Exibição do valor de natureza de despesa está aparecendo número estranho e não o número selecionado (erro)

Exibição do valor de idoc está aparecendo número estranho e não o número selecionado (erro)

valor da quantidade do localizador não está salvando
