### ISSUE TITLE
Alterações na listagem de Beneficiários dentro do Cadastro de Emendas

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#325]
- [x] Excluir a coluna Esfera e forma de execução e incluir as colunas número da proposta, situação siconv,   custeio e capital empenhado, pago e um total em baixo ficando na seguinte ordem:  (5 pontos)

Ações  /  Proponente / Unidade / nº proposta / situação siconv / custeio / capital / empenhado / pago

e o total abaixo.

OBS1: Pegar o left que tem na listagem de emendas: nº proposta / situação siconv
OBS2: Pegar da View monitora.vw_planointerno: custeio / capital / empenhado / pago

**Comment by Rafaeljcg20** [comment]
Oi @dougs007 , temos os seguintes erros pra resolver que foi detectado em fase de teste:
O Número de capital e custeio não está igual ao número de capital e custeio da Tela principal Lista de Emendas.
*Dica: O Valor da emenda 201811350010 é (custeio é 550.000,00 e capital 0,00), enquanto o valor mostrado na lista de beneficiários é (Custeio: 681.504,00 e capital 0,00).

**Comment by dougs007** [comment]
@Rafaeljcg20 Resolvido !

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br

**Comment by Rafaeljcg20** [comment]
Oi @macavalheiro, poderia validar pra nós?

**Comment by macavalheiro** [comment]
Legal! Só faltou o totalizador abaixo.

**Comment by dougs007** [comment]
Adicionado o totalizador !

**Comment by macavalheiro** [comment]
já vi aqui que tá ok e já fechei, @Rafaeljcg20

**Comment by Rafaeljcg20** [comment]
Nome da branch: hotfix-325-lista-emendas
