### ISSUE TITLE
no espelho de pi de emenda está aparecendo os dados quem abre 

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#326]
retirar

**Comment by macavalheiro** [comment]
no módulo planejamento> lista pi> filtrar só emendas > abrir o espelho (clicar sobre o titulo) de qualquer uma delas. 

ao fim do espelho vai aparecer os dados do usuario q abriu, que são os q devem ser retirados

**Comment by dougs007** [comment]
Nome da Branch : hotfix-326-planejamento-espelho-pi
