### ISSUE TITLE
[MELHORIA] Relatório geral de Emendas

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#327]
Na tela Relatório Geral(Acessada pelo menu principal: Relatórios->Relatório Geral) fazer as seguintes mudanças:
- [x] Retirar as colunas GND, Mod. aplicação, Fonte, Valor e inserir no lugar as Colunas "Custeio" e "Capital" respectivamente com o total dos valores cadastrados pra emenda de Custeio e Capital. Obs: Os valores de custeio são os regristros financeiros que têm GND igual ou menor que 3, e os valores de capital são os registros financeiros que têm GND igual ou maior que 4;
- [x] Retirar as colunas Vl. Beneficiário, Vl. Priorizado, Vl. Contigenciado e inserir no lugar as Colunas "Vl. Beneficiário Custeio", "Vl. Priorizado Custeio", "Vl. Contingenciado Custeio" e "Vl. Beneficiário Capital" , "Vl. Priorizado Capital", "Vl. Contingenciado Capital" respectivamente com o total dos valores cadastrados pra cada Beneficiário de Custeio e Capital;
 - [x] Corrigir erro de duplicação dos registros do relatório causados por emendas e ou beneficiários que tenham mais de um dado cadastrado na seção de dados financeiros.

**Comment by isaiassm** [comment]
Nome da branch: hotfix-327-Emendas-relatorio-custeio-capital

**Comment by dougs007** [comment]
Testado em Homologação !

**Comment by macavalheiro** [comment]
na verdade era a coluna valor beneficiário que precisa aberto em custeio e capital...  agora q o valor da emenda já está poderia deixar, mas tb colocar o valor benefiario nesse formato...

se precisar abrir outra demanda avisem

**Comment by macavalheiro** [comment]
na verdade era a coluna valor beneficiário que precisa aberto em custeio e capital... agora q o valor da emenda já está poderia deixar, mas tb colocar o valor benefiario nesse formato...

se precisar abrir outra demanda avisem

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro, não precisa abrir outra demanda, está tudo bem. Eu expliquei essa demanda pra o Isaias, só que não detalhei e outro membro da equipe foi fazer e não foi feito o repasse das informações. Vamos corrigir.

**Comment by rafaelfcar** [comment]
Alterações efetuadas.

**Comment by rafaelfcar** [comment]
Leo, favor testar novamente.

**Comment by leossb36** [comment]
testado em Homologação com adição dos campos que faltava "Vl. Priorizado Custeio", "Vl. Contingenciado Custeio", "Vl. Priorizado Capital", "Vl. Contingenciado Capital" respectivamente com o total dos valores cadastrados pra cada Beneficiário de Custeio e Capital.

**Comment by macavalheiro** [comment]
por gentileza alterar a ordem das colunas de 
![image.png](https://images.zenhubusercontent.com/5aa819f64b5806bc2bcab1c5/7e247d06-d368-4c75-934e-8b74c9204f60)

Vl. Benefiário Custeio / Vl Beneficiário Capital/ Vl Priorizado Custeio / Valor Priorizado Capital / Vl. Contigenciado Custeio / Vl Contigenciado Capital

**Comment by dougs007** [comment]
Bom dia @macavalheiro, alterações feitas e testado em homologação !
