### ISSUE TITLE
Criação de Ano Exercício(Via Script de banco)

### ISSUE THREAD

**Issue by orionteles** [culturagovbr/siminc2#344]

**Comment by orionteles** [comment]
- [ ] Objetivo PPA
- [ ] Iniciativa PPA
- [ ] Unidade de Medida PO
- [ ] Produtos PO
- [ ] Unidade de Medida PI
- [ ] Produtos PI
- [ ] Enquadramento de Despesa
- [ ] Área Cultural
- [ ] Item Manutenção
- [ ] Sub Item Manutenção
- [ ] Segmento
- [ ] Modalidade de Pactuação
- [ ] Meta PPA
- [ ] Meta PNC
- [ ] Vínculo de Meta com Objetivo
- [ ] Vínculo de Meta com Unidade
- [ ] Ações
- [ ] Localizadores
- [ ] PO

**Comment by orionteles** [comment]
@Rafaeljcg20 Adaptei o script de atualização de Funcionais (o que recupera as ações e funcionais automaticamente) para receber o exercício e o momento via parâmetro. Dessa forma, ele serve para importar os ptres desde a ação do exercício e momento que quisermos:

A chamada ficou assim: /seguranca/scripts_exec/spo_atualizarFuncionais.php?exercicio=2019&momento=2000, sendo que se não passar nenhum parâmetro, ele continua com a funcionalidade padrão (exercício atual, momento 9000).

**Comment by Rafaeljcg20** [comment]
@orionteles, o ideal é que fosse desenvolvida uma tela no sistema com o botão de gerar os dados do ano seguinte com um formulário onde o usuário pudesse entrar com esses dados citados como  parâmetro e um texto(fieldset) com informações de uso da tela dizendo o impacto das alterações e o que essa funcionalidade iria produzir no sistema para que os usuários autorizados pudessem ter autonomia e também validar. Também ele terá que validar se os dados das tabelas de apoio e vinculações do ano anterior serão copiados para o ano seguinte automaticamente.
