### ISSUE TITLE
[CORREÇÃO] Funcionais sem dados de Objetivos

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#348]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/dfdc6e8e-e3ad-4294-80d2-c209be6d4797)

Fazer análise de porque algumas funcionais como o caso da 42206.2027.20ZI.0785 contém informação de Objetivo(0785) no SIOP, mas não é exibido no SIMINC2.

Verificar e fazer testes no consumo de dados do WS SIOP.
- [x] Analisar se a consulta do sistema não está trazendo informação do campo errado das tabelas de ação e ptres.
- [x] Estudar documentação pra descobrir se o WS retorna esse dado corretamente: https://www1.siop.planejamento.gov.br/siopdoc/doku.php
- [x] Esgotar possibilidades de testes mudando parâmetros do serviço como número do momento e ano do exercício.

**Comment by Rafaeljcg20** [comment]
Branch: hotfix-348-proposta-objetivos
