### ISSUE TITLE
[MELHORIA] Funcionalidade de Importar dados de PI

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#349]
Desenvolver nova funcionalidade de importar dados do Pi do ano anterior para o formulário de Proposta Orçamentária.

Na tela de Cadastro de Pré-PI, desenvolver funcionalidade para que ao usuário clicar no botão Importar de PI[Ano Atual -1] o Sistema abra uma janela modal listando todos os PIs do ano anterior com um link/Icone com a funcionalidade de ao clicar, preencher os dados do Pré-Pi com os dados do PI do ano anterior do módulo Planejamento Orçamentário.

- [x] Janela Modal com Lista de PIs do ano anterior do módulo Planejamento Orçamentário;
- [x] Funcionalidade de preencher os dados do Pré-Pi apartir do item selecionado na lista de PIs do Ano anterior do módulo Planejamento Orçamentário.

**Comment by Darciro** [comment]
Branch: hotfix-349-proposta-importar-dados-pi

**Comment by Rafaeljcg20** [comment]
Oi @macavalheiro , quando puder, dê uma validada pra nós?
