### ISSUE TITLE
[MELHORIA] Valor do Projeto

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#351]
Na tela de Cadastro de Pré-Pi, mudar o formato dos campos Valor do Projeto Custeio, Valor do Projeto Capital, Limite Autorizado na Unidade, Limite Disponível na Unidade, Total Cadastrado na Funcional Custeio, Total Cadastrado na Funcional Capital para valor de moeda nacional sem as casas decimais que representam os centavos.

- [x] Valor do Projeto Custeio
- [x] Valor do Projeto Capital
- [x] Limite Autorizado na Unidade
- [x] Limite Disponível na Unidade
- [x] Total Cadastrado na Funcional Custeio
- [x] Total Cadastrado na Funcional Capital

* Caso a manutenção no componente usado pra colocar mascara no campo seja muito impactante no resto do sistema, inserir uma biblioteca nova ou função pra mudar a mascara para o formato especificado acima.

**Comment by leossb36** [comment]
branch: hotfix-351-Valor-do-projeto

**Comment by rafaeljcg20** [comment]
Observações do @leossb36 sobre itens pendentes pra completar a demanda:
 - [ ] Na tela de proposta alterar em Dados Financeiros os campos de input de Valor, Valor Expansão retirando as casas decimais de centavos e tambem na tabela a mesma coisa, Valor e VI.Expansão

**Comment by dougs007** [comment]
Resolvido @rafaeljcg20, @leossb36 ! Demanda liberada para teste.

**Comment by macavalheiro** [comment]
tirar todos os decimais (de todos os campos numericos)

**Comment by leossb36** [comment]
Segue, abaixo, script para alteração do tipo da coluna informada
alter table proposta.proposta alter column proquantidadeexpansao type integer

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br
