### ISSUE TITLE
[CORREÇÃO] Perfil Unidade

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#352]
- [x] Mudar nome do perfil de Subunidade pra Unidade
* Produzir script de banco pra alterar o nome de Perfil de Subunidade para Unidade
- [x] Implementar regra: O usuário com perfil de Unidade deve ver a Lista de Pré-Pi(/proposta/proposta.php?modulo=principal/preplanointerno&acao=A) ao invés do Painel(proposta/proposta.php?modulo=inicio&acao=C).
* Retorna perfil do usuário logado: 
>> $perfis = pegaPerfilGeral();
>> $podeEditar = !in_array(PFL_SUBUNIDADE, $perfis)? TRUE: FALSE;
- [x] Implementar regra: O usuário com perfil de Unidade só pode visualizar na lista de Pré-Pi os Pré-Pis das subunidades vinculadas ao perfil do usuário logado.
* Retorna perfil do usuário logado: 
>> $perfis = pegaPerfilGeral();
>> $podeEditar = !in_array(PFL_SUBUNIDADE, $perfis)? TRUE: FALSE;
* Retorna lista de Unidades do usúário logado: 
>> $listaSubUnidadeUsuario = buscarSubUnidadeUsuario((object) array('usucpf' => $_SESSION['usucpf']));

**Comment by dougs007** [comment]
Segue script para atualização do nome do perfil :

/*
SELECT * FROM seguranca.perfil WHERE pflcod = 1513;
*/

BEGIN ;
-- ROLLBACK;

UPDATE seguranca.perfil 
SET pfldsc = 'Unidade'
WHERE pflcod = '1513'

COMMIT;

**Comment by dougs007** [comment]
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/0c44639b-af7f-4b2d-8617-1e72b18b5b1f)


Ao testar foi encontrado a seguinte ressalva:
Foi feito o teste com o usuário Alysson da unidade FCR, de cpf  (71225919134) e ao entrar no sistema com este usuário, na listagem de Pré-PI o usuário consegue ver outros Pré-PI's que não estão vinculados a Subunidade dele, como mostrado na foto.

**Comment by dougs007** [comment]
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/b7005512-7f3d-4768-bcc9-605a58c7d6c5)

Foi realizado outro teste e o usuário do teste anterior estava com o cadastro antigo, porém foi encontrado a seguinte divergência, ao cadastrar um Pré-PI, ele não está sendo listado para unidade.

**Comment by dougs007** [comment]
Prezados, foi realizado outro teste e concluiu-se que, nos testes em que relatamos ressalvas, os mesmos foram realizados simulando usuário. Uma particularidade da funcionalidade dos sistema é que no modo de simulação de usuário, ele não altera, nem exclui e nem salva nenhum tipo de dados.

**Comment by macavalheiro** [comment]
O perfil unidade deve visualizar suas propostas tb.

**Comment by Rafaeljcg20** [comment]
Corrigido.
@macavalheiro
