### ISSUE TITLE
[CORREÇÃO] Unidade(Unidade de Medida) e Produto

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#353]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/90f90e67-d549-4dc4-86a2-10014b1a351b)

Na tela Cadastro de Proposta pra algumas funcionais o sistema não está exibindo o valor de Unidade(Unidade de Medida) do localizador e do PO.

A demanda consiste em fazer uma verificação nos dados do BD do SIMINC2 e nas informações de retorno da API do SIOP, para descobrirmos porque esse valor não existe pra todas as funcionais do módulo Proposta Orçamentária e "se possível" corrigir.
Obs:
- [x] Fazer testes mudando os parâmetros enviados pra consulta no WS do SIOP como momento(1000,2000,3000) e ano para verificar o resultado.
- [x] Estudar documentação do WS do SIOP pra verificar se o sistema realmente oferece esses dados(https://www1.siop.planejamento.gov.br/siopdoc/doku.php).

**Comment by Rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/56c04300-992d-41fa-8971-8954f4b15d59)

**Comment by Rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/ef8bc42e-c0fc-4020-b2a3-5e56cef6cc59)

**Comment by Rafaeljcg20** [comment]
mesmo quando traz produto não está trazendo a unidade

**Comment by Rafaeljcg20** [comment]
Descobrimos que ao fazer migração dos dados que recebemos do SIOP existe um erro que faz com que a informação de Unidade não seja exibida corretamente dentro do sistema SIMINC2, mas ainda não foi possível fazer a correção no sistema de forma definitiva.

**Comment by Darciro** [comment]
Preciso das credenciais de acesso ao sistema do Siop para realizar a carga (importação) dos dados afim de testar a funcionalidade à ser implementada. URL de importação: http://siminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=sistema/comunica/importaQualitativo&acao=A

**Comment by rafaelfcar** [comment]
branch: hotfix-353-proposta-correcao-importacao

**Comment by dougs007** [comment]
Testado em homologação : http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/proposta_form&acao=A&proid=6

**Comment by rafaeljcg20** [comment]
- [ ] Falta a execução do SCRIPT de banco de dados que ocorrerá às 14hrs pelo Sr. Heron
