### ISSUE TITLE
[MELHORIA] Visual do campo Limites Pré-PI

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#354]
Na tela de Cadastro de Proposta, mudar a posição da tabela Limites Pré-PI para ficar abaixo do campo Subunidades Vinculadas à Funcional.

Descrição do P.O pra referência: [tela proposta] Colocar Limites Pré- PI entre Subunidade Vinculadas à Funcional e Quantidades.

**Comment by dougs007** [comment]
Nome da branch: hotfix-354-proposta-layout-pi

**Comment by Darciro** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/proposta_form&acao=A
