### ISSUE TITLE
[CORREÇÃO] Visual dos campos de Expansões

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#355]
Na tela de Cadastro de Proposta, criar uma nova caixa visual/box(fieldeset) com o nome de Expansão com os campos já existentes Quantidade Expansão PO e Justificativa Expansão.

**Comment by dougs007** [comment]
Nome da branch: hotfix-355-proposta-fieldset

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br
