### ISSUE TITLE
[MELHORIA] Validação  de Valores Financeiros

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#356]
Na tela Cadastro de Proposta, inserir validação para o sistema não permitir cadastrar valores financeiros cuja soma dos valores cadastrados sejam superiores aos Limites Pré-PI tanto de Valor(Por Custeio e Por Capital) quanto de Expansão(Por Custeio e por Capital).

- [x] Validação de Valor Custeio
- [x] Validação de Valor Capital
- [x] Validação de Valor Expansão Custeio
- [x] Validação de Valor Expansão Capital

Obs:
    * Cada dado Financeiro salvo é determinado como "custeio" quando a Natureza de Despesa for definida começando com o número 3. Exemplo: Natureza Despesa: 31304100 - Contribuições.
    * Cada dado Financeiro salvo é determinado como "capital" quando a Natureza de Despesa for definida começando com o número 4. Exemplo: Natureza Despesa: 44504200 - Auxílios.
    * Regra: O usuário só poderá inserir um novo dado financeiro de "custeio" se a soma dos dados já cadastrados tanto de valor quanto de expansão não forem superiores ao dado informado na tabela Limites Pré-Pi de de Valor e Expansão de "custeio" respectivamente.
    * Regra: O usuário só poderá inserir um novo dado financeiro de "capital" se a soma dos dados já cadastrados tanto de valor quanto de expansão não forem superiores ao dado informado na tabela Limites Pré-Pi de de Valor e Expansão de "capital" respectivamente.

**Comment by Rafaeljcg20** [comment]
Branch: hotfix-356-proposta-financeiro

**Comment by leossb36** [comment]
Testado em homologação.
