### ISSUE TITLE
[CORREÇÃO] Natureza de Despesa

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#358]
Na tela de Cadastro de Proposta, na lista de dados financeiros, trocar o valor exibido na coluna Nat. Desp. de o número da Chave Primaria da tabela de natureza de despesa(Número interno do banco de dados) para o Código(Ex um número de 8 dígitos: 31900300) da natureza de despesa.

**Comment by dougs007** [comment]
Testado em : http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/proposta_form&acao=A&proid=14
