### ISSUE TITLE
[CORREÇÃO] IDOC

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#359]
Na tela de Cadastro de Proposta, na lista de dados financeiros, trocar o valor exibido na coluna IDOC de o número da Chave Primaria da tabela de IDOC(Número interno do banco de dados) para o Código(Ex um número de 4 dígitos: 2952) do IDOC.

**Comment by dougs007** [comment]
Testado em : http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/proposta_form&acao=A&proid=14
