### ISSUE TITLE
[MELHORIA] Lista de Propostas

### ISSUE THREAD

**Issue by Rafaeljcg20** [culturagovbr/siminc2#361]
Na tela Proposta(Lista de Propostas), criar uma linha ao final da tabela informando o Total de Quantidade PO, Quantidade Expansão, Custo Total, Custo Expansão.

**Comment by dougs007** [comment]
Nome da branch: hotfix-361-proposta-totalizador

**Comment by Rafaeljcg20** [comment]
Testada em: http://homologasiminc2.cultura.gov.br

**Comment by macavalheiro** [comment]
o total não está variando com o filtro.

**Comment by Rafaeljcg20** [comment]
Oi @macavalheiro, é porque esse componente de filtro trabalha com os dados que estão impressos na lista naquele momento e não faz uma nova consulta no banco após o texto filtrado. 
Nesse caso teríamos que abrir uma outra Issue pra fazer os filtros personalizados semelhante a tela de lista do módulo Planejamento e do Emendas.
