### ISSUE TITLE
Emenda FNC - Valor de execução aparece Dobrado no módulo Planejamento Orçamentário.

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#365]
O valor de "empenhado" do ID FNC 10425, oriundo da emenda 201836300008, está aparecendo dobrado no módulo Planejamento Orçamentário.
No módulo Emendas Parlamentares, esse valor aparece.
No SIOP também consta o valor empenhado de R$1.300.000,00.
No módulo Planejamento o valor que aparece em empenhado é de 2.600.000,00.

**Comment by Rafaeljcg20** [comment]
Branch: hotfix-365-planejamento-execucao
