### ISSUE TITLE
[CORREÇÃO] Formulário Reduzido

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#374]
Na tela Cadastro de Pré-PI quando selecionado o enquadramento dos tipos que são reduzidos, não estão sumindo os campos conforme módulo planejamento.

 - [x] Opções de Enquadramentos que tem formulário reduzido:
> Benefícios ao servidor;

> Contribuição patronal;

> Despesas obrigatórias;

> Manutenção;

> Pessoal e encargos.

Campos que devem ser ocultados ao selecionar qualquer uma das opções de enquadramento reduzido:- 
 - [x] Todas as metas;

 - [x]  Área;

 - [x]  Segmento;

 - [x]  Produto deve ser preenchido automaticamente como "não se aplica" e implica em ocultar as opções Unidade de Medida e quantidade.

**Comment by Rafaeljcg20** [comment]
Branch: hotfix-374-proposta-reduzido

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br

**Comment by Rafaeljcg20** [comment]
Olá @macavalheiro, quando puder, tente validar essa demanda também.
