### ISSUE TITLE
[CORREÇÃO] Relatório Geral

### ISSUE THREAD

**Issue by HenriqueOliveiradosAnjos** [culturagovbr/siminc2#381]
Fazer as seguintes correções:
 - [x] Erro 1: PIs com a informação da coluna "Programa" em branco. A consulta deve ser corrigida para que a coluna programa sempre venha preenchida.
 - [x] Erro 2: Alguns PIs da FUNARTE estão repetidos. Eliminar duplicação da consulta.
 - [x] Erro 3: Existem PIs com RP-6 aparecendo no relatório. A consulta deve ser corrigida para não exibir PIs que foram originados do módulo Emendas ou seja, PIs que contenham RP igual a 6.

**Comment by HenriqueOliveiradosAnjos** [comment]
Os PIs repetidos são IDs: 10435, 10436, 10438, 10439, 10441, 10444 e 10498.

**Comment by leossb36** [comment]
branch: hotfix-381-planejamento-relatorio-geral

**Comment by rafaelfcar** [comment]
Testado em ambiente de homologação
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/painel&acao=A

**Comment by rafaeljcg20** [comment]
Problema de programas em branco no relatório geral foi publicado nessa data. Obs: View alterada de banco de dados.
