### ISSUE TITLE
[MELHORIA] Inserir regra pra buscar Metas PPA através de Unidades Delegadas

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#384]
Quando um PI é delegado para outra unidade, que executará o projeto, seria interessante que fossem disponibilizadas também as metas PPA referentes à essa unidade (que executará), pois hoje só aparecem as metas da unidade(principal) que delega.

 - [x] Tela Cadastro de PI
 - [x] Tela Cadastro de PI FNC
 - [x] Tela Cadastro de Beneficiários -> Cadastro Complementar do PI

**Comment by Rafaeljcg20** [comment]
meta pnc a mesma coisa.

no módulo emenda e no modulo planejamento.

**Comment by macavalheiro** [comment]
no módulo emendas no formulário de beneficiário (que pode ser acessado clicando sobre o número na colula "id beneficiário" > botão delegação

e no módulo planejamento > "criar pi" > delegação

**Comment by Darciro** [comment]
Branch:  hotfix-384-emendas-metas-ppa-outras-unidades

**Comment by dougs007** [comment]
Testado em homologação : http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8420

**Comment by macavalheiro** [comment]
no módulo planejamento funcionou certinho.

já no módulo emendas, ao marcar uma unidade delegada, salvar e ir para a aba "cadastro complementar do pi"  não consegui acessar as metas PPA nem pnc da unidade que foi colocada como delegada

**Comment by leossb36** [comment]
Em emendas Parlamentares, no botão de Delegação [BUG]:
Caso Delegação esteja salvo com dados, ao mudar o botão para checked-off e salvar não esta alterando os dados

**Comment by leossb36** [comment]
testada em homologação: 
* Modulo: 
**Planejamento Orçamentario - http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10175
