### ISSUE TITLE
[MELHORIA] Administrar Ações Estratégicas

### ISSUE THREAD

**Issue by Darciro** [culturagovbr/siminc2#385]
Adição de novos campos no formulário de ações estratégicas:
- Orçamento atual;
- Descontigenciamento;
- Recomposição PLOA;
- Crédito.

**Comment by Darciro** [comment]
Branch: hotfix-385-painel-novos-campos-acoes-estrategicas

**Comment by dougs007** [comment]
Testado em homologação : http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=sistema/tabelaapoio/cadastroacoes/formulario_acao&acao=A

**Comment by Darciro** [comment]
Segue script para criação dos novos campos no banco de dados:

ALTER TABLE painel.acao ADD acaorcamentoatual numeric(15,2) NULL;
COMMENT ON COLUMN painel.acao.acaorcamentoatual IS 'Valor do orçamento atual' ;

ALTER TABLE painel.acao ADD acadescontigenciamento numeric(15,2) NULL;
COMMENT ON COLUMN painel.acao.acadescontigenciamento IS 'Valor do Descontigenciamento' ;

ALTER TABLE painel.acao ADD acarecomposicao numeric(15,2) NULL;
COMMENT ON COLUMN painel.acao.acarecomposicao IS 'Valor da Recomposição PLOA' ;

ALTER TABLE painel.acao ADD acacredito numeric(15,2) NULL;
COMMENT ON COLUMN painel.acao.acacredito IS 'Valor do Cédito' ;
