### ISSUE TITLE
[MELHORIA] Criar nova tela Tramitação em Lote FNC

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#389]
Criar nova tela com a funcionalidade de mudar PIs de estado em Lote. Semelhante a tela do menu Principal -> Tramitação em Lote.

**Comment by rafaelfcar** [comment]
branch: hotfix-389-planejamento-tramitacao-lote-fnc

**Comment by dougs007** [comment]
Testado em :  http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/tramitacao-lote-fnc&acao=A
