### ISSUE TITLE
[CORREÇÃO] Perfil Consulta

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#398]
Fazer as seguintes correções:
 - [x] O sistema deve ser corrigido para o usuário com perfil de Consulta poder acessar todas as telas que o perfil Planejamento pode acessar, porém não poderá alterar os dados.
 - [x] O sistema deve ser corrigido para o usuário poder entrar na Lista de PI. Obs: Atualmente não acessava.
 - [x] O sistema deve permitir o usuário entrar na tela de Espelho e na tela de Cadastro de PI, Cadastro de PI FNC, porém sem poder alterar os dados.
 - [x] Deve ser retirado o acesso à tela tela de tramitar em lote.

**Comment by Rafaeljcg20** [comment]
como tem q ficar

conseguir entrar em lista pi (tanto fundo qto normal)

ao entrar em lista pi conseguir entrar em editar e conseguir entrar em espelho (fnc (fundo) e normal)

tela painel, ao clicar em cima da funcional  conseguir entrar em editar e conseguir entrar em espelho


*não deve ver a tela tramitar em lote

**Comment by dougs007** [comment]
Nome da Branch : hotfix-398-planejamento-perfil-consulta

**Comment by rafaelfcar** [comment]
[] Na lista de Pi está permitindo excluir um registro.

**Comment by rafaelfcar** [comment]
Testado em ambiente de homologação.

**Comment by macavalheiro** [comment]
Tanto na lista PI, quanto na tela lista PI FNC não está aparecendo (e dando pra entrar ) o lapisinho.

já no painel está ok, dá para entrar tanto no espelho, quanto no lápis (porém não edita, como tem q ser)

**Comment by dougs007** [comment]
Boa tarde, @macavalheiro. A solicitação em ambas listas foram atendidas em  :   http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapimanter_fnc&acao=A

**Comment by macavalheiro** [comment]
boa!
