### ISSUE TITLE
emendas no painel fundo

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#399]
tela painel fnc - parte acompanhamento geral fnc - por ação está com várias funcionais de emendas que não eram para aparecer (RP 6)

**Comment by macavalheiro** [comment]
módulo planejamento > painel FNC > "Acompanhamento Geral FNC - Por Ação" (quadro de baixo)

**Comment by dougs007** [comment]
Nome da branch : hotfix-399-planejamento-painel
