### ISSUE TITLE
[CORREÇÃO] Emenda gerar PI

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#401]
O PI 18E10516SVF (ID 10516), criado a partir da Emenda 201827760007 (ID Beneficiário 8571), foi duplicado ao ser alterado o seu GND, de custeio para capital. Verificar que erro aconteceu para a ocorrência da duplicação.

Obs 10577 está ativo.

**Comment by rafaelfcar** [comment]
Prezados, foram feitos vários testes no sistema e houve também uma investigação na estrutura do banco de dados para identificar ou simular o problema citado, porém não foi possível encontrar algo o erro que gerasse essa inconsistência.

**Comment by rafaeljcg20** [comment]
Em contato com o Sr. @JoelSSilva ele autorizou fechar essa demanda.
