### ISSUE TITLE
[MELHORIA] Inserir Percentual sob Limite no Painel

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#410]
Na tela Painel de acompanhamento, inserir informação de percentual no tooltip(Texto de ajuda ao mover o mouse por cima) de cada uma das barras do gráfico de valores Planejado, Provisionado, Empenhado, liquidado e pago em relação ao valor de limite.

O texto deve aparecer no seguinte formato: [PERCENTUAL]% do Limite.

Exemplo: 95% do Limite.

 - [x] Aba Gráficos das Unidades
 - [x] Aba Gráficos da Direta
 - [x] Aba Gráficos da CGCON/COGEP

Obs: Rascunho do P.O: Percentual empenhado/limite e planejado/limite

**Comment by leossb36** [comment]
As informações de percentuais estão funcionais.

Entretanto, ao clicar em alguns das barras, de quaisquer gráfico, a modal não está apresentando o conteúdo que desejamos visualizar.

Segue a imagem abaixo:
![Screenshot from 2018-06-14 17-00-53.png](https://images.zenhubusercontent.com/59f463e48a75884b908527c3/a6c338a8-0cc8-49e0-beb6-89fbde11582b)

**Comment by leossb36** [comment]
Testado em homologação: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/painel&acao=A

**Comment by macavalheiro** [comment]
Perfeito. 

Só trocar o texto onde diz "xx,xx% sob o Limite" para "xx.xx do limite"

**Comment by macavalheiro** [comment]
só um pequeno detalhe:

ao passar o mouse em cima da dotação e do limite está escrito "undefined"

**Comment by rafaeljcg20** [comment]
@rafaelfcar, poderia resolver pra gente na segunda-feira?

**Comment by rafaeljcg20** [comment]
Testado novamente em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/painel&acao=A

**Comment by rafaeljcg20** [comment]
Olá @macavalheiro, poderia validar novamente a demanda, fizemos nova correção.
