### ISSUE TITLE
[CORREÇÃO] Relatório por e-mail

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#412]
No módulo Segurança é possível cadastrar rotinas para serem executadas periodicamente através do menu Principal -> Agendamento de SCRIPTS. Existe uma rotina responsável por atualizar as dotações das subunidades buscando os dados do sistema SIOP e ao atualizar os dados é enviado um e-mail com três relatórios aos usuários com perfil de Super Usuário, porém o relatório de <b>Funcionais compartilhadas com valores divergentes</b> está informando dados errados na coluna Unidade.

É necessário corrigir a consulta desse relatório porque as Subunidades listas na coluna Unidade não estão vinculadas a funcional 2027.20ZF.0001.0786.000O, mas estão aparecendo no relatório.

Segue os dados que não deveriam aparecer na Coluna Unidade pra funcional 2027.20ZF.0001.0786.000O:
MINC - ASCOM (R$ 865.000);

MINC - SCDC (R$ 171.429);

MINC - SADI/DEINT (R$ 3.000.000);

MINC - SE (R$ 19.349.362);

MINC - SEFIC (R$ 0);

MINC - SADI (R$ 13.500.000);

MINC - SCDC/DLLLB (R$ 400.000).

Obs: Arquivo que envia o relatório por email: <b>/seguranca/www/scripts_exec/spo_atualizarDotacao.php</b>

**Comment by macavalheiro** [comment]
conforme email enviado ao rafa

**Comment by rafaeljcg20** [comment]
Branch: hotfix-412-planejamento-rel-email
