### ISSUE TITLE
[CORREÇÃO] Restrição de valor Pré-PI conforme o Limite da Subunidade

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#416]
Na tela de Cadastro de Pré-PI, corrigir os valores de Limite Disponível e corrigir restrição para que o usuário não possa cadastrar um Pré-PI com valor que excede o Limite estabelecido para a Subunidade.

Obs: Consequentemente está sendo possível abrir mais projetos que a unidade tem de limite.

**Comment by rafaeljcg20** [comment]
Branch: hotfix-416-proposta-limite-unidade

**Comment by carlosalmeida1958** [comment]
https://docs.google.com/spreadsheets/d/1WmSSaK-B6cctEbUl-Gf4dfIk9rkgerkoFBXAgrq60po/edit?usp=sharing
