### ISSUE TITLE
[MELHORIA] Tela de pesquisa pré-pi adicionar filtros

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#417]
## Inserir opções de filtros na tela de Lista de Pré-PI:
 - [x] Unidade
 - [x] Enquadramento
 - [x] Estado Atual

**Comment by rafaeljcg20** [comment]
- [ ] Corrigir botão de Novo;

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br
