### ISSUE TITLE
[MELHORIA] Tela lista proposta adicionar filtros e trocar nomes colunas

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#418]
## Adicionar filtros:
 - [x] SubUnidade;
 - [x] Funcional;
 - [x] Enquadramento da Despesa.

**Comment by dougs007** [comment]
Nome da Branch : hotfix-418-operacao-filtro-proposta

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br
