### ISSUE TITLE
[MELHORIA] Inserir linha de totais

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#419]
## Trocar nomes colunas:
 - [ ] "Custo Total" por "Valor Total";
 - [ ]  "Custo Expansão" por "Valor Expansão".

Na tela lista pré-pi e tela Lista de Propostas, inserir linha com totais de todos os dados que são numéricos semelhante a tela Lista de PI do módulo Planejamento Orçamentário.

**Comment by leossb36** [comment]
Testado em homologação: http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/preplanointerno&acao=A
