### ISSUE TITLE
[CORREÇÃO] Validação no Cadastro de PI e Cadastro PI do FNC

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#441]
- [x] Na tela de Cadastro de PI, Mudar o preenchimento do campo de código de PI de 15 caracteres para 11.

- [x] Na tela de Cadastro de PI do FNC, Mudar o preenchimento do campo de código de PI de 15 caracteres para 11.

**Comment by dougs007** [comment]
Nome da Branch :   hotfix-441-planejamento-cadastro-pi

**Comment by rafaelfcar** [comment]
Testado em ambiente de homologação
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi_fnc&acao=A&pliid=10411

**Comment by macavalheiro** [comment]
funcionou ao impedir gravação de códigos com mais de 11 dígitos

porém aceitou códigos com menos de 11 dígitos. 

 Ao comentar com a Rafa sobre essa funcionalidade comentei que deveria barrar tanto com mais qto com menos. 

É possível a validação funcionar dessa forma?

**Comment by dougs007** [comment]
Adicionada a funcionalidade @macavalheiro !
