### ISSUE TITLE
[CORREÇÃO] Cadastro de Proposta.

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#444]
- [x] Na tela cadastro de Proposta o Limite pré-pi não está vindo de pré-pi aprovados, conforme em : http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/proposta_form&acao=A&proid=21

**Comment by dougs007** [comment]
Nome da Branch :  hotfix-444-operacao-proposta

**Comment by rafaelfcar** [comment]
Testado em ambiente de homologação
http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/preplanointerno&acao=A
