### ISSUE TITLE
[CORREÇÃO] Listagem de Pré-PI - Filtro de Pré-PI

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#445]
- [x] Pré-PI filtro de enquadramento sem opção de pessoal.

**Comment by rafaelfcar** [comment]
Branch: hotfix-445-proposta-correção-combo-enquadramento-pi

**Comment by dougs007** [comment]
Testado em : http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/proposta&acao=A

Observação : Realizado no filtro de Proposta e Pré-PI !
