### ISSUE TITLE
[MELHORIA] Painel de Acompanhamento - Inserir Filtro por Situação

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#450]
Na tela Painel de Acompanhamento, inserir uma opção de filtro "Situação" com duas opções "Total" com todos os estados/Situação e "Aprovados". Ao aplicar o filtro aprovado o sistema deverá alterar apenas os valores de Pré-PI(Custeio, Capital e Total).

Obs: No gráfico e na tabela abaixo do gráfico.

**Comment by rafaelfcar** [comment]
branch: hotfix-450-proposta-adicionar-filtro

**Comment by dougs007** [comment]
Testado em homologação  :  homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=inicio&acao=C

**Comment by macavalheiro** [comment]
ao filtrar somente os aprovados, está mostrando (tanto o gráfico, como em baixo) só os que tem valor aprovado.  Ocultando tudo que está com valor 0 aprovado.

É possível não ocultar?

**Comment by rafaeljcg20** [comment]
Sim @macavalheiro. Vamos corrigir.

**Comment by rafaeljcg20** [comment]
@leossb36 , a demanda foi corrigida. Poderia testar pra nós?

**Comment by rafaeljcg20** [comment]
Testado em homologação: homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=inicio&acao=C
