### ISSUE TITLE
[CORREÇÃO] Tela Cadastro de Pré-PI - Salvar Pré-PI

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#455]
A Ancine relata que, após salvar um pré-PI, o sistema informa que foi salvo com sucesso, porém não aparece na tela "Pesquisa avançada por PI". Um dos pré-PIs que a Ancine diz ter acontecido isso é na ação 212B, PO 0001.

**Comment by rafaelfcar** [comment]
branch: hotfix-455-proposta-cadastro-prepi

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/preplanointerno_form&acao=A
