### ISSUE TITLE
[MELHORIA] Limite Subunidade por RP

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#460]
- [x] 1) Criar nova TELA "Limite das Subunidades" pra os perfis Super Usuário, Administrador e Planejamento. Para que seja possível informar o Limite das Subunidades para cada RP(Resultado Primário).
Seria como a tela "Limite das Subunidades", porém lá no próprio módulo Proposta;
Ao invés das colunas Custeio Capital , Total e Limite seriam as colunas:  "Total Pré PI" e "Limite RP";
Ao clicar no "+ " ao lado de cada unidade listaria os totais e os limites por RP (contanto o número e o nome do rp).;
Acima (na linha do nome da unidade, exibiria os totais de cada coluna para a unidade);

- [x] 2) Na tela Cadastro de Pré-PI:
- [x] 2.1) Corrigir o sistema para buscar o limite da Subunidade conforme o valor preenchido na tela "Limite das Subunidades/RP" de acordo com o RP da opção de Enquadramento selecionado na tela atual(Cadastro de Pré-PI).
Obs: O formulário passaria a ser limitado pelo "limite do RP" ao invés do limite da unidade.
 - [x] 2.2) Trocar o texto de Limite Autorizado na Unidade para Limite RP da Unidade;
 - [x] 2.3) Trocar o texto de Limite Disponível na Unidade para Limite RP disponível na Unidade.

- [x] 3) Na tela Cadastro de Painel de Acompanhamento:
- [x] 3.1) Corrigir o gráfico para buscar o limite conforme o cadastrado na nova tela Limite das Subunidades.
- [x] 3.2) Corrigir a lista Acompanhamento de Plano Interno para buscar o limite conforme o cadastrado na nova tela Limite das Subunidades.

**Comment by macavalheiro** [comment]
[Uploading... doc05522620180628121930.pdf ]

**Comment by rafaeljcg20** [comment]
BEGIN;

-- corrige sequence de banco
SELECT setval('seguranca.menu_mnuid_seq', (
SELECT
    max(mnuid)
FROM seguranca.menu));

-- Insere menus novos para os módulos mais utilizados
INSERT INTO seguranca.menu(
	mnucod,
	mnucodpai,
	mnudsc,
	mnustatus,
	mnulink,
	mnutipo,
	mnustile,
	mnuhtml,
	mnusnsubmenu,
	mnutransacao,
	mnushow,
	abacod,
	mnuhelp,
	sisid,
	mnuidpai,
	mnuordem,
	mnupaginainicial,
	mnuimagem,
	constantevirtual
)
SELECT
	mnucod,
	mnucodpai,
	mnudsc,
	mnustatus,
	mnulink,
	mnutipo,
	mnustile,
	mnuhtml,
	mnusnsubmenu,
	mnutransacao,
	mnushow,
	abacod,
	mnuhelp,
	sis.sisid,
	mnuidpai,
	mnuordem,
	mnupaginainicial,
	mnuimagem,
	constantevirtual
FROM seguranca.menu m
	LEFT JOIN seguranca.sistema sis ON(
		sis.sisstatus = 'A'
		AND sis.sisid NOT IN(4, 10, 48, 132, 157, 216)
	)
WHERE
	m.mnudsc ILIKE '%Configuração%'
	AND m.sisid = 157
;


/**

SELECT
	*
FROM seguranca.menu m
WHERE
	m.mnudsc ILIKE '%Configuração%'
	AND m.sisid = 157
;

SELECT
	*
FROM seguranca.sistema
WHERE
	sisstatus = 'A'
	AND sisid = 10
;

*/

-- COMMIT; ROLLBACK;

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=inicio&acao=C

**Comment by rafaeljcg20** [comment]
Olá @macavalheiro, poderia verificar pra nós?
