### ISSUE TITLE
[CORREÇÃO] Tela de Limites das Subunidades

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#466]
Na tela de Limites das Subunidades, ao clicar sobre a Unidade "FNC - FUNDO NACIONAL DE CULTURA (42902)" o sistema está exibindo funcionais de emenda(RP6). 
 - [x] Corrigir o sistema pra não exibir funcionais de emendas(RP6).

**Comment by dougs007** [comment]
Nome da branch : hotfix-466-planejamento-limites-subunidades

- [ ] Executar Script em produção

**Comment by rafaelfcar** [comment]
Testado em ambiente de homologação
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/unidadegestora-limite&acao=A
