### ISSUE TITLE
Relatório Geral - Painel e Painel FNC

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#471]
Ao pedir o Relatório Geral, tanto no Painel quanto no Painel FNC, abre uma janela com apenas uma opção "salvar como". Seria mais interessante a janela disponibilizar as opções "salvar como" e "abrir".

**Comment by rafaeljcg20** [comment]
ajudar o joel com o mozila para dar a opção de salvar ou abrir os relatórios.

**Comment by JoelSSilva** [comment]
O problema parecia resolvido, depois de acessar as configurações de download dos dois navegadores. A solução parecia ser usar apenas no Firefox, que dá a opção de abrir o arquivo.
Porém, verifiquei que no Firefox também é necessário salvar o arquivo, caso eu queira editá-lo.
Em resumo: o Chrome não deixa abrir, apenas salvar. O Firefox dá a opção de abrir, porém não deixa editar, a não ser que salve.

OBS: No módulo Proposta Orçamentária -> Painel Siop -> Gerar Planilha, o arquivo abre e permite editar.
Antes, em qualquer módulo do Sistema funcionava desta forma, com a possibilidade de abrir e editar o arquivo aberto sem a necessidade de salvá-lo. Agora, aparentemente apenas esse botão Gerar Planilha está procedendo dessa maneira.
