### ISSUE TITLE
[CORREÇÃO]Listar PI - Perfis Consulta e Consulta Unidade

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#472]
Nos perfis "Consulta" e "Consulta Unidade" não é possível visualizar a Lista de PIs. Apenas a Lista de PIs FNC está disponível.

**Comment by dougs007** [comment]
Nome da branch > hotfix-472-planejamento-perfis

**Comment by rafaeljcg20** [comment]
https://docs.google.com/spreadsheets/d/1_4Z90H1diHqpSJPgl-USrNu785VsGiPelEfYXILQObs/edit#gid=333462702

**Comment by dougs007** [comment]
Nome da branch : hotfix-472-planejamento-correcao-perfis

**Comment by rafaeljcg20** [comment]
Desabilitar o botão de salvar da aba monitoramento que se encontra na tela cadastro de PI e cadastro de PI FNC.

**Comment by leossb36** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10057

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapimanter_fnc&acao=A

**Comment by JoelSSilva** [comment]
Tudo certo!
