### ISSUE TITLE
[MELHORIA]Painel FNC-Exportar Planilha

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#474]
Na tela acessada através do menu Principal -> Painel FNC fazer as seguintes mudanças:
- [x] Criar botão "Exportar XLS" alinhado a direita do Título "Acompanhamento Geral FNC - Por Unidade" com a finalidade de exportar planilha no formato XLS:
- [x] Criar botão "Exportar XLS" alinhado a direita do Título "Acompanhamento Geral FNC - Por Ação" com a finalidade de exportar planilha no formato XLS.

<b>Obs: Essas duas planilhas novas devem ser feitas com o PHPExcel.</b>

**Comment by rafaelfcar** [comment]
branch: hotfix-474-planejamento-painel-fnc

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/painel_fnc&acao=A
