### ISSUE TITLE
[MELHORIA]Gerador de relatórios dinâmico

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#480]
Refatorar o componente de geração de relatórios para funcionar com o layout novo dos novos módulos Planejamento Orçamentário, Emendas, Monitoramento.

**Comment by rafaeljcg20** [comment]
Fazer manutenção no gerador de relatórios


Consultas:
Emendas :  Módulo Emendas> Relatórios > Relatório Geral
Pre PI:   Módulo Proposta > Relatórios > Pré Pi
Proposta: Módulo Proposta > Relatórios > Proposta
Funcionais:  Módulo Planejamento > Relatório de Funcionais. 
PI (relatório geral): Módulo Planejamento > Relatório Geral 
PI FNC: Módulo Planejamento > Painel FNC > Rotatório Geral

**Comment by rafaeljcg20** [comment]
A demanda da Issue #520 utiliza o componente que foi criado nessa demanda, portanto como a demanda #520 foi validada pelo demandate então essa demanda também está validada e será fechada.
