### ISSUE TITLE
[MELHORIA] Alterar Código do PI

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#483]
Na tela de Cadastro de PI e Cadastro de PI FNC, permitir inserir código de PI com mais de 11 digitos.

Obs: Permitir até 15 Dígitos que é o máximo permitido pela estrutura da base de dados do SIMINC2 atualmente.

**Comment by leossb36** [comment]
testado em homologão:
PI:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10000

PI FNC:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi_fnc&acao=A&pliid=10411

**Comment by rafaeljcg20** [comment]
branch: hotfix-483-planejamento-codigo-pi-limite

**Comment by macavalheiro** [comment]
rafa, essa alteração era só pra permitir menos de 11 digitos... mais mais de 11 podia continuar limitando....

ficaria assim,,,, o código poderia ter até 11 digitos.
