### ISSUE TITLE
[CORREÇÃO]Cadastrar Unidade/Subunidade-Painel

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#485]
Na tela "Cadastrar Unidade/Subunidade" (2019) foram alterados os nomes/siglas das seguintes unidades:
- Secretaria de Infraestrutura Cultural (SEINFRA) -> Secretaria de Difusão e Infraestrutura Cultural;
- Secretaria de Economia da Cultura (SEC) -> Secretaria da Economia Criativa (SEC);
- Secretaria da Cidadania e da Diversidade Cultural (SCDC) -> Secretaria da Diversidade Cultural (SDC);
- Departamento de Direitos Intelectuais (DDI) -> Secretaria de Direitos Autorais e Propriedade Intelectual (SDAPI);
- Departamento de Promoção Internacional (DEINT) -> Departamento de Assuntos Internacionais (DAI).

![image.png](https://images.zenhubusercontent.com/5aa81f454b5806bc2bcab2bc/bc7a7a95-7e00-456b-b9bb-4e7ee1cbcf54)

Após fazer as alterações em 2019, tudo ok, estas aparecem no painel principal, na lista de PIs, etc:

![image.png](https://images.zenhubusercontent.com/5aa81f454b5806bc2bcab2bc/23a7123e-b7a8-434e-8690-3b0df8d342c9)

Porém, ao que parece, está havendo um atraso na rotina dessa atualização, pois:

Ao mudar o exercício para 2018, o sistema puxa as alterações para esse exercício:

![image.png](https://images.zenhubusercontent.com/5aa81f454b5806bc2bcab2bc/8bfd09b4-2111-4bf7-830b-51cc4213703e)

Ao atualizar a página, as informações 2018 voltam:

![image.png](https://images.zenhubusercontent.com/5aa81f454b5806bc2bcab2bc/19ae4a78-e303-4160-a880-2497768ebe5b)

Ao mudar novamente para 2019, o sistema puxa as informações de 2018:

![image.png](https://images.zenhubusercontent.com/5aa81f454b5806bc2bcab2bc/fd4d1116-f057-484c-9057-0025fa7cfc59)

Ao atualizar a página, as informações de 2019 voltam:

![image.png](https://images.zenhubusercontent.com/5aa81f454b5806bc2bcab2bc/77fc1301-d308-4edd-9247-d2a753a2cae1)

**Comment by rafaelfcar** [comment]
Branch: hotfix-485-planejamento-cadastrar-unidade-subunidade

**Comment by rafaeljcg20** [comment]
Teste: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/painel&acao=A&exercicio=2019
