### ISSUE TITLE
[MELHORIA] Cadastro de Metas/Indicadores PNC

### ISSUE THREAD

**Issue by leossb36** [culturagovbr/siminc2#489]
- [x] Na tela de Cadastro Meta PNC/Indicador PNC, na parte de cadastro de Indicadores PNC, inserir na tabela de listagem uma coluna com o código dos Indicadores PNC.

**Comment by leossb36** [comment]
nome da branch: hotfix-489-planejamento-melhoria-indicadores-pnc

**Comment by dougs007** [comment]
Testado em homologação :  http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/metapnc_form&acao=A&mpnid=966
