### ISSUE TITLE
[MELHORIA]Lista de Alterações e Relatório Geral

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#502]
- [x] Desenvolver a lista de alterações orçamentárias com os botões de alterar e excluir.
- [x] Botão de exportar pra planilha na Lista principal de alterações.

Obs: 
- [x] Inserir coluna suplementar depois da coluna cancelado na lista e no relatório;
- [x] O relatório deverá ter uma coluna pra informar se é interno ou externo.

Segue foto do protótipo do design
![alteracao-lista-pedidos](https://user-images.githubusercontent.com/17576143/47378323-28becc80-d6ce-11e8-9b05-11a50b916aff.png)

**Comment by dougs007** [comment]
Nome da branch :
hotfix-502-alteracoes-lista

**Comment by leossb36** [comment]
testada em homologação: http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=inicio&acao=C
