### ISSUE TITLE
[MELHORIA]Cadastro de pedido de Alteração Orçamentária

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#503]

**Comment by rafaelfcar** [comment]
branch:
hotfix-503-alteracao-cadastro-pedido

**Comment by rafaelfcar** [comment]
﻿-- DROP SEQUENCE alteracao.pedido_ped_seq;
CREATE SEQUENCE alteracao.pedido_ped_seq
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER TABLE alteracao.pedido_ped_seq
OWNER TO postgres;
GRANT ALL ON SEQUENCE alteracao.pedido_ped_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE alteracao.pedido_ped_seq TO usr_simec;

-- DROP TABLE alteracao.janela;
CREATE TABLE alteracao.pedido
(
pedid integer NOT NULL DEFAULT nextval('alteracao.pedido_ped_seq'::regclass), -- Chave Primária
pedtitulo character varying(255) NOT NULL, -- Descrição
docid integer ,
suoid integer NOT NULL,
tpaid integer NOT NULL,
janid integer NOT NULL,
pedstatus character(1) NOT NULL DEFAULT 'A'::bpchar, -- Status:...
pedano character(4) NOT NULL, -- Ano

CONSTRAINT pk_pedido_pedid PRIMARY KEY (pedid),

CONSTRAINT fk_documento_docid FOREIGN KEY (docid)
      REFERENCES workflow.documento (docid) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE RESTRICT,

CONSTRAINT fk_subunidadeorcamentaria_suoid FOREIGN KEY (suoid)
      REFERENCES public.subunidadeorcamentaria (suoid) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE RESTRICT,

CONSTRAINT fk_tipo_credito_tpaid FOREIGN KEY (tpaid)
      REFERENCES alteracao.tipo (tpaid) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE RESTRICT,

CONSTRAINT fk_janela_janid FOREIGN KEY (janid)
	REFERENCES alteracao.janela (janid) MATCH SIMPLE
	ON UPDATE RESTRICT ON DELETE RESTRICT,
)
WITH (
OIDS=FALSE
);
ALTER TABLE alteracao.pedido
OWNER TO postgres;
GRANT ALL ON TABLE alteracao.pedido TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE alteracao.pedido TO usr_simec;
COMMENT ON TABLE alteracao.pedido IS 'Tipo de Alteração Orçamentária';
COMMENT ON COLUMN alteracao.pedido.pedid IS 'Chave Primária';
COMMENT ON COLUMN alteracao.pedido.pedtitulo IS 'Título do pedido';
COMMENT ON COLUMN alteracao.pedido.docid IS 'Foreign da tabela workflow.documento';
COMMENT ON COLUMN alteracao.pedido.suoid IS 'Foreign da tabela public.subunidadeorcamentaria';
COMMENT ON COLUMN alteracao.pedido.tpaid IS 'Foreign da tabela alteracao.tipo';
COMMENT ON COLUMN alteracao.pedido.janid IS 'Foreign da tabela alteracao.janela';
COMMENT ON COLUMN alteracao.pedido.pedstatus IS 'A - Ativo I - Inativo';
COMMENT ON COLUMN alteracao.pedido.pedano IS 'Exercício da janela cadastrada';

**Comment by dougs007** [comment]
- [ ] Bugs apresentados na hora do teste.
Ao entrar na página de cadastro e tentar avançar para o próximo passo sem ter preenchido o formulário, o sistema deveria não permitir avançar (Atualmente está quebrando).

**Comment by dougs007** [comment]
Testado em homologação :

http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=principal/cadastro_alteracoes&acao=C&tpdid=269
