### ISSUE TITLE
[MELHORIA]Cadastro do vínculo dos Planos Internos ao Pedido

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#504]
Obs:
 - [x]  Inserir o botão de excluir PI.
 - [x]  O sistema não pode permitir cancelar valor maior que do PI
 - [x] O sistema não deve permitir abrir nova alteração de crédito para PIs que estão em processo de alteração cadastrado em andamento.
 - [x] O sistema deve notificar toda vez que o cancelado for maior que o suplementado e vice e versa de todos os PIs envolvidos mas, o sistema deve permitir continuar salvando.
 - [x] Alterar a coluna de Dotação provavel pra resultado provavel.
 - [x] Inserir na coluna de título as informações Produto, Unidade(quebrando linha).
 - [x] inserir linha na coluna tipo com a informação físico.
 - [x] inserir linha com campo de entrada de texto pra fisico cancelado e suplementado.
 - [x] na coluna de Resultado Provavel inserir o resultado do que está sendo adicionado ou cancelado do físico.

![alteracao-cadastro-pi](https://user-images.githubusercontent.com/17576143/47378532-c4e8d380-d6ce-11e8-9b6f-16293e073a30.png)

![alteracao-cadastro-pedido-selecionar](https://user-images.githubusercontent.com/17576143/47378622-0f6a5000-d6cf-11e8-9b80-9e145e9a774a.png)

**Comment by rafaelfcar** [comment]
script:

-- DROP SEQUENCE alteracao.plano_interno_selecionado_seq;
CREATE SEQUENCE alteracao.plano_interno_selecionado_seq
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER TABLE alteracao.plano_interno_selecionado_seq
OWNER TO postgres;
GRANT ALL ON SEQUENCE alteracao.plano_interno_selecionado_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE alteracao.plano_interno_selecionado_seq TO usr_simec;

-- DROP TABLE alteracao.plano_interno_selecionado;
CREATE TABLE alteracao.plano_interno_selecionado
(
pliselid integer NOT NULL DEFAULT nextval('alteracao.plano_interno_selecionado_seq'::regclass), -- Chave Primária
pliid integer NOT NULL,
vlsaldoempenhocusteio numeric(15,2),
vlsaldoempenhocapital numeric(15,2),
vlsuplementarcusteio numeric(15,2),
vlsuplementarcapital numeric(15,2),
vlcancelarcusteio numeric(15,2),
vlcancelarcapital numeric(15,2),
vlsuplementarexcessocusteio numeric(15,2),
vlsuplementarexcessocapital numeric(15,2),
vlsuplementarsuperavitcusteio numeric(15,2),
vlsuplementarsuperavitcapital numeric(15,2),
vldotacaocusteio numeric(15,2),
vldotacaocapital numeric(15,2),

CONSTRAINT pk_plano_interno_selecionado PRIMARY KEY (pliselid),

CONSTRAINT fk_plano_interno_selecionado FOREIGN KEY (pliid) REFERENCES monitora.pi_planointerno (pliid) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT

)
WITH (
OIDS=FALSE
);
ALTER TABLE alteracao.plano_interno_selecionado
OWNER TO postgres;
GRANT ALL ON TABLE alteracao.plano_interno_selecionado TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE alteracao.plano_interno_selecionado TO usr_simec;

**Comment by leossb36** [comment]
os campos não estão obedecendo as regras seguintes:

- [ ] O sistema não pode permitir cancelar valor maior que do PI
- [ ] O sistema não deve permitir abrir nova alteração de crédito para PIs que estão em processo de alteração cadastrado em andamento.
- [ ] ajustar mensagem de aviso de permissividade ![Captura de tela de 2018-11-27 14-53-20.png](https://images.zenhubusercontent.com/59f463e48a75884b908527c3/7e3764d7-4431-4700-9034-a3027cb654bc)

**Comment by leossb36** [comment]
testado em homologação: http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=principal/cadastro_alteracoes&acao=C&pedid=28&tpdid=269#

**Comment by rafaeljcg20** [comment]
Na tela de selecionar pi fazer validação para que nao avance para remanejamento LOA sem selecionar nenhum pi, pois como o campo de funcional é obrigatório é necessario que um pi seja selecionado para então continuar.

Teste e relato feito pelo @leossb36

**Comment by rafaeljcg20** [comment]
Boa tarde @leossb36 , obrigado por fazer o teste de forma bem detalhista! 

Porém em conversa com o Rafael Carneiro concluímos que conforme o pedido do demandante de não haver restrições para acessar todas as abas do sistema o fato de não ter PI não irá gerar um erro apenas será um impedimento pra o usuário cadastrar o detalhamento da aba LOA. Portanto concluímos que não haverá restrição entra a aba de PI para a de LOA.
