### ISSUE TITLE
[MELHORIA]Cadastro de PI-Aviso Cronograma

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#505]
Na tela de Cadastro de PI e Cadastro de PI FNC, o sistema deverá exibir um aviso na parte superior da tela informando que o PI está envolvido em um pedido de alteração orçamentária e que os valores de custeio e capital foram alterados e por isso é necessário ajustar os dados dos cronogramas.

RN - O sistema só deverá exibir o aviso quando o PI estiver envolvido em um pedido de alteração orçamentária que está na situação de Efetivado.

**Comment by rafaeljcg20** [comment]
Usar o componente: 
http://webapplayers.com/inspinia_admin-v2.8/notifications.html

**Comment by leossb36** [comment]
branch: feature-alteracoes

**Comment by rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/0d82ab2e-7d5f-446e-b567-8e4846d89db7)

**Comment by rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/6f9c97a2-230b-4e71-b060-d33555ba3fee)

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10002
