### ISSUE TITLE
[MELHORIA]Cadastros das Justificativas das Alterações Orçamentárias

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#507]
Link do protótipo desta aba : https://www.figma.com/proto/c95PwyivUjXdpNRzJqmRDr2r/siminc2?node-id=20%3A9096&scaling=scale-down-width&redirected=1

Obs
- [x] Adicionar o item 1 da seguinte forma.
1. Necessidade de Alteração. tooltip => Indicar a necessidade da alteração orçamentária, informando a destinação da proposição.

- [x] Adicionar o item 2 da seguinte forma.
2. Causa da Demanda. tolltip => Indicar a causa para a demanda, o que provocou a necessidade do ajuste e dos novos recursos e explicitar, caso haja, a alteração nas metas de atendimento da política pública envolvida

- [x] Adicionar o item 3 da seguinte forma.
3. Formas de Financiamento do Crédito e a Adequação da proposta à meta fiscal e ao limite de gastos tooltip => Indicar as compensações orçamentárias oferecidas e/ou a utilização de excesso de arrecadação ou superávit financeiro, além de verificar a adequação das alterações à meta fiscal do exercício e ao limite de gastos definido pela EC 95/2016, e que os cancelamentos oferecidos não trazem prejuízo à execução das programações canceladas.

- [x] Adicionar o item 4 da seguitne forma.
4. Verificação das fontes, dos Identificadores de uso - Iduso e dos identificadores de Resultado Primário - RP   tooltip => Verificar o balanceamento dessas classificações orçamentárias, justificando, caso estejam desbalanceadas.

- [x] Adicionar o item 5 da seguitne forma.
5. Medida Provisória   tooltip => Indicar a urgência, a relevância e a imprevisibilidade da proposição.

- [x] Adicionar o item 6 da seguitne forma.
6. Legislação Específica    tooltip => Informar, quando for o caso, a legislação 'específica' da qual decorre ou se baseia a alteração orçamentária solicitada.

- [x] Adicionar o item 7 da seguitne forma.
7. Outras Informações   tooltip => Além de outras informações que forem julgadas como necessárias, registrar que não há óbices no prosseguimento da proposta/solicitação.

**Comment by dougs007** [comment]
-- DROP SEQUENCE alteracao.justificativa_seq;
CREATE SEQUENCE alteracao.justificativa_seq
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER TABLE alteracao.justificativa_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE alteracao.justificativa_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE alteracao.justificativa_seq TO usr_simec;

﻿-- DROP TABLE alteracao.justificativa
CREATE TABLE alteracao.justificativa
(
  jstid integer NOT NULL DEFAULT nextval('alteracao.justificativa_seq'::regclass), -- Chave Primária
  pedid integer NOT NULL,
  jstnecessidade character varying(5000) NOT NULL,
  jstcausa character varying(5000)  NOT NULL,
  jstfinanciamento character varying(5000),
  jstfontes character varying(5000),
  jstmedida character varying(5000),
  jstlegislacao character varying(5000),
  jstoutros character varying(5000),
  CONSTRAINT pk_alteracao_justificativa_jstid PRIMARY KEY (jstid),
  CONSTRAINT fk_alteracao_pedid FOREIGN KEY (pedid)
      REFERENCES alteracao.pedido (pedid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE alteracao.justificativa
  OWNER TO postgres;
GRANT ALL ON TABLE alteracao.justificativa TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE alteracao.justificativa TO usr_simec;
COMMENT ON TABLE alteracao.justificativa IS 'Justificativa do Pedido de Alteração';
COMMENT ON COLUMN alteracao.justificativa.jstid IS 'Chave Primária';
COMMENT ON COLUMN alteracao.justificativa.jstnecessidade IS 'Necessidade de alteração';
COMMENT ON COLUMN alteracao.justificativa.jstcausa IS 'Causa da demanda';
COMMENT ON COLUMN alteracao.justificativa.jstfinanciamento IS 'Forma de financiamento de Crédito';
COMMENT ON COLUMN alteracao.justificativa.jstfontes IS 'Verificação das fontes Iduso e RP';
COMMENT ON COLUMN alteracao.justificativa.jstmedida IS 'Medida Provisória';
COMMENT ON COLUMN alteracao.justificativa.jstlegislacao IS 'Legislação Específica';
COMMENT ON COLUMN alteracao.justificativa.jstoutros IS 'Outras Informações';

**Comment by leossb36** [comment]
testado em homologação: 
http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=principal/cadastro_alteracoes&acao=C&pedid=3&tpdid=269
