### ISSUE TITLE
[MELHORIA]Criação dos perfis

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#508]
- [x] Criar estrutura básica de arquivos e esquemas de tabelas do sistema;
- [x] Criar Perfis Administrador e Unidade nos moldes do módulo Proposta Orçamentária.

**Comment by rafaeljcg20** [comment]
Branch: hotfix-508-alteracoes-perfis

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=sistema/usuario/consusuario&acao=A
