### ISSUE TITLE
[MELHORIA]Atualizar Execução Orçamentária

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#510]
- [x] Na tela acessada através do menu Principal -> Painel, criar um novo Botão "Atualizar" ao lado esquerdo do botão "Painel FNC" com a finalidade de buscar os dados de execução orçamentária do sistema SIOP através do webservice.
- [x] Na tela acessada através do menu Principal -> Painel FNC, criar um novo Botão "Atualizar" ao lado esquerdo do botão "Painel" com a finalidade de buscar os dados de execução orçamentária do sistema SIOP através do webservice.
- [ ] Fazer manutenção no arquivo de atualização diária para só efetivar(commit) as atualizações dos dados de execução orçamentária na base de dados quando as funcionais não vinherem com valor 0.
- [ ] Fazer manutenção na funcionalidade acionada através do botão "Atualizar" para só efetivar(commit) as atualizações dos dados de execução orçamentária na base de dados quando as funcionais não vinherem com valor 0.
Obs: Todas as funcionais da ação 2000.

<b>Regra: Apenas o perfil Super Usuário e Administrador podem ver o botão "Atualizar".</b>
<b>Regra: Ao executar a funcionalidade de buscar os dados de execução orçamentária o sistema deverá enviar o e-mail de atualização de dotação no final do processo.</b>

**Comment by rafaelfcar** [comment]
Prezados,

Quando for publicar esta demanda, favor remover da cron do servidor a rotina que executa os arquivos spo_atualizarExecucaoOrcamentaria.php e spo_atualizarDotacao.php.

**Comment by FernandaLA** [comment]
No Painel FNC não é exibido o botão.

**Comment by rafaelfcar** [comment]
O botão foi adicionado no Painel FNC

**Comment by dougs007** [comment]
Testado em homologação : 
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/painel_fnc&acao=A
