### ISSUE TITLE
[CORREÇÃO]Painel de Acompanhamento-Acompanhamento de Plano Interno

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#512]
Corrigir duplicação de funcional.

![SIMINC2-ERRO-Proprosta-painel.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/a251dea2-d24b-47d5-8962-7df7e1f9770d)

**Comment by rafaelfcar** [comment]
branch: hotfix-512-proposta-painel-acompanhamento
