### ISSUE TITLE
[MELHORIA] Tela de administrar "IDUSO"

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#515]
- [ ] Criar uma tela de cadastro para o "IDUSO", a tela deve ficar no menu de Apoio.

**Comment by leossb36** [comment]
Nome da branch: hotfix-515-proposta-iduso
OBS:
- [ ] Criar e habilitar menu em produção

**Comment by dougs007** [comment]
Testado em homologação  :  http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=apoio/iduso&acao=A
