### ISSUE TITLE
[MELHORIA] Tela de administrar "FONTE"

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#516]
- [x] Criar uma tela de cadastro para o "FONTE", a tela deve ficar no menu de Apoio.

**Comment by dougs007** [comment]
Nome da Branch: hotfix-516-proposta-fonte

OBS : 
- [ ] Habilitar menu em produção.

**Comment by FernandaLA** [comment]
Teste em homologação

http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=apoio/fonte&acao=A

http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/proposta_form&acao=A&proid=42

Ao excluir uma fonte, se ja foi atribuida a uma proposta ela, essa proposta mantém como se esse fonte ainda existisse, só substitui ao editar.

Substituir o nome do campo 'Fonte' por 'Fonte recurso' no cadastro de proposta.

**Comment by dougs007** [comment]
Oi, @FernandaLA , poderia testar para nós novamente, por favor ?
