### ISSUE TITLE
[MELHORIA] Tela de administrar "IDOC"

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#517]
- [ ] Criar uma tela de cadastro para o "IDOC", a tela deve ficar no menu de Apoio.

**Comment by isaiassm** [comment]
Nome da Branch : hotfix-517-proposta-idoc

**Comment by dougs007** [comment]
Testado em homologação : http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=apoio/idoc&acao=A

**Comment by leossb36** [comment]
testada em homologação:

http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=apoio/idoc_form&acao=A&idoid=1551
