### ISSUE TITLE
[MELHORIA]Gerador de relatórios-Relatório de Beneficiários/Emenda

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#518]
Criar uma nova tela "Relatório de Beneficiários/Emenda" com o componente de geração de relatórios a partir da consulta acessada a partir do Módulo Emendas no menu Relatórios -> Relatório Geral

Filtros que o demandante solicitou pra esse relatório:
- [x] Subunidade(Formato: {Nome}({SIGLA}))
- [x] Subunidade Delegada(Formato: {Nome}({SIGLA}))
- [x] Situação SICONV
- [x] Situação
- [x] Autor
- [x] UF Parlamentar(Formato: {Nome}-{SIGLA})
- [x] Partido(Formato: {Nome}({SIGLA}))
- [x] Modalidade de Pactuação
- [x] TED
- [x] Área Cultural
- [x] Alterações
- [x] Parecer Técnico
- [x] Parecer Jurídico
- [x] Impedimento

**Comment by rafaelfcar** [comment]
branch: hotfix-518-monitoramento-relatorio-emendas

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A
