### ISSUE TITLE
[MELHORIA]Gerador de relatórios-Relatório Pré-PI

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#519]
Criar uma nova tela "Relatório Pré-PI" com o componente de geração de relatórios a partir da consulta acessada a partir do Módulo Proposta Orçamentária no menu Relatórios -> Pré Pi.

Filtros que o demandante solicitou pra esse relatório:

- [x] Subunidade(Formato: ( Código - Nome  ))
- [x] Enquadramento
- [x] RP(Formato: (Código - Nome))
- [x] Situação

**Comment by dougs007** [comment]
Nome da branch :  hotfix-519-monitoramento-relatorio-pre-pi

**Comment by leossb36** [comment]
testado em homologação: http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A

**Comment by macavalheiro** [comment]
qdo fui testar deu o seguinte erro:

Exercício: 
Colunas
Fatal error: Call to undefined function montarColunasRelatorioPrePI() in /var/www/html/siminc2/acompanhamento/modulos/relatorio/pre-pi/relatorio_form.inc on line 26

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro , fizemos a correção. Poderia tentar validar novamente.
