### ISSUE TITLE
[MELHORIA]Gerador de relatórios-Relatório de Proposta

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#520]
Criar uma nova tela "Relatório de Proposta" com o componente de geração de relatórios a partir da consulta acessada a partir do Módulo Proposta Orçamentária no menu Relatórios > Proposta.

**Comment by dougs007** [comment]
Nome da branch  :   hotfix-520-proposta-relatorio

**Comment by glhr-alcantara** [comment]
Testado em homologação:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A

**Comment by rafaeljcg20** [comment]
Filtros que o demandante solicitou no relatório:

Subunidade

Enquadramento

RP

Tipo de Detalhamento (ainda não existe no relatório, mas é legar colocar)
