### ISSUE TITLE
[MELHORIA]Gerador de relatórios-Relatório de Funcionais

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#521]
Criar uma nova tela "Relatório de Funcionais" com o componente de geração de relatórios a partir da consulta acessada a partir do Módulo Planejamento Orçamentário no menu Relatórios > Funcionais

Filtros que o demandante solicitou:
- [x] Unidade(Formato: {Nome}({SIGLA}))
- [x] Subunidade(Formato: {Nome}({SIGLA}))
- [x] Ação(Formato: {Codigo} {Nome})
- [x] Código da funcional até o nível de PO(Formato: {Codigo_programa}.{Codigo_ação}.{Codigo_localizador}.{Codigo_objetivo}.{Codigo_po}-{Descrição da ação})
- [x] RP(Formato: {Codigo} {Nome})

**Comment by leossb36** [comment]
nome da branch: hotfix-521-monitoramento-gerador-de-relatorio-funcionais

**Comment by rafaeljcg20** [comment]
Falta fazer as combos encadeadas de Unidade, com Subunidade, com Ação e com Funcionais.

**Comment by leossb36** [comment]
testado em homologação: http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A

**Comment by macavalheiro** [comment]
qdo fui testar em homologa deu o seguinte erro:

Colunas
Fatal error: Call to undefined function montarColunasRelatorioFuncional() in /var/www/html/siminc2/acompanhamento/modulos/relatorio/funcional/relatorio_form.inc on line 24

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro , fizemos a correção. Poderia tentar validar novamente.
