### ISSUE TITLE
[MELHORIA]Gerador de relatórios-Relatório PI

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#522]
Criar uma nova tela "Relatório PI" com o componente de geração de relatórios a partir da consulta acessada a partir do Módulo Planejamento Orçamentário no menu Relatórios > Relatório Geral

Filtros que o demandante solicitou pra esse relatório:
- [x] Subunidade(Formato: ( Código - Nome  ))
- [x] Situação
- [x] Enquadramento
- [x] TED
- [x] RP(Formato: ( Código - Nome  ))
- [x] Objetivo(Formato: ( Código - Nome  ))
- [x] Área Cultural
- [x] Modalidade de Pactuação
- [x] Edital
- [x] Classificação

**Comment by dougs007** [comment]
Nome da branch :  hotfix-522-monitoramento-relatorio-pi

**Comment by rafaelfcar** [comment]
Testado em homologação:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A

**Comment by macavalheiro** [comment]
gerar excel não está funcionando

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro , fizemos a correção. Poderia tentar validar novamente.
