### ISSUE TITLE
[MELHORIA]Gerador de relatórios-Relatório PI - FNC

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#523]
Criar uma nova tela "Relatório PI - FNC" com o componente de geração de relatórios a partir da consulta acessada a partir do Módulo Planejamento Orçamentário no menu Principal > Painel FNC -> Botão Relatório Geral.

Filtros que o demandante solicitou:
- [x] Subunidade(Formato: {Nome}({SIGLA}))
- [x] Situação
- [x] Enquadramento
- [x] TED
- [x] RP(Formato: {Codigo} {Nome})
- [x] Ação(Formato: {Codigo} {Nome})
- [x] Objetivo(Formato: {Codigo} {Nome})
- [x] Área Cultural
- [x] Modalidade de Pactuação
- [x] Edital
- [x] Classificação

**Comment by leossb36** [comment]
nome da branch: hotfix-523-monitoramento-gerador-de-relatorio-pi-fnc

**Comment by macavalheiro** [comment]
geral excel não está funcionando

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro , fizemos a correção. Poderia tentar validar novamente.
