### ISSUE TITLE
[CORREÇÃO] Relatório Geral

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#525]
- [ ] Na tela acessada a partir do menu "Principal -> Painel" Corrigir relatório para utilizar o componente PHPExcel a fim de melhorar a visualização e abertura do documento.
- [ ] Na tela acessada a partir do menu "Principal -> Painel FNC" Corrigir relatório para utilizar o componente PHPExcel a fim de melhorar a visualização e abertura do documento.

**Comment by JoelSSilva** [comment]
A geração dos relatórios citados voltou a permitir que se abram os mesmos, sem a obrigatoriedade de ter que salvá-los na máquina, situação que levou à abertura desta demanda. Não há, por essa razão, necessidade de se continuar com a demanda.

**Comment by rafaeljcg20** [comment]
Obrigado Joel( @JoelSSilva ) . Então fecharemos a demanda!
