### ISSUE TITLE
[CORREÇÃO] Cadastro de Beneficiários  - Gerar PI

### ISSUE THREAD

**Issue by leossb36** [culturagovbr/siminc2#533]
- [x] Na tela de Cadastro de Beneficiários quando gerar PI, a tela de workflow que é aberta está apresentando erro para algumas emendas.
* As emendas são:

Autor | UR | Emenda
-- | -- | --
Adelson Barreto | PR | 201830340005
Antonio Carlos Valadares | PSB | 201822460008
Eduardo Amorim | PSDB | 201829080016
João Daniel | PT | 201836910025
Laercio Oliveira | SD | 201826080007
Valadares Filho | PSB | 201824620008
Maria do Carmo Alves | DEM | 201823310002

![image002](https://user-images.githubusercontent.com/26796127/43224166-bbb9955e-902b-11e8-9f30-be54f88b01c5.jpg)

**Comment by leossb36** [comment]
nome da branch: hotfix-533-emendas-gerar-pi

**Comment by glhr-alcantara** [comment]
Testado em homologação:
http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8538&aba=1#

**Comment by rafaeljcg20** [comment]
Parabéns @leossb36 e @glhr-alcantara !!! Muito obrigado!
