### ISSUE TITLE
[MELHORIA] Ícone do histórico de PI

### ISSUE THREAD

**Issue by isaiassm** [culturagovbr/siminc2#535]
- [x] Aumentar o ícone de "Último usuário que alterou" para ficar de acordo com o de "Histórico de Alterações" do PI. 

Caminho: 
Planejamento orçamentário -> Lista pi -> Editar (apenas para exemplo de visualização da demanda)

Segue imagem para identificar o local de alteração:
 ![35492fc1-4b17-48ad-be8c-1507ee3a7c6f.jpeg](https://images.zenhubusercontent.com/5a5769644b5806bc2bc25a50/2f5f2ac6-7618-4c04-9aa6-fc0b3b4b7ca1)

**Comment by dougs007** [comment]
Nome da branch :  hotfix-535-planejamento-icone-pi
