### ISSUE TITLE
ao clicar no espelho do id 10369

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#552]
está mostrando a unidade errada (sem o fnc)

unidade correta é FNC e subunidade é FUNDAÇÃO BIBLIOTECA NACIONAL/FNC

**Comment by dougs007** [comment]
Nome da branch :  hotfix-552-planejamento-espelhopi

**Comment by glhr-alcantara** [comment]
Testado em homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/espelho-pi&acao=A&acao=A&pliid=10369

**Comment by rafaeljcg20** [comment]
O Demandante solicitou pra adicionar o nome da UO e mudar o campo Unidade pra Unidade Delegada.

**Comment by rafaeljcg20** [comment]
Implementação concluída.

**Comment by leossb36** [comment]
testada em homologação: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/espelho-pi&acao=A&acao=A&pliid=10369

**Comment by rafaeljcg20** [comment]
O demandante informou que está correto em homologação. Portanto a demanda será fechada
