### ISSUE TITLE
[CORREÇÃO]Painel FNC-Valor Provisionado

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#553]
não está trazendo o valor provisionado e empenhado tanto para o por unidade quanto por ação

existe pelo menos 250 mil empenhados no pi 10369  da fbn

**Comment by leossb36** [comment]
nome da branch: hotfix-553-planejamento-painel-fnc

**Comment by rafaeljcg20** [comment]
Demanda foi paralisada pra o Leonardo atender a demanda #222 e o Rafael carneiro atender o Gestão Estratégica.

**Comment by rafaeljcg20** [comment]
Demanda voltou a ser atendida.

**Comment by rafaeljcg20** [comment]
Em conversa com o Sr. Marcelo por não existir PI com empenho para ser possível reproduzir esse erro combinamos de fechar a demanda e observarmos se o sistema voltará a apresentar o problema.

Obs: Foi implementado melhoria no layout do painel e refatoração de código.
