### ISSUE TITLE
[CORREÇÃO]Cadastro de Emendas-Delegacao

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#554]
Na tela Cadastro de Emendas, ao informar Unidade(subunidade) Delegada, preencher os dados de beneficiários e tramitar o beneficiário até a geração de PI, os usuários perceberam que o sistema está perdendo a informação de Subunidade delegada.
Obs: Ao concluir o fluxo de reprodução do erro, verificar tanto no módulo planejamento, quanto no módulo Emenda se o cadastro persiste o dado de unidade delegada em ambas as telas dos respectivos módulos.

Obs:
id PI - 10519 foi informado que está com esse problema.

**Comment by dougs007** [comment]
Nome da branch :  hotfix-554-emendas-delegacao

**Comment by glhr-alcantara** [comment]
Testado em Homologação:
http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8855

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10704

**Comment by macavalheiro** [comment]
lindberg
