### ISSUE TITLE
[CORREÇÃO]WEBSERVICE-SIOP-Execução Orçamentária

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#559]
Ao executar a rotina diária de atualização de dados de pagamento da execução orçamentária o sistema não atualiza os valores corretamente, apenas envia o e-mail.

**Comment by rafaeljcg20** [comment]
@dougs007 
seguranca/www/scripts_exec/spo_atualizarExecucaoOrcamentaria.php

**Comment by dougs007** [comment]
Nome da branch:  hotfix-559-planejamento-atualizar-webservice
