### ISSUE TITLE
[CADASTRO] Criar tela para Enquadramento de Despesa

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#56]

**Comment by RamonCanabarro** [comment]
Terminamos a demanda, porém ela não foi revizada e nem testada.

**Comment by macavalheiro** [comment]
a tela está perfeita. mas ao criar novo enquadramento teste e marca-lo como rp "Primária e considerada na apuração do resultado primário para cumprimento da meta, sendo discricionária e não abrangida pelo PAC" (rp 2) não consegui acesso as funcionais de rp 2 (qdo seleciono esse enquadramento teste), que deveria ter na tela de criar pi.

**Comment by g-adler** [comment]
Criar combo que permita várias seleções

**Comment by Rafaeljcg20** [comment]
Testada.

**Comment by macavalheiro** [comment]
Legal! Está ok!

Pelo entendi essa tela substitui a necessidade de ter a tela "vincular enquadramento com RP".
Confere @orionteles ?

Se for isso, favor só ocultar esse menu "vincular enquadramento com RP", para q eu possa fechar a demanda. 

Valeu

**Comment by Rafaeljcg20** [comment]
Oi @macavalheiro , corrigimos essa demanda. Está no ambiente de Teste pra depois publicarmos.

**Comment by Rafaeljcg20** [comment]
Branch: feature-cruds

**Comment by Rafaeljcg20** [comment]
Publicado
