### ISSUE TITLE
Detalhamento Relatórios

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#561]
Caros, conforme tinha ficado de fazer, listei todos os campos (colunas do respectivo relatório) que precisamos como filtros de seleção multipla tb, por relatório.

Percebi que esses relatórios estão sendo salvos todos com o mesmo nome, aí queria aproveitar para pedir que fossem trocados todos, pelo nome em negrito da planilha tb

https://docs.google.com/spreadsheets/d/1_4Z90H1diHqpSJPgl-USrNu785VsGiPelEfYXILQObs/edit#gid=2068854522

aba "Filtros Relatórios"

**Comment by rafaeljcg20** [comment]
Todas as informações desse card de atividade foi repassada pra os cards de individuais de cada relatório solicitado. Portanto essa atividade será fechada pra organizar o quadro de atividades/demandas.
