### ISSUE TITLE
Painel de Acompanhamento-Perfil Subunidade

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#562]
Habilitar para o perfil 'unidade' a tela "Painel de Acompanhamento", visto que contém dados de interesse dos usuários que cadastram as propostas orçamentárias.
Cada usuário precisa ver apenas o que diz respeito à sua unidade (ex: Funarte vê apenas Funarte, Ibram vê apenas Ibram, etc).

**Comment by glhr-alcantara** [comment]
Nome da branch:
hotfix-562-proposta-perfil-subunidade

**Comment by rafaeljcg20** [comment]
Demanda de alta complexidade foi parada pra atender as outras prioridades.

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=inicio&acao=C
