### ISSUE TITLE
Relatório de Pré-PIs/Relatório de Propostas - Proposta Orçamentária

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#563]
Habilitar para o perfil 'unidade' a geração de relatórios de Pré PIs e de Propostas (o usuário só poderá ver o que é de sua unidade - Ex: Funarte verá apenas Funarte, Ibram verá apenas Ibram, etc.

**Comment by glhr-alcantara** [comment]
hotfix-563-proposta-relatorio-prepis-propostas

**Comment by dougs007** [comment]
Testado em homologação :  http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/preplanointerno&acao=A
