### ISSUE TITLE
[MELHORIA]Gestão Estratégica(PDM)-Cadastro de Indicadores

### ISSUE THREAD

**Issue by rafaelfcar** [culturagovbr/siminc2#565]
No módulo Painel usado para a Gestão Estratégica(PDM), estabilizar e fazer ajustes na tela de cadastro de indicadores.

**Comment by rafaelfcar** [comment]
branch: hotfix-565-painel-cadastro-indicadores

insert into pde.monitoratipoindicador (mtidsc, mtistatus, mtinivel)
values ('Quantitativo', 'A', 1);
insert into pde.monitoratipoindicador (mtidsc, mtistatus, mtinivel)
values ('Qualitativo', 'A', 1);

insert into seguranca.perfilmenu (pflcod, pmnstatus, mnuid)
values (271,'A',7297), (271,'A',11010);

insert into seguranca.aba_menu (abacod, mnuid)
values (57105, 7297), (57105, 11010);

insert into seguranca.aba_menu (abacod, mnuid)
values (57279, 4709), (57279, 4708);

**Comment by rafaeljcg20** [comment]
A demanda está publicada mas não foi liberado o acesso para o público e nem para os usuários internos.
