### ISSUE TITLE
[CADASTRO] Criar tela para Objetivo PPA

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#57]

**Comment by RamonCanabarro** [comment]
Terminamos a demanda, porém ela não foi revizada e nem testada.

**Comment by Rafaeljcg20** [comment]
O campo de código deve aceitar no máximo 4 caracteres do tipo inteiro.

[ ERRO ] Ao fazer o teste o sistema permitiu inserir uma letra no campo código.

**Comment by Rafaeljcg20** [comment]
Vamos criar a branch novamente.

**Comment by Rafaeljcg20** [comment]
Branch: hotfix-planejamento-objetivoppa

**Comment by Rafaeljcg20** [comment]
Testado

**Comment by macavalheiro** [comment]
A tela está perfeita, porém no cadastro PI havia uma vinculação de um pra um entre funcional e objetivo. (ao selecionar uma funcional o objetivo era automaticamente selecionado.) Essa vinculação parece ter se perdido.

**Comment by Rafaeljcg20** [comment]
Tarefa: Criar menu e publicar
