### ISSUE TITLE
[MELHORIA] Cadastro de Proposta

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#573]
- [x] Adicionar no cadastro de  Ação, que se localiza no módulo Planejamento Orçamentário, um campo para "Nome do Produto" e "Nome da Unidade".
Obs: Esses campos devem ser carregados através da opção da funcional na tela de cadastro de Proposta.

- [x] Adicionar no cadastro de Funcional, que se localiza no módulo Planejamento Orçamentário, um campo para "Nome do Produto" e "Nome da Unidade".
Obs: Esses campos devem ser carregados através da opção da funcional na tela de cadastro de Proposta.

- [x] Migração de dados enviada por planilha.

**Comment by dougs007** [comment]
Nome da branch  :  hotfix-573-proposta-cadastro-proposta

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=principal/proposta_form&acao=A&proid=71
