### ISSUE TITLE
[CORREÇÃO]Limite Subunidades/RP-Total por Unidade

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#577]
Na tela de limite das Subunidades por RP na unidade ANCINE o sistema está calculando o limite RP em aproximandamente 300 reais a mais do calculo correto.

**Comment by dougs007** [comment]
https://app.zenhub.com/workspace/o/culturagovbr/siminc2/issues/579

A demanda foi atentida no card #579.
