### ISSUE TITLE
[MELHORIA]Tipo Monitoramento-Administrar(Cadastro)

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#584]
Criar nova tela de "Cadastro de Tipo de Monitoramento" Tipo de Monitoramento para listar, inserir, editar e deletar os dados de Tipo de Monitoramento.

Obs: 
Tabela: acompanhamento.tipo;
Não esquecer de criar os menus, inclusive em produção(pedir ajuda do douglas);
Fazer a tela no modelo da tela Cadastro de Autor do módulo Emendas: http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=apoio/autor_form&acao=A&autid=2379

**Comment by isaiassm** [comment]
Nome da Branch: hotfix-584-monitoramento-AdministrarCadastro

**Comment by glhr-alcantara** [comment]
Testado em homologação:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=apoio/tipo&acao=A

**Comment by rafaeljcg20** [comment]
A demanda não nasceu da área meio, porém da necessidade de auxiliar a demanda #222 e portanto será fechada como sendo débito técnico do projeto que será apresentada em reunião no fechamento da sprint dia 03/09/2018.
