### ISSUE TITLE
[MELHORIA]Beneficiário-Histórico de Alterações/Delegação

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#595]
Na tela de cadastro de Beneficiário fazer as seguintes mudanças:
- [x] Implementar a funcionalidade de guardar histórico de alterações de informações da caixa/Seção "Dados Gerais" refentes aos campos Delegação, Subunidade, Proponente, Localização(Sem considerar, uf, municipio e país), Número do Processo, Data de Inicio da Vigência, Modalidade de Pactuação e TED.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/9172aac9-9fda-432e-89c3-e3221c7a7c29)

**Comment by dougs007** [comment]
Nome da branch :  hotfix-595-emendas-historico-beneficiario

**Comment by dougs007** [comment]
Testado em homologação  :  http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8425
