### ISSUE TITLE
[CORREÇÃO]Cadastro de PI-Histórico alterção Código PI

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#598]
No histórico de Código do PI
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/f7d8e6ba-853c-4464-a523-dceab7fa79e1)

E no histórico de Alteração de dados do PI(acessado acima da barra de workflow):
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/6e5e31a5-adc7-41e5-813e-4e404d43d52d)

Na tela de monitorar Projeto(PI) no módulo Monitoramento:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/392460f1-3c7d-42e5-82cf-54753a04716c)

Na tela de Cadastro de PI e na tela de Cadastro de PI FNC, inserir o histórico de pi no padrão.

O sistema deve ficar conforme o exemplo abaixo:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/2bc01b04-34de-482f-8297-d4ed349e46c4)

**Comment by dougs007** [comment]
Nome da branch :  hotfix-598-planejamento-historico-pi

**Comment by glhr-alcantara** [comment]
Ao realizar o teste ocorreu um erro não esperado na tela Monitorar Projeto(PI) módulo Monitoramento.


testado em homologação:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=principal/monitorar-pi&acao=A&pliid=10084&acoid=15

**Comment by glhr-alcantara** [comment]
Testado em homologação: 
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=principal/monitorar-pi&acao=A&pliid=10088
