### ISSUE TITLE
[CADASTRO] Criar tela para cadastro de unidade e subunidade

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#60]

**Comment by RamonCanabarro** [comment]
Terminamos a demanda, porém ela não foi revizada e nem testada.

**Comment by Rafaeljcg20** [comment]
Fazendo testes

**Comment by Rafaeljcg20** [comment]
Correções para a demanda:
* Altear o label da opção de "Código dor Orçmaneto" pra "Código do Orçamento".
* Corrigir o botão salvar.
* Excluir a coluna duplica de código na lista de UO.
* Corrigir o nome do menu de "Unidade orçamentaria" para "Unidade Orçamentária".

**Comment by Rafaeljcg20** [comment]
Tela foi corrigida e testada exaustivamente rs.

**Comment by Rafaeljcg20** [comment]
Publicada.
