### ISSUE TITLE
[CORREÇÃO]Cadastro de PI-Cronogramas

### ISSUE THREAD

**Issue by glhr-alcantara** [culturagovbr/siminc2#604]
Na área de "Cronogramas" quando chamamos a submissão salvar, não está salvando as devidas alterações realizadas quando estamos reduzindo os valores mensais dos cronogramas financeiro e orçamentário.

![erro_pi_cronograma.jpg](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/71322838-1885-4cf1-8651-3a5709d62a68)

**Comment by rafaeljcg20** [comment]
Olá @glhr-alcantara , com ajuda do Sr. Joel identificamos que o problema ocorre quando o usuário coloca o valor "0" nos campos do cronograma Financeiro ou Orçamentário e logo após clica em salvar. 

Obs: <b>Resolveremos isso com calma no dia seguinte</b>, porém com uma solução paliativa o usuário já conseguiu resolver o problema e essa demanda não é mais impeditiva pra o uso do sistema.

**Comment by glhr-alcantara** [comment]
Foi feita algumas alterações que já está de acordo com o cliente. Após realizar vários testes, percebemos que os dados estão salvando corretamente, só foi retirado o alerta que aparecia quando era reduzido o valor do custeio e capital, com isso a segurança não foi afetada e permanece avisando corretamente se está de acordo com as regras!

**Comment by JoelSSilva** [comment]
Tudo certo, salvando sem problemas!
