### ISSUE TITLE
[CORREÇÃO]Cadastro Complementar do PI-Gerar PI

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#606]
![erro_emenda_gerar_pi.jpg](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/dc22d982-c0ac-4787-9130-5ccebcc55529)

Na tela de cadastro de beneficiários, Aba Cadastro Complementar do PI, ao clicar na funcionalidade de gerar PI do beneficiário <b>Id 8528</b> o sistema não gera um novo PI no módulo Planejamento Orçamentário.

Obs: O campo de título e descrição no módulo emendas suporta mais caracteres do que no módulo planejamento.

**Comment by rafaeljcg20** [comment]
Foi enviado um relatório para os demandantes sobre casos parecidos para que os usuários das Unidades possam adequar o cadastro ou para que os demandantes optem por solicitarem uma correção automática da equipe de desenvolvimento.

[https://app.zenhub.com/files/114924704/d90d410e-93ec-4b39-89c9-3f07b7f8a763/download](https://app.zenhub.com/files/114924704/d90d410e-93ec-4b39-89c9-3f07b7f8a763/download)

**Comment by rafaeljcg20** [comment]
Foi realizada uma correção no sistema pra o sistema suportar até 1000 caracteres no campo de descrição e não se fez necessário corrigir os registros passivos do relatório conforme orientação do Demandante.

**Comment by rafaeljcg20** [comment]
Branch: hotfix-606-emendas-gerar-pi-titulo

**Comment by glhr-alcantara** [comment]
Testado em homologação:
http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8528#
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi_fnc&acao=A&pliid=10739
