### ISSUE TITLE
[CORREÇÃO] Suprimir menu de Consultar

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#61]
Relatório do demandante : Suprimir tela usuários> consultar pois tem alguns erros e não é necessária pra gente. tudo que fazemos nessa tela dá pra fazer em "gerenciar'

**Comment by dougs007** [comment]
Observação para publicar : Ocultar/Remover o menu em produção.

**Comment by leossb36** [comment]
Testado em homologação na sideBar: Sistema > Usuários.
