### ISSUE TITLE
[MELHORIA]Legenda do Gráfico-Administrar

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#612]
Criar nova tela ou verificar se é possível utilizar a tela de Estratégias de Meta para inserir, alterar, visualizar e deletar um campo de descrição(Numero+Unidade Medida+Descrição) livre(255 letras) que deverá ser listado na tela de Detalhes do Indicador e Abaixo do Gráfico da tela Metas do Indicador:

Tela Metas do Indicador:
![form_indicadores_4.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/a49f6325-be06-4b9a-9b0b-643832564171)

Tela Detalhes do Indicador:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/bd6bccf4-993e-4b9c-b80e-e517710e1375)

Obs: A imagem acima é meramente ilustrativa e com a finalidade de prototipar a demanda. A disposição dos dados e apresentação da tela deverá ser consultada e analisada pelo webdesigner(Moises @moisesrlima ).

**Comment by rafaelfcar** [comment]
branch: hotfix-612-painel-estrategia-meta


﻿--DROP SEQUENCE emendas.usuario_siconv_ussid;
CREATE SEQUENCE painel.estrategia_meta_indicador_emiid
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE painel.estrategia_meta_indicador_emiid OWNER TO postgres;
GRANT ALL ON SEQUENCE painel.estrategia_meta_indicador_emiid TO postgres;
GRANT SELECT, USAGE ON SEQUENCE painel.estrategia_meta_indicador_emiid TO usr_simec;

--DROP TABLE emendas.usuario_siconv;
CREATE TABLE painel.estrategia_meta_indicador
(
  emiid integer NOT NULL DEFAULT nextval('painel.estrategia_meta_indicador_emiid'::regclass),
  indid integer not NULL,
  emidsc character(255) NOT NULL,
  CONSTRAINT pk_estrategia_meta_indicador PRIMARY KEY (emiid)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE painel.estrategia_meta_indicador OWNER TO postgres;
GRANT ALL ON TABLE painel.estrategia_meta_indicador TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE painel.estrategia_meta_indicador TO usr_simec;

insert into seguranca.menu (mnucod, mnucodpai, mnudsc, mnustatus, mnulink, mnutipo, mnustile, mnuhtml, mnusnsubmenu, mnutransacao, mnushow, abacod, mnuhelp, sisid, mnuidpai, mnuordem, mnupaginainicial)
values (1960,null,'Estratégia de Metas','A','painel.php?modulo=principal/cadastroEstrategiaMetas&acao=A',2,'','',false,'Estratégia de Metas',true,null,null,48,4702,1,'N');

insert into seguranca.aba_menu (abacod, mnuid)
values (57105, 17436);

**Comment by glhr-alcantara** [comment]
Testado em homologação:
http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/metaIndicador&acao=A
http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/detalhamentoInd&acao=A

**Comment by rafaeljcg20** [comment]
Em acordo com o Gabriel representante da SE. Essa demanda pode ser encerrada e publicada.
