### ISSUE TITLE
[CORREÇÃO]Gerenciar Usuário-Envio Email

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#613]
Ao tentar mudar o status do usuário (PAULINO DE OLIVEIRA NETO => 009.878.704-75)

![bug2.jpg](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/e626d7e6-7df6-4b0a-b5df-cc207ee9f0d4)

O sistema apresentou o seguinte erro;

![bug.jpg](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/d48766ea-24ba-4a69-a611-d472919a0d42)

**Comment by dougs007** [comment]
Nome da branch  :  hotfix-613-gerenciar-usuario

**Comment by JoelSSilva** [comment]
O status do usuário foi alterado com sucesso.
