### ISSUE TITLE
Relatório de Funcionais - Colunas trocadas

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#62]
"Relatório de Funcionais": no xls gerado, os títulos das colunas "Planejado Custeio" e "Dotação Capital" estão invertidos. No relatório da tela está certo, mas no xls não.

**Comment by RamonCanabarro** [comment]
A pedido P.O, essa demanda foi despriorizada dessa sprint.

**Comment by Rafaeljcg20** [comment]
Branch: feat-issue-62
