### ISSUE TITLE
[CORREÇÃO]Relatório geral de PI

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#620]
- [ ] Trazer no relatório geral e relatório FNC do Módulo Planejamento, todos os dados do PI de Emendas.

**Comment by rafaeljcg20** [comment]
relatório geral e relatório fnc

**Comment by dougs007** [comment]
Nome da branch :   hotfix-620-planejamento-relatorio-geral

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/painel_fnc&acao=A

**Comment by macavalheiro** [comment]
Rafa, testei e não veio as emendas no relatório geral do fnc nem no geral

no homologa

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro , foi porque a correção estava muito antiga e modernizamos a consulta pra ser utilizada nos novos relatórios, mas agora conseguimos resolver pra todos os casos.
