### ISSUE TITLE
[MELHORIA] Alterar link tela de listagem de indicadores

### ISSUE THREAD

**Issue by rafaelfcar** [culturagovbr/siminc2#625]
Ao clicar no ícone da série histórica na listagem de indicadores, mudar o redirecionamento para as metas.

**Comment by rafaelfcar** [comment]
branch: hotfix-625-painel-listagem-indicador
Observação: Subindo esta branch, subirá também a branch: hotfix-612-painel-estrategia-meta

**Comment by glhr-alcantara** [comment]
Testado em homologação:
http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/metaIndicador&acao=A&indid=3336

**Comment by rafaeljcg20** [comment]
Em acordo com o Gabriel representante da SE. Essa demanda pode ser encerrada e publicada.
