### ISSUE TITLE
[CORREÇÃO]Erro de Layout no meu Relatórios

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#628]
Na tela inicial do módulo Painel, o item de menu Relatórios aparece posicionado de forma errada.
obs: Solicitar ajuda para o Sr. Moises.

![Painel-Erro-layout-relatorio.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/d695c513-b21f-4c7f-9dc6-735fa30c5ed5)

Demandante: Gabriel/Secretaria Executiva

**Comment by leossb36** [comment]
nome da branch: hotfix-628-painel-layout

**Comment by rafaeljcg20** [comment]
Essa demanda foi concluída na branch da demanda #635
