### ISSUE TITLE
[MELHORIA]Listar Indicadores-Ordenar lista de indicadores

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#629]
Na tela Lista de Indicadores, incluir sequencia de ordenação por "Autarquia/Secretaria Executora" considerando a seguinte ordem de acordo com a tabela abaixo informada pelo demandante:
1. Secretaria-Executiva - SE 

2. Departamento de Assuntos Internacionais - DEAIN

3. Assessoria de Comunicação - ASCOM

4. Secretaria da Diversidade Cultural - SDC

5. Secretaria do Audiovisual - SAV

6. Secretaria da Economia Criativa: - SEC

7. Secretaria de Fomento e Incentivo à Cultura: - SEFIC

8. Secretaria de Difusão e Infraestrutura Cultural: Departamento de Desenvolvimento, Análise, Gestão e Monitoramento - SEINFRA

9. Secretaria de Direitos Autorais e Propriedade Intelectual: - SDAPI

10. Instituto do Patrimônio Histórico e Artístico Nacional - Iphan;

11. Agência Nacional do Cinema - Ancine; e

12. Instituto Brasileiro de Museus - Ibram; e

13. Fundação Casa de Rui Barbosa - FCRB;

14. Fundação Cultural Palmares - FCP;

15. Fundação Nacional de Artes - Funarte;

16. Fundação Biblioteca Nacional - FBN.

![lista-indicadores-ordenacao.jpg](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/f4b2349f-1705-4e86-a589-b638c00ac151)

Demandante: Gabriel/Secretaria Executiva

**Comment by dougs007** [comment]
Sugestão antes de criar a branch: Tirar da branch => hotfix-610-painel-homologado . Motivo: Há alterações que não estão em prod, evitando conflito na hora da publicação.

**Comment by rafaelfcar** [comment]
branch: hotfix-629-painel-ordenacao-lista

script
alter table painel.secretaria add column secordem integer;

UPDATE painel.secretaria SET secordem = 1 WHERE secid = 44;
UPDATE painel.secretaria SET secordem = 3 WHERE secid = 65;
UPDATE painel.secretaria SET secordem = 5 WHERE secid = 52;
UPDATE painel.secretaria SET secordem = 7 WHERE secid = 43;
UPDATE painel.secretaria SET secordem = 9 WHERE secid = 42;
UPDATE painel.secretaria SET secordem = 11 WHERE secid = 45;
UPDATE painel.secretaria SET secordem = 13 WHERE secid = 47;
UPDATE painel.secretaria SET secordem = 15 WHERE secid = 46;
UPDATE painel.secretaria SET secordem = 17 WHERE secid = 49;
UPDATE painel.secretaria SET secordem = 19 WHERE secid = 61;
UPDATE painel.secretaria SET secordem = 21 WHERE secid = 56;
UPDATE painel.secretaria SET secordem = 23 WHERE secid = 60;
UPDATE painel.secretaria SET secordem = 25 WHERE secid = 62;
UPDATE painel.secretaria SET secordem = 27 WHERE secid = 63;
UPDATE painel.secretaria SET secordem = 29 WHERE secid = 58;
UPDATE painel.secretaria SET secordem = 31 WHERE secid = 59;

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/lista&acao=A&1=1
