### ISSUE TITLE
[MELHORIA]Cadastro de Indicador-Observação do Gestor

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#630]
Na tela Cadastro de Indicador, inserir os seguintes campos no final do formulário:
- [x] Inserir um ícone de 'Thumbs Up e Thumbs Down' e 'Unlike/Like' Não obrigatório/opcional.
- [x] Inserir o Campo "Resposta do Gestor do Indicador" com até 125 letras e opcional.

RN1: Todos os perfis de usuários podem ver os campos, porém só o perfil "Gestor de Acompanhamento" poderá alterar o campo de Avaliação do Gestor(ThumbsUp/ThumbsDown).
RN2: Todos os perfis de usuários podem ver os campos, porém só o perfil "Gestor do Indicador" poderá alterar o campo de Observação do Gestor.

Demandante: Felipe/Secretaria Executiva

**Comment by rafaelfcar** [comment]
branch: hotfix-630-painel-observacao-gestor

scripts: 
alter table painel.indicador add column indavalgestor char(1);
alter table painel.indicador add column indobsgestor varchar(125);

**Comment by dougs007** [comment]
Testado em homologação :


http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/avaliacaoGestor&acao=A

**Comment by dougs007** [comment]
Testado em homologação: 

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/avaliacaoGestor&acao=A

**Comment by Gabrielran** [comment]
CGINC:

Acrescentar a observação do gestor no relatório gerado em "Relatórios".

**Comment by rafaelfcar** [comment]
Gabriel, boa tarde!

Por questões de controle, podemos criar outra demanda para adicionar este campo no relatório e finalizarmos esta demanda em questão?

**Comment by Gabrielran** [comment]
De acordo.
