### ISSUE TITLE
[MELHORIA]Perfis-Gestor de Acompanhamento e Gestor do Indicador

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#631]
Criação dos perfis "Gestor de Acompanhamento" e "Gestor do Indicador".

###### RN3 - Gestor de indicador pode cadastrar todos os dados de Indicador incluindo a série histórica, porém não pode alterar nada.

**Comment by rafaeljcg20** [comment]
Branch: hotfix-631-perfis-acompanhamento-indicadores

**Comment by dougs007** [comment]
Testado em homologação : 

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/listarMetasIndicador&acao=A
http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/valorMetasIndicador&acao=A

**Comment by rafaelfcar** [comment]
De acordo com o Gabriel, não foi possível testar a demanda pois ainda não tem os usuários definidos para cada perfil.
A demanda será fechada para publicação de outras demandas dependentes.
