### ISSUE TITLE
[CADASTRO] Criar tela para Funcionais

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#64]

**Comment by dougs007** [comment]
Branch : issue-64-funcionais

**Comment by Rafaeljcg20** [comment]
Obrigado @dougs007 pelo nome da Branch !     

XD

**Comment by Rafaeljcg20** [comment]
@dougs007, combinamos de cadastrar esses menus novos em produção sem visibilidade... Você conseguiu fazer esse cadastro já?

**Comment by Rafaeljcg20** [comment]
Testado

**Comment by macavalheiro** [comment]
> Não estou conseguindo acesso a esse menu direito. a Visualização fica cortada conforme o monitor;

> ao incluir nova funcional, não consegui acessar a ação que criei (marcelo teste); 
> ao tentar inserir nova ocorrência não gravou

> conforme conversa telefonica com orion, transformar tudo que for "po" EIND  (plano orçamentário Emenda Individual)  em rp 6

> incluir rotina de atualização diária siop (ver com orion)

**Comment by Rafaeljcg20** [comment]
* Retirar campos de valores.
* Verificar o porque a ação cadastrada na tela de Ação não foi visualizada na tela de cadastro de funcionais.

**Comment by Rafaeljcg20** [comment]
Boa noite @macavalheiro ! Foram retirados os campos de valores e foi corrigido a funcionalidade de buscar lista de ações para ser possível cadastrar a funcional com a nova ação criada.

**Comment by macavalheiro** [comment]
consegui criar a ação e o resto está ok

entretanto a ação criada não aparece na tela vincular ptres, que é onde eu vincularia para aparecer na tela formulário do pi.

**Comment by Rafaeljcg20** [comment]
Oi @macavalheiro , Poderia nos informar qual o id da funcional(ptrid) ou código da funcional pra eu reproduzir o erro e corrigir com mais velocidade?

**Comment by macavalheiro** [comment]
ptrid 2262

creio até está aparecendo o po q criei (xxxx)  porem com as colunas prog, ação, local vazias

**Comment by Rafaeljcg20** [comment]
Está sendo utilizado o campo acacod da tabela ptres

**Comment by Rafaeljcg20** [comment]
Corrigido os dados de prog, ação, local. @macavalheiro , poderia tentar validar novamente a demanda?

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/vincular-ptres&acao=A
