### ISSUE TITLE
[CORREÇÃO] Cadastro de Beneficiário - Observações.

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#640]
No cadastro de Beneficiário, na parte das Observações, o sistema está permitindo submeter o formulário com os campos obrigatórios em branco.
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/c931d028-6f61-4e41-9b91-276b7b81bf69) 

- [ ] Corrigir função que submete formulário, respeitando a obrigatoriedade dos campos de data e de observação.

**Comment by dougs007** [comment]
Nome da branch :  hotfix-planejamento-beneficiario-observacao

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8420
