### ISSUE TITLE
[CORREÇÃO]Primeiro Acesso-Liberação de usuários email

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#649]
Verificar e corrigir envio de e-mail para os usuários que estão solicitando acesso ao sistema pela primeira vez.

Dica: Fazer o procedimento de primeiro acesso com um CPF fictício para reproduzir o problema.

Demandante: Marcelo-SPO( @macavalheiro )

**Comment by rafaeljcg20** [comment]
Branc: hotfix-649-liberacao-usuario-email

**Comment by rafaeljcg20** [comment]
Demanda retomada.

**Comment by rafaeljcg20** [comment]
Demanda paralisada pra atender a #667

**Comment by dougs007** [comment]
Testado em homologação em todos os módulos, segue prints abaixo :

Alterações :
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/3cffbb46-f39c-4886-97b1-2876b3c3735d)

Emendas :
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/9c05ccd9-e48f-4f8d-8347-eeeca1e90549)

Monitoramento :
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/a8554283-5097-43a2-a0ce-007141a3d22b)

Gestão : 
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/319647fc-dccf-43e3-89f8-0befd4b993f2)

Planejamento :
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/83a45b58-8da6-4d60-a11a-637a0b4f3c8d)


Proposta :
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/5c9dd77b-4a6c-47dd-ba8f-62075438d1f2)

**Comment by macavalheiro** [comment]
Rafa, essa demanda já está em produção? Pois só o produção manda e-mail, né? Fiz o teste aqui com um cpf ficticio e não recebi o e-mail, nem o pessoal aqui

**Comment by rafaeljcg20** [comment]
@macavalheiro 
Oi Marcelo, identificamos que o problema acontece quando os usuários informam endereços externos ao da cultura(nome@cultura.gov.br) e estamos ajustando a configuração do servidor SMTP para resolver o problema.

**Comment by rafaeljcg20** [comment]
Configuração corrigida.

**Comment by macavalheiro** [comment]
Rafa, fiz 3 pedidos de acesso no sistema. Mudei meu perfil para Administrador e Aspar (antes tava super usuário) e em não recebi nenhum e-mail com o pedido
