### ISSUE TITLE
[CADASTRO] Criar tela para Produto do PI

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#65]

**Comment by macavalheiro** [comment]
tela nova, que vai alimentar o campo produto dentro do formulário padrão do módulo planejamento (modulo planejamento > criar pi)

**Comment by Darciro** [comment]
Branch: hotfix-65-planejamento-crud-produtos-pi

**Comment by dougs007** [comment]
Testado em Homologação => http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/produtos_pi&acao=A#

**Comment by rafaeljcg20** [comment]
@dougs007, favor criar o menu e dar acesso aos perfis de Super Usuário, Administrador no ambiente de produção pra concluir a publicação da demanda.
