### ISSUE TITLE
Ajustes - CGINC - Detalhar demandas

### ISSUE THREAD

**Issue by Gabrielran** [culturagovbr/siminc2#650]
[ OK ]1 - Criar maneira de acrescentar ações no combo de cadastro de indicador;
[ #656 ] 2 - Alterar a página inicial pós login para a listagem de indicadores,
[ #660 ] 3 - Usar a lógica de categorização da listagem de indicadores (por secretaria) também na listagem das metas (http://siminc2.cultura.gov.br/painel/painel.php?modulo=principal/listarMetasIndicador&acao=A).
[ #661 #662] 4 - Acrecentar campo "observação" nos "valores da meta". Se possível, apresentar também no gráfico. Remover campos Estratégias e Ações Estratégicas. (http://siminc2.cultura.gov.br/painel/painel.php?modulo=principal/listarMetasIndicador&acao=A)
[ #663 ] 5 - Limpar as opções da aba principal, mantendo somente o estritamente necessário.
[ #664 ] 6 - Fazer com o que o sistema reconheça os marcos de 0%, tanto na serie histórica como na meta.
[ #665 ] 7 - Fixar os menus do indicador, sem variações.
[ #666 ] 8 - Acrescentar marcador de realização no relatório.

**Comment by rafaeljcg20** [comment]
As demandas foram detalhadas e associadas a cada item solicitado, podendo ser modificadas e priorizadas pelos demandantes ou pela equipe de desenvolvimento a a partir de agora.
