### ISSUE TITLE
[CORREÇÃO]Página Inicial do Painel

### ISSUE THREAD

**Issue by rafaelfcar** [culturagovbr/siminc2#656]
Alterar a página inicial pós login para a listagem de indicadores

**Comment by rafaelfcar** [comment]
branch: hotfix-656-painel-redirecionamento-inicial

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/lista&acao=A
