### ISSUE TITLE
[MELHORIA]Painel Cadastro de Metas

### ISSUE THREAD

**Issue by rafaelfcar** [culturagovbr/siminc2#658]
Acrecentar campo "observação" nos "valores da meta". Se possível, apresentar também no gráfico. Remover campos Estratégias e Ações Estratégicas. (http://siminc2.cultura.gov.br/painel/painel.php?modulo=principal/listarMetasIndicador&acao=A)

**Comment by rafaelfcar** [comment]
branch: hotfix-658-painel-cadastro-metas

Scripts:
alter table painel.detalhemetaindicador add column dmiobs varchar(255);

**Comment by dougs007** [comment]
Testado em homologação :  

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/metaIndicador&acao=A
