### ISSUE TITLE
[MELHORIA]Listagem de Metas do Indicador-Remover colunas da tabela

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#662]
Na tela Listagem de Metas do Indicador, remover as colunas "Estratégias e "Ações Estratégicas" da tabela.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/15d661fc-d4bf-4d22-a465-5a38ece11f34)

**Comment by dougs007** [comment]
Nome da branch :   hotfix-662-painel-listagem-metas

**Comment by leossb36** [comment]
testada em homologação:
http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/listarMetasIndicador&acao=A
