### ISSUE TITLE
[CORREÇÃO]Gráfico de Metas do Indicador-Marcos inciando por zero

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#664]
Na tela Metas do Indicador, corrigir o sistema pra mostrar os marcos que recebem valor 0 no gráfico.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/6e1fb61b-64a9-4155-83b9-8bf914dad4ab)

**Comment by dougs007** [comment]
Testado em homologação :

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/metaIndicador&acao=A
