### ISSUE TITLE
[CORREÇÃO]Navegação das Abas de edição de Indicadores

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#665]
Corrigir a navegação das abas de edição dos indicadores para persistir as abas anteriores as abas "Editar Metas do Indicador" e "Valores de Meta".

Obs: Atualmente quando se clica pra editar Meta do Indicador na tela "Listagem de Meta do Indicador" o sistema oculta as abas anteriores causando dúvidas ao navegar pelo sistema.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/9456a89c-fb49-4605-aaee-0226b5228196)

**Comment by leossb36** [comment]
nome da branch: hotfix-665-painel-navegacao-de-abas

**Comment by dougs007** [comment]
Testado em homologação :

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/metaIndicador&acao=A
