### ISSUE TITLE
[MELHORIA]Criar PI por Proposta

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#667]
Atualmente a funcionalidade acessada a partir do menu Principal -> Criar PI por Proposta busca os dados de Propostas Orçamentárias do SIMINC1 e preenche parte do formulário de criação de um novo PI para dar continuidade ao processo de capitação executiva. O sistema deverá ser mudado pra ao invés de buscar os dados de Proposta do SIMINC1, para buscar os dados de Pré-PI do módulo Proposta Orçamentária do SIMINC2.

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listar_propostas_pi&acao=A

**Comment by rafaeljcg20** [comment]
Branch: hotfix-667-planejamento-pi-proposta

**Comment by rafaeljcg20** [comment]
Publicação solicitada(Pull Request)
