### ISSUE TITLE
[CORREÇÃO] Componente de opções 

### ISSUE THREAD

**Issue by leossb36** [culturagovbr/siminc2#668]
- [x] Corrigir tratamento de componente de opção(sim, não e todos). O componente não está diferenciando o não de todos sem diferenciar '0' de NULL e trazendo os dois campos marcados

**Comment by leossb36** [comment]
nome da branch: hotfix-correcao-componente-php

**Comment by rafaeljcg20** [comment]
Na fase de teste houve Impacto negativo na tela de Cadastro de Beneficiários. Vamos analisar o erro, identificar se existe padrões pra gerar o erro identificado pra mapear o montante de refatorações necessárias e analisar a viabilidade de continuar com essa correção no componente.

**Comment by rafaeljcg20** [comment]
Demanda cancelada. por não ser viável o tempo de refatoração dos pontos de impacto no sistema.
