### ISSUE TITLE
[CORREÇÃO] Vincular Objetivo com Metas e Iniciativas

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#67]
Na tela de Cadastro de Objetivo PPA, inserir funcionalidade de vincular Metas e Iniciativas.
Obs: Deve ser verificado se as metas inseridas e vinculadas vão aparecer corretamente na tela de Vincular Metas(que vincula meta a unidade).

**Comment by rafaelfcar** [comment]
branch: hotfix-67-planejamento-vincular-objetivos-metas

**Comment by leossb36** [comment]
##### testado em homologação: 

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/objetivoppa_form&acao=A&oppid=86

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A

**Comment by macavalheiro** [comment]
> o botão editar das iniciativas não está funcionando
>  código das iniciativas precisa aceitar letras tb e ter 4 digitos. (assim como as inciativas que já estão no sistema
> na listagem de inciativa, uma coluna mostrando o código ajudaria muito tb
> descrição não precisaria ser obrigatório
> as metas não estão puxando o código correto (com letras e números, lá da tabela metas)

**Comment by macavalheiro** [comment]
Valeu Douglas!

Em Qua, 4 de jul de 2018 11:26, Douglas Santana <notifications@github.com>
escreveu:
