### ISSUE TITLE
[MELHORIA]Construtor de Relatórios-Cabeçalho e Filtros

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#674]
Adicionar as seguintes mudanças e melhorias na atual tela de Relatórios Gerenciais:
- [x] Mudar nome do menu e cabeçalho da tela de "Relatórios Gerenciais" para "Construtor de Relatórios";
- [x] Inserir Cabeçalho conforme o exemplo anexado informando o nome da Subunidade quando houver apenas uma subunidade selecionada;
- [x] Inserir linha de Totais com as devidas somas das colunas que têm valor de moeda.
- [x] Inserir no final da tela/página impressa a lista de filtros selecionados do relatório gerado.

![Relatórios melhorias.jpg](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/836da59d-0aea-4901-b7b6-0c44e55c5d40)

**Comment by dougs007** [comment]
Nome da branch :  
hotfix-674-monitoramento-construtor-relatorios

**Comment by HenriqueOliveiradosAnjos** [comment]
No Relatório de Proposta as colunas "Subunidade, Natureza de Despesa e Ano " não estão puxando as informações.

**Comment by dougs007** [comment]
Oi Henrique, bom dia !
Foi feita a correção, poderia validar para nós novamente ?

Obs: Será necessário sair do sistema e logar novamente para o ambiente trazer as últimas atualizações.
