### ISSUE TITLE
[MELHORIA]Construtor de Relatórios-Salvar

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#675]
Desenvolver nova funcionalidade de salvar os campos selecionados, filtros aplicados e nome pra cada configuração de relatório semelhante a funcionalidade de salvar Relatório do SIMINC1/SIMEC.

- [x] Criar botão de Salvar Relatório.
- [x] Criar lista de relatórios salvos com o nome do relatório, nome do criador, data de criação e os ícones de ações visualizar e excluir.
- [x] Ao clicar em Salvar o sistema deverá exibir uma caixa de entrada de texto solicitando o nome pra o relatório e o botão de confirmar.
- [x] Após o usuário acionar a opção confirmar, o sistema deverá salvar as colunas selecionadas e todos os filtros selecionados.
- [x] Ao clicar na opção visualizar da lista de relatórios, o sistema deverá carregar todas as colunas selecionadas e filtros daquele Relatório salvo anteriormente.

Regras:
RN1 - O sistema não deverá permitir salvar o relatório sem nome informado pelo usuário.

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A&crid=29
