### ISSUE TITLE
[MELHORIA]Tela de Administrar Tipo de alteração orçamentária

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#679]
Criar nova tela de Apoio "Tipo"(Inserir, Editar, Visualizar e excluir) para poder administrar as informações de tipo de alterações orçamentárias.

**Comment by dougs007** [comment]
Nome da branch:
feature-alteracoes

OBS: branch usada para o módulo todo de alterações até o momento.

Observações para versionamento

- [ ] Publicar menu em produção.
- [ ] Solicitar execução do script da criação das tabelas.

**Comment by dougs007** [comment]
Segue script a ser executado:



﻿-- DROP SEQUENCE alteracao.tipo_tpaid_seq;
CREATE SEQUENCE alteracao.tipo_tpaid_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE alteracao.tipo_tpaid_seq
  OWNER TO postgres;
GRANT ALL ON SEQUENCE alteracao.tipo_tpaid_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE alteracao.tipo_tpaid_seq TO usr_simec;

﻿-- DROP TABLE alteracao.tipo;
CREATE TABLE alteracao.tipo
(
  tpaid integer NOT NULL DEFAULT nextval('alteracao.tipo_tpaid_seq'::regclass), -- Chave Primária
  tpacod character varying(15) NOT NULL,
  tpadsc character varying(125) NOT NULL,
  tpaobs character varying(125),
  tpastatus character(1) NOT NULL DEFAULT 'A'::bpchar, -- Status: ...
  CONSTRAINT pk_alteracao_tipo_tpid PRIMARY KEY (tpaid)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE alteracao.tipo
  OWNER TO postgres;
GRANT ALL ON TABLE alteracao.tipo TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE alteracao.tipo TO usr_simec;
COMMENT ON TABLE alteracao.tipo
  IS 'Tipo de Alteração Orçamentária';
COMMENT ON COLUMN alteracao.tipo.tpaid IS 'Chave Primária';
COMMENT ON COLUMN alteracao.tipo.tpacod IS 'Código do Tipo de Crédito';
COMMENT ON COLUMN alteracao.tipo.tpadsc IS 'Descrição do Tipo de Crédito';
COMMENT ON COLUMN alteracao.tipo.tpaobs IS 'Observação do Tipo de Crédito';
COMMENT ON COLUMN alteracao.tipo.tpastatus IS 'Observação do Tipo de Crédito';

**Comment by rafaelfcar** [comment]
testado em homologação
http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=apoio/tipo&acao=A

**Comment by macavalheiro** [comment]
tb não achei o menu, no meu perfil

**Comment by rafaelfcar** [comment]
Marcelo, também já foi corrigido.

**Comment by macavalheiro** [comment]
Boa Valeu

Só faltou a opção de definir se é um tipo interno ou externo, conforme o papel dessa tela

**Comment by rafaeljcg20** [comment]
@dougs007, amanhã, coloca pra gente por favor o campo de tipo, qualquer dúvida me procure.

**Comment by dougs007** [comment]
Atendida a solicitação do campo de Tipo.

**Comment by dougs007** [comment]
Testado em homologação.

http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=apoio/tipo&acao=A
