### ISSUE TITLE
[MELHORIA]WORKFLOW-Cadastro de fluxo Interno e Externo

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#680]
Ao chegar no final do workflow interno ou externo o sistema deverá alterar os valores de Físico, Custeio e Capital dos PIs envolvidos no pedido de alteração orçamentária.

Fluxo Interno:
![image](https://user-images.githubusercontent.com/17576143/47162771-ffb3cb80-d2ca-11e8-9985-e021d1a33f9b.png)

Fluxo Externo:
![image](https://user-images.githubusercontent.com/17576143/47162827-22de7b00-d2cb-11e8-9f1a-ea4fb1fb29c8.png)

**Comment by rafaeljcg20** [comment]
O Workflow foi cadastrado, porém o sistema ainda não possui a funcionalidade de alterar valores dos PIs envolvidos no pedido de alteração orçamentária, portanto essa demanda ficará paralisada até a conclusão de todos os passos do cadastro de pedidos de alteração.

**Comment by macavalheiro** [comment]
Ok Rafa! Não consegui testar ainda nem só o Workflow pois não consegui criar um Novo Pedido para testar a tramitação.  De qquer forma como vc falou q ficará paralisada, vou aguadar.
