### ISSUE TITLE
[MELHORIA]Tela de Espelho de Alterações Orçamentárias

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#681]
Desenvolver a tela de espelho de alterações orçamentárias conforme o protótipo.

![tela espelho de pedido de alteracao orcamentaria](https://user-images.githubusercontent.com/17576143/46313969-a98f1a80-c59f-11e8-9379-3da68d9574e1.png)

**Comment by rafaeljcg20** [comment]
O esforço estimado pela equipe foi de 13 pontos desconsiderando o desenvolvimento dos gráficos que também não foram definidos.

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=principal/cadastro_alteracoes&acao=C&pedid=29&tpdid=269
