### ISSUE TITLE
[MELHORIA] Painel - Relatório de Indicadores

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#689]
- [x] Adicionar campo de Observação do gestor no relatório de indicadores.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/2110b417-1f45-430d-9de8-6b0156bd774b)

**Comment by rafaelfcar** [comment]
branch: hotfix-689-painel-relatorio-indicadores

**Comment by dougs007** [comment]
Testado em homologação :

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=relatorio/indicadores-secretaria&acao=A

**Comment by dougs007** [comment]
O Gabriel ficou de verificar se no relatório geral terá o thumbs ou/e o de observação do gestor.

**Comment by rafaeljcg20** [comment]
Demandante Gabriel informou pessoalmente que a demanda foi aceita e poderia ser publicada, ainda que foram solicitadas novas melhorias.
