### ISSUE TITLE
criar perfils consulta e gestão consulta

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#69]
perfil consulta e perfil gestão consulta conforme aba "perfis" do doc anexo

https://docs.google.com/spreadsheets/d/1_4Z90H1diHqpSJPgl-USrNu785VsGiPelEfYXILQObs/edit#gid=333462702

aba perfils

**Comment by Rafaeljcg20** [comment]
https://docs.google.com/spreadsheets/d/1_4Z90H1diHqpSJPgl-USrNu785VsGiPelEfYXILQObs/edit#gid=333462702

**Comment by Rafaeljcg20** [comment]
Branch: issue-69-criar-perfil

**Comment by g-adler** [comment]
OK em homolog - Adler

**Comment by Rafaeljcg20** [comment]
Publicada.
