### ISSUE TITLE
[MELHORIA]Construtor de Relatórios-Disponibilizar pra Perfil Unidade

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#694]
- [x] Disponibilizar a tela Construtor de Relatórios para os usuários do perfil Unidade.

 - [x] RN1 - Quando o usuário com o perfil de Unidade entrar na tela Costrutor de Relatórios o sistema deverá exibir apenas os dados vinculados as Unidades que o Usuário está associado.

**Comment by rafaelfcar** [comment]
branch: hotfix-694-monitoramento-gerador-relatorio

**Comment by dougs007** [comment]
Testado em homologação :

http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A
