### ISSUE TITLE
[MELHORIA] Ws Siop - Log no banco

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#695]
- [x] Retirar das rotinas do SIOP os log's do WS no banco de dados.

Obs:

Após a publicação, rodar o script de apagar os dados da tabela de log
- [x] Script solicitado: Apagar a tabela =>  spo.logws

**Comment by dougs007** [comment]
Demanda paralisada para aguardar o problema temporário do SIOP.

**Comment by rafaeljcg20** [comment]
A demanda foi concluída com a implementação de um novo cliente de Webservice #727 .
