### ISSUE TITLE
[CORRECAO] Painel - Cadastro de Indicadores

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#698]
- [x] Ao cadastrar um novo indicador e mudar a periodicidade de indicador, não exibir mensagem "Se alterar a periodicidade a série histórica será apagada!"

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/cadastro&acao=A&indid=novoIndicador
