### ISSUE TITLE
[MELHORIA]Cadastro de PI e Criar PI por Proposta 2019-Teste

### ISSUE THREAD

**Issue by leossb36** [culturagovbr/siminc2#705]
No módulo Planejamento Orçamentário testar a tela "Cadastro de PI" e a tela "Criar PI por Proposta" com exercício 2019 para apoiar a apresentação do sistema.
Cadastrar um PI com os seguintes casos de Enquadramento:
- [x] Benefícios ao servidor
- [x] Finalístico
- [x] Manutenção
- [x] Não orçamentaria
- [x] Cadastrar PI por proposta

Demandante: Lindberg

**Comment by dougs007** [comment]
Quando o enquadramento for "Finalístico" e no ano de 2019:

Na coluna de 'Vinculações Eventuais do Projeto', o campo de 'Número do Processo' não está excluindo registro.
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/57f03f35-e722-4b27-abf0-bd476896fb72)

Na coluna de 'Anexos', ao clicar no botão de inserir anexos e escolher o arquivo, o sistema diz que foi salvo com sucesso, mas não lista o arquivo inserido.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/cfa2f95f-1c04-4edd-9eb8-da0e77df90fb)

**Comment by leossb36** [comment]
Não foi possível cadastrar pi de emendas para o ano de 2019.
Devido ao exercício do modulo emendas não existe emendas para 2019, assim impossibilitando a criação de um pi voltada para este exercício.

**Comment by leossb36** [comment]
@dougs007 para o exercicio de 2018 os mesmo problemas ocorrem.

**Comment by leossb36** [comment]
Impedimento com cadastro de pi de emendas solucionado.
Foi sanado as duvidas com @rafaeljcg20, não sendo mais necessário o de emendas. Portanto será removida da demanda.

**Comment by rafaelfcar** [comment]
branch:

hotfix-705-planejamento-cadastro-pi

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10815

**Comment by rafaeljcg20** [comment]
Considerando a apresentação do sistema hoje no estado do Rio de Janeiro, a publicação se tornou urgente pra evitar transtornos.
