### ISSUE TITLE
[MELHORIA]Painel Relatório de Indicadores

### ISSUE THREAD

**Issue by rafaelfcar** [culturagovbr/siminc2#707]
- [x] Alterar a Regra das cores, colocando verde para tudo que for realizado maior ou igual a meta.
- [x] Mudar barra de progresso para a coluna de realizado
- [x] Coluna Orçamento depois de produto
- [x] Coluna Observação por último
- [x] Fixar Largura das colunas
- [x] Colocar Avaliação do Gestor (thumbsup, thumbsdown, exclamação), no começo da linha

**Comment by rafaelfcar** [comment]
branch: hotfix-707-painel-relatorio-indicadores

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=relatorio/indicadores-secretaria&acao=A
