### ISSUE TITLE
[MELHORIA]Painel Avaliação do Gestor

### ISSUE THREAD

**Issue by rafaelfcar** [culturagovbr/siminc2#708]
- [x] Criar mais um ícone para avaliação do gestor de acompanhamento(exclamação)

**Comment by rafaelfcar** [comment]
branch: hotfix-708-painel-avaliacao-gestor

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/avaliacaoGestor&acao=A
