### ISSUE TITLE
[CORREÇÃO]Painel Lista de Indicadores

### ISSUE THREAD

**Issue by rafaelfcar** [culturagovbr/siminc2#709]
- [x] Corrigir filtros na pesquisa da listagem

**Comment by rafaelfcar** [comment]
branch: hotfix-709-painel-lista-indicadores

**Comment by dougs007** [comment]
Testado em homologação : 

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/lista&acao=A
