### ISSUE TITLE
Aviso comparando divergência entre valores empenhados da funcional vs PI

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#71]
Para tanto, na tela do modal "PI's da Funcional na Unidade" detalhando os PIs da funcional exibir  outra linha com total por funcional e também enviar email quando houver

**Comment by Rafaeljcg20** [comment]
colunas no email:

Funcional	Unidade	PI   	Titulo   Previsto	Provisionado	Empenhado	Liquidado	Pago

Onde as colunas Previsto	Provisionado	Empenhado	Liquidado	Pago serão a diferença entre o valor da funcional e o somatório dos pis dessa funcional.

**Comment by macavalheiro** [comment]
Onde diz "TOTAL" trocar por "TOTAL PI´S"


o campo custeio e capital não estão puxando e o provisionado parece estar puxando o total.

já os campos empenhado, liquidado e pago parecem já estar ok

**Comment by Rafaeljcg20** [comment]
Enviamos uma nova correção.

**Comment by Rafaeljcg20** [comment]
Publicada
