### ISSUE TITLE
[MELHORIA]Painel Relatório de Indicadores

### ISSUE THREAD

**Issue by rafaelfcar** [culturagovbr/siminc2#711]
- [x] Quebra de página para cada Secretaria

Demandante: Felipe-SE

**Comment by rafaelfcar** [comment]
Funciona somente no Mozila Firefox

**Comment by rafaeljcg20** [comment]
Em acordo com o Felipe e o Gabriel explicamos que no navegador Chrome a quebra de linha não está funcionando e os demandantes concordaram em utilizar o Firefox pra realizar as impressões corretamente.

**Comment by rafaeljcg20** [comment]
O demandante Sr. Wallace-SE apoiado pelo Sr. Felipe-SE, solicitou que fosse colocado um aviso no sistema informando que o relatório é melhor visualizado no navegador Mozila Firefox em função do erro de quebra de páginas.

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=relatorio/indicadores-secretaria&acao=A&secid=
