### ISSUE TITLE
[MELHORIA]Lista de PI-Total de Custeio com Capital

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#712]
Na tela lista de PI e Lista de PI FNC, incluir uma coluna total sendo a soma de custeio com capital pra facilitar o uso dos usuários com perfil de Subunidade.

Demandante: Paulo Henrique - CGTEC/Marcelo - SPOA

**Comment by rafaelfcar** [comment]
testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapimanter_fnc&acao=A

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapimanter&acao=A

**Comment by macavalheiro** [comment]
Em um dos meus monitores ficou cortado, de forma que não consigo arrastar para ver a ultima coluna. 

Será que não é o caso de suprimir a colunas "custeio" e "capital" e apresentar esses valores na forma de rint apenas?

**Comment by dougs007** [comment]
Oi marcelo, boa tarde !
Foi feita essa alteração, depois poderia validar para nós por favor ?
