### ISSUE TITLE
[CORREÇÃO]Painel Relatórios de Indicador

### ISSUE THREAD

**Issue by rafaelfcar** [culturagovbr/siminc2#717]
Alterar o campo observação para buscar da aba de Avaliação do Gestor

**Comment by rafaelfcar** [comment]
branch:

hotfix-717-painel-relatorio-indicadores

**Comment by leossb36** [comment]
testado em homologação:

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=relatorio/indicadores-secretaria&acao=A

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/avaliacaoGestor&acao=A
