### ISSUE TITLE
[CORREÇÃO]Painel Avaliação do Gestor

### ISSUE THREAD

**Issue by rafaelfcar** [culturagovbr/siminc2#718]
Na aba Avaliação do Gestor permitir que o perfil "Gestor Acompanhamento", possa editar o campo observações.

**Comment by rafaelfcar** [comment]
branch:
hotfix-718-painel-avaliacao-gestor

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/avaliacaoGestor&acao=A
