### ISSUE TITLE
voltar o cancelado no workflow

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#72]
não permitir reativar pi cancelado se não houver saldo na funcional ou no limite.

**Comment by Rafaeljcg20** [comment]
adicionar o estado cancelado no fluxo e como pós ação atualizar o status para inativo.

**Comment by Rafaeljcg20** [comment]
Branch: hotfix-issue-72

**Comment by Rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br

**Comment by macavalheiro** [comment]
Massa!

**Comment by Rafaeljcg20** [comment]
Oi Marcelo, esse erro aconteceu no ambiente de teste porque havia um registro de Subunidade com código do SIOP contendo caracteres alpha numéricos, mas isso não vai acontecer em produção porque corrigimos esse problema ainda em fase de desenvolvimento.

Muito obrigado por avisar! Se perceber qualquer outro risco ao projeto, fique a vontade pra continuar nos informando.

Obs: No ambiente de teste já corrigi o registro na base de dados que gerava esse erro.

**Comment by macavalheiro** [comment]
Massa! ficou bem legal essa demanda. testei várias coisas q poderiam dar errado, e todas passaram no teste

**Comment by Rafaeljcg20** [comment]
Pull Request pra publicação.
