### ISSUE TITLE
[CORREÇÃO]Painel - Cadastro de Indicadores

### ISSUE THREAD

**Issue by Gabrielran** [culturagovbr/siminc2#724]
1 - O campo "Observações do Gestor" é apagado quando é realizado algum ajuste no cadastro do indicador.
2 - O campo "Observações do Gestor" não grava quando apagamos toda a informação e desmarcamos o sinal de Thumbs.

**Comment by rafaelfcar** [comment]
branch: hotfix-724-painel-cadastro-indicadores

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/avaliacaoGestor&acao=A
