### ISSUE TITLE
[MELHORIA]Tela de Administrar Janela

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#729]
Criar nova tela de Apoio "Janela"(Inserir, Editar, Visualizar e excluir) para poder administrar as informações de Janela.

Segue imagem do modelo do siminc que será base no siminc2.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/70e3e087-ce03-492f-a1ae-6e3ad586887d)

**Comment by dougs007** [comment]
Nome da branch:
feature-alteracoes

OBS: branch usada para o módulo todo de alterações até o momento.

Observações para versionamento

- [ ] Publicar menu em produção.
- [ ] Solicitar execução do script da criação das tabelas.

**Comment by dougs007** [comment]
Script a ser publicado para as tabelas da demanda

- [ ] Solicitar publicação do script em prod

-- DROP SEQUENCE alteracao.tipo_alteracao_tao_seq;
CREATE SEQUENCE alteracao.janela_janid_seq
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER TABLE alteracao.janela_janid_seq
OWNER TO postgres;
GRANT ALL ON SEQUENCE alteracao.janela_janid_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE alteracao.janela_janid_seq TO usr_simec;

-- DROP TABLE alteracao.janela;
CREATE TABLE alteracao.janela
(
janid integer NOT NULL DEFAULT nextval('alteracao.janela_janid_seq'::regclass), -- Chave Primária
jannome character varying(125) NOT NULL, -- Descrição
janinicio timestamp without time zone NOT NULL, -- Data Início
janfim timestamp without time zone NOT NULL, -- Data Final
janinicioprogramacao timestamp without time zone, -- Data Início Programação
janfimprogramacao timestamp without time zone, -- Data Final Programação
janstatus character(1) NOT NULL DEFAULT 'A'::bpchar, -- Status:...
prsano character(4) NOT NULL, -- Ano
CONSTRAINT pk_janela_janid PRIMARY KEY (janid)
)
WITH (
OIDS=FALSE
);
ALTER TABLE alteracao.janela
OWNER TO postgres;
GRANT ALL ON TABLE alteracao.janela TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE alteracao.janela TO usr_simec;
COMMENT ON TABLE alteracao.janela
IS 'Tipo de Alteração Orçamentária';
COMMENT ON COLUMN alteracao.janela.janid IS 'Chave Primária';
COMMENT ON COLUMN alteracao.janela.jannome IS 'Nome da Janela';
COMMENT ON COLUMN alteracao.janela.janinicio IS 'Data Início da Janela';
COMMENT ON COLUMN alteracao.janela.janfim IS 'Data Final da Janela';
COMMENT ON COLUMN alteracao.janela.janinicioprogramacao IS 'Data Início da Janela de Programação';
COMMENT ON COLUMN alteracao.janela.janfimprogramacao IS 'Data Final da Janela de Programação';
COMMENT ON COLUMN alteracao.janela.janstatus IS  'Status:
A - Ativo
I - Inativo';
COMMENT ON COLUMN alteracao.janela.prsano IS 'Exercício da janela cadastrada';

**Comment by rafaelfcar** [comment]
testado em homologação
http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=apoio/janela&acao=A

**Comment by macavalheiro** [comment]
não sei se é perfil, mas não consegui acessar o menu em homologa

**Comment by rafaelfcar** [comment]
Marcelo, já foi corrigido, favor testar novamente.
