### ISSUE TITLE
[MELHORIA] Padronização de layout de icones das principais lista

### ISSUE THREAD

**Issue by leossb36** [culturagovbr/siminc2#730]
- [x] Fazer um mapeamento para identificar todos os ícones(Editar e Excluir) das listas principais do sistema que não estão dentro de formulários para colocar no padrão do Lista de PI do módulo Planejamento Orçamentário.
- [x] Alterar para o padrão estabelecido na tela Lista de PI do módulo Planejamento Orçamentário.

**Comment by leossb36** [comment]
nome da branch: hotfix-730-padronizacao-de-layout

**Comment by rafaeljcg20** [comment]
Oi @leossb36, ficou excelente. Se puder, nessa mesma demanda(branch) ajuste a tela Lista de Emendas do módulo Emendas Parlamentares para o mesmo padrão de cores de botões da tela Lista de PI do módulo Planejamento Orçamentário?

Exemplo:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/1472e658-7482-4653-8086-441bb26f0b2f)

**Comment by dougs007** [comment]
Observações feitas na hora do teste :
- [ ] Planejamento

* Diferença de cor de botão "Novo" nas telas gerenciais => laranjado. para Telas de filtro =>azul
* Algumas páginas do Planejamento ficaram com o espaçamento da coluna ações maiores que outras, apesar de ambas conterem apenas o ícone de edição. segue exemplo abaixo 
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/d84a0706-d38a-4627-a550-a856de37ff20)
Sugestão: usar width: 10%; ou 5%; 
* Alguns nomes da coluna de ação estão como "Ação" e outros "Ações", sendo que ambos contém o mesmo ícone de edição.

- [ ] Emendas

* Lista principal, ícone "novo" trocar de cor com o ícone de limpar.
* Telas de Apoio => Trocar iícone de novo para cor azul, mudar nome do campo para ação e padronizar o width.

- [ ] Monitoramento

* Telas de Apoio => Trocar iícone de novo para cor azul, mudar nome do campo para ação e padronizar o width.

- [ ] Proposta
* Listagem de proposta, mudar nome de ações para ação e padronizar width.
* Listagem de pre-pi mudar nome de ações para ação e padronizar width.
* Telas de apoio,  mudar nome de ações para ação e padronizar width.

**Comment by dougs007** [comment]
Testado em homologação em todos os módulos.
