### ISSUE TITLE
[MELHORIA]Perfil Gestor de Indicadores

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#736]
As seguintes mudanças e acréscimos de papel deverão ser implementadas para o Perfil de Indicador:
- [x] Na lista de indicadores o sistema deverá permitir visualizar todos os indicadores;
- [x] Na tela de Cadastro de Indicadores o sistema só deverá permitir o usuário alterar o indicador vinculado a mesma Secretaria/Unidade atribuída ao seu perfil;
- [x] Na tela de Serie histórica o sistema deverá permitir o Usuário alterar os dados além de inserir;
- [x] Na tela de Avaliação de acompanhamento deverá ser criado um novo campo de observação do Gestor de Indicador.

**Comment by rafaelfcar** [comment]
branch: hotfix-736-painel-perfil-indicadores

Scripts:
alter table painel.indicador add column indobsgestorindicador varchar(255);

**Comment by dougs007** [comment]
- [ ] Ao editar um indicador de sua unidade, ao salvar o sistema não está permitindo.

- [ ] Ao clicar na aba de Metas do Indicador, o sistema está dando acesso negado.
