### ISSUE TITLE
[MELHORIA]Perfil Consultor

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#737]
Implementar as telas usadas pra gestão estratégica(ações, metas, indicadores, serie histórica...) para que o perfil Consultor possa visualizar todos os dados, mas não possa alterar.

Demandante: Felipe e Gabriel - SE

**Comment by rafaelfcar** [comment]
Fazer depois que executar a demanda 736.

**Comment by dougs007** [comment]
Demanda fechada.
Motivo: Módulo Descontinuado
