### ISSUE TITLE
[MELHORIA]Portal Gestão Estratégica-Relatórios

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#738]
No portal Gestão Estratégica, na tela acessada através do menu Plano de diretrizes e metas -> Plano de Ação(gestaoestrategica.cultura.gov.br/plano-de-acao) o sistema deverá exibir o Relatório de Indicadores e um novo relatório que será detalhado posteriormente no lugar do conteúdo atual.

Demandante: Felipe e Gabriel - SE

**Comment by rafaelfcar** [comment]
create view relatorios.vw_relatorios_indicador AS
SELECT DISTINCT i.indid,
	    s.secordem,
            i.indnome AS nome,
            unm.unmdesc AS unidade,
            ume.umedesc AS produto,
            NULL AS parecer_gestor_a,
            indobservacao AS observacao_gestor_i,
            (
		SELECT dmi.dmiqtde
		FROM painel.detalhemetaindicador dmi
		    JOIN painel.detalheperiodicidade dpe ON(dmi.dpeid = dpe.dpeid AND dpestatus = 'A')
		    JOIN painel.metaindicador mi ON(mi.metid = dmi.metid AND mi.metstatus = 'A')
		WHERE
		    dmi.dmistatus = 'A'
		    -- Ano igual ou menor
		    AND dpe.dpeanoref::INTEGER <= TO_CHAR(NOW(), 'YYYY')::INTEGER
		    AND dpe.dpemesref::INTEGER <= TO_CHAR(NOW(), 'mm')::INTEGER
		    AND mi.indid = i.indid
		ORDER BY
			dpe.dpeanoref DESC,
			dpe.dpemesref DESC
		LIMIT 1
            )::INTEGER AS meta,
            (
                SELECT
                    MAX(seh.sehqtde)
                FROM painel.seriehistorica seh 
                    LEFT JOIN painel.detalheperiodicidade dpe ON dpe.dpeid = seh.dpeid 
                    LEFT JOIN painel.detalheseriehistorica dsh on seh.sehid = dsh.sehid
                WHERE
                    (
                        sehstatus='A'
                        OR
                        sehstatus='H'
                    )
                    AND seh.indid = i.indid
            )::INTEGER AS realizado,
            a.acaorcamento AS orcamento
        FROM painel.indicador i
            LEFT JOIN painel.unidademedicao unm ON unm.unmid = i.unmid
            LEFT JOIN painel.acao a ON a.acaid = i.acaid
            LEFT JOIN painel.secretaria s ON i.secid = s.secid
            LEFT JOIN painel.unidademeta ume ON i.umeid = ume.umeid
        WHERE
            i.indstatus = 'A'
        ORDER BY
            s.secordem ASC;
GRANT ALL ON TABLE relatorios.vw_relatorios_indicador TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE relatorios.vw_relatorios_indicador TO usr_simec;

**Comment by rafaeljcg20** [comment]
Demandante validou a demanda via mensagem.
Obs: Demanda duplicada na sprint 4
