### ISSUE TITLE
[email alterações de dotação] incluir a coluna titulo após o código de pi

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#74]

**Comment by Rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/e9c20726-3de2-4ac7-b5ce-b01b67a760a6)

**Comment by macavalheiro** [comment]
Funcionou Massa! 

Só gostaria de saber se é possível aumentar a largura da coluna título (pode dobrar), aumentar um pouco a coluna Unidade e centralizar tudo verticalmente

**Comment by Rafaeljcg20** [comment]
Oi @dougs007 , poderia verificar pra nós?

**Comment by dougs007** [comment]
Consegui formatar todas as colunas para centralizamento vertical e aumentei a largura da coluna  'Unidade', mas não foi possível aumentar a largura da coluna 'Título' por falta de espaço.

**Comment by Rafaeljcg20** [comment]
Ok. Testado.

**Comment by Rafaeljcg20** [comment]
Feito PR em master.

**Comment by Rafaeljcg20** [comment]
Publicada
