### ISSUE TITLE
[CORREÇÃO] Cadastro de usuário no sistema

### ISSUE THREAD

**Issue by leossb36** [culturagovbr/siminc2#741]
- [x] Na hora que salva a solicitação de cadastro definir como Default Orgao como sendo MINISTERIO DA CULTURA.

Demandante: Rafael José

**Comment by leossb36** [comment]
nome da branch:  hotfix-741-seguranca-cadastro-de-usuario-sistema

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/seguranca/seguranca.php?modulo=sistema/usuario/cadusuario&acao=A&usucpf=

**Comment by rafaeljcg20** [comment]
Validado no módulo SIS. @leossb36 arrumar também nas telas de gerenciar usuários de dentro dos módulos planejamento, monitoramento, proposta, emendas e alterações.
