### ISSUE TITLE
[MELHORIA]Docker Compose

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#750]
Terminar as configurações pra instalação do SISTEMA.

- [x] Subir o sistema usando o docker compose com o banco de dados (dump).

**Comment by rafaeljcg20** [comment]
Aguardando reunião com o Sr. Nitai dia 21/11/2018 e o Coordenador Marcus Menezes pra definir diretrizes para o desenvolvimento da demanda.

**Comment by dougs007** [comment]
Nome da branch:

docker-feature

**Comment by rafaeljcg20** [comment]
A pontuação dessa demanda foi redistribuída entre as sub-demandas:
* https://app.zenhub.com/workspaces/siminc2-5a974f9d25b7373ceb1e20d5/issues/culturagovbr/siminc2/789
* https://app.zenhub.com/workspaces/siminc2-5a974f9d25b7373ceb1e20d5/issues/culturagovbr/siminc2/785
* https://app.zenhub.com/workspaces/siminc2-5a974f9d25b7373ceb1e20d5/issues/culturagovbr/siminc2/784
* https://app.zenhub.com/workspaces/siminc2-5a974f9d25b7373ceb1e20d5/issues/culturagovbr/siminc2/788
* https://app.zenhub.com/workspaces/siminc2-5a974f9d25b7373ceb1e20d5/issues/culturagovbr/siminc2/786
* https://app.zenhub.com/workspaces/siminc2-5a974f9d25b7373ceb1e20d5/issues/culturagovbr/siminc2/787
