### ISSUE TITLE
[MELHORIA] Criar tela Vincular Inciativas PPA

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#76]
- [x] Criar nova tela pra vincular iniciativas PPA, conforme a tela de vincular Metas PPA;
 - [x] Fazer manutenção na tela de Cadastro de PI para que ao selecionar Subunidade e Objetivo, o sistema restrinja as opções de Iniciativas PPA conforme o Objetivo e a Subunidade selecionada;
 - [x] Fazer manutenção na tela de <b>Cadastro de PI FNC</b> para que ao selecionar Subunidade e Objetivo, o sistema restrinja as opções de Iniciativas PPA conforme o Objetivo e a Subunidade selecionada.
 - [x] Remover link Apoio -> PPA -> Meta

Observação:
Regra 1: Na tela de <b>Cadastro de PI e Cadastro de PI FNC</b> o sistema só poderá exibir as iniciativas e metas associadas ao Objetivo selecionado e que estiverem associadas a Subunidade Selecionada <b>ou que estejam associadas ao Objetivo selecionado e que não tenham nenhuma associação com Subunidade</b>.

**Comment by rafaelfcar** [comment]
teste

**Comment by macavalheiro** [comment]
caros, 
tentei vincular 2 inciativas 05VX e 05VW (ambas do objetivo 0786) a duas unidades, mas qdo fui procurar atraves da tela de cadastro pi, não  apareceram as respectivas iniciativas na unidades que vinculei.

**Comment by rafaeljcg20** [comment]
Obrigado @macavalheiro por nos avisar. Vamos corrigir.

**Comment by rafaelfcar** [comment]
Consulta alterada.

**Comment by rafaelfcar** [comment]
Leo, favor testar novamente.

**Comment by leossb36** [comment]
Testado em homologação na tela de cadastro de pi e pi fnc.
Rotina seguida:
###### Registrando Iniciativa:
* Apoio > PPA > 0786 > registrar iniciativa em Iniciativas
###### Vinculando Iniciativa:
* Configuração > Vincular Iniciativa PPA > fazer vinculo da iniciativa PPA com as unidades que desejar
###### Realizando Cadastro Pi ou Pi FNC
* Principal > Cadastro Pi ou Cadastro Pi FNC 
Realizando os vínculos desejados e está sendo utilizado corretamente na hora do cadastro.

**Comment by macavalheiro** [comment]
Caros, Vinculei a inciativa 05VT outra unidade (portanto deveria aparecer só para essa unidade) entrei na ancine e procurei ela dentro do objetivo dela (0786) e ela estava lá.

**Comment by rafaeljcg20** [comment]
![Cadastro de Objetivo-Iniciativas.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/3fc445b6-8aa9-4caa-b86b-19b0bc2f60a4)

Oi @rafaelfcar, por favor, retirar a opção 'Ano' tanto do formulário de Cadastro de Meta PPA quanto da lista.
Obs:
* O sistema deve acrescentar o ano da sessão automaticamente ao acionar a opção 'Salvar'.
* Na lista o sistema deve listar apenas as Metas do ano selecionado no módulo também atribuído na sessão.

**Comment by rafaeljcg20** [comment]
Oi @rafaelfcar, também vamos padronizar a forma de utilização do campo nome e descrição das metas. Analise cada lugar onde está sendo usado mppdsc e substitua pra mppnome levando em consideração o esforço e impacto da mudança no sistema para tomar a decisão de alterar ou não. 

Obs:
Vamos combinar de usar sempre mppnome em primeiro lugar em todos os lugares do sistema e caso haja necessidade ou solicitação dos demandantes, utilizaremos o mppdsc considerando que a descrição poderá ter maior quantidade de texto que o nome na hora da exibição dos dados alterando o visual das telas.

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A
