### ISSUE TITLE
[MELHORIA]Gráfico de Acompanhamento de Metas dos Indicadores

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#763]
Na tela de Metas do Indicador, mudar o comportamento do gráfico para ser possível visualizar todos os meses do ano mesmo que não tenha lançamentos da meta ou do indicador e mudar o estilo do gráfico para Barras.

**Comment by dougs007** [comment]
Demanda fechada.
Motivo: Módulo Descontinuado
