### ISSUE TITLE
[MELHORIA]Avaliação do Gestor-Mês

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#766]
Na tela de Avaliação do Gestor, o sistema deve salvar os dados por mês.
Sugestão: Colocar opção Mês.Inserir combo com opção de selecionar o mês.

**Comment by rafaelfcar** [comment]
branch:
hotfix-766-gestao-avaliacao-gestor

**Comment by dougs007** [comment]
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/f0e8cac4-095a-4476-a437-b1e174e5c766)

Ao realizar o teste, foi encontrado a seguinte divergência na tela de Avaliação do Gestor

- [ ] Não permitir avaliar mais de uma vez no mesmo mês e do mesmo ano.

**Comment by rafaeljcg20** [comment]
Demandante solicitou fechar a demanda e pulicar.
