### ISSUE TITLE
[MELHORIA]Relatório-Indicadores por Secretarias por Mês

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#767]
No Relatório Indicadores por Secretarias, inserir a opção para seleção de Mês. Ao selecionar o mês o sistema deverá exibir a consulta sob a perspectiva do mês selecionado para os valores das colunas Previsto, Realizado e Observações.

**Comment by rafaelfcar** [comment]
branch:
hotfix-767-gestao-relatorio-indicadores

**Comment by rafaeljcg20** [comment]
Demanda publicada antecipadamente após o teste da Ti pelo fato de ser urgente.
