### ISSUE TITLE
[MELHORIA]Cadastro de Indicadores-Produto

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#768]
Na tela Cadastro de Indicadores no formulário de cadastro, inserir a opção Produto sendo um campo descritivo de texto pequeno(70 caracteres) e obrigatório.

- [x] Inserir o valor desse novo campo no Relatório de Indicadores por Secretarias na coluna Produto.
- [x] Inserir coluna Produto no portal do Gestao Estratégica (Manutenção nas views)

**Comment by dougs007** [comment]
Nome da branch :

hotfix-768-gestao-indicadores
