### ISSUE TITLE
[CORREÇÃO]Cadastro de Indicadores-Navegação de Abas

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#769]
Na tela de Cadastro de Indicadores, fazer correção na exibição das abas de navegação que estão sumindo, tendo comportamento estranho direcionando pra telas erradas e mudando os nomes.

**Comment by rafaelfcar** [comment]
branch:
hotfix-769-gestao-navegacao-abas

scripts:
insert into seguranca.aba_menu (mnuid, abacod) values (7297,57105);
insert into seguranca.aba_menu (mnuid, abacod) values (7298,57105);
insert into seguranca.aba_menu (mnuid, abacod) values (7300,57105);
insert into seguranca.aba_menu (mnuid, abacod) values (4907,57105);

insert into seguranca.aba_menu (mnuid, abacod) values (7302,57279);
insert into seguranca.aba_menu (mnuid, abacod) values (7300,57279);
insert into seguranca.aba_menu (mnuid, abacod) values (4907,57279);

delete from seguranca.aba_menu where mnuid = 4741 and abacod = 57279;
delete from seguranca.aba_menu where mnuid = 4741 and abacod = 57105;
delete from seguranca.aba_menu where abacod = 57108;
insert into seguranca.aba_menu (mnuid, abacod)
select mnuid, 57108 from seguranca.aba_menu where abacod= 57105;

**Comment by dougs007** [comment]
Testado em homologação:


http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/lista&acao=A
