### ISSUE TITLE
[MELHORIA]Cadastro de Indicadores-Peso

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#770]
Na tela de Cadastro de Indicadores, inserir opção Peso com restrição de preenchimento obrigatório e do tipo numérico.

**Comment by dougs007** [comment]
Nome da branch : 

hotfix-770-gestao-indicadores-peso

**Comment by dougs007** [comment]
Script para ser executado em produção:

ALTER TABLE painel.indicador ADD COLUMN indpeso integer default 0;
ALTER TABLE painel.indicador ALTER COLUMN indpeso SET NOT NULL;
COMMENT ON COLUMN painel.indicador.indpeso IS 'Peso';

**Comment by rafaelfcar** [comment]
Testado em Homologação:
http://homologasiminc2.cultura.gov.br/painel/painel.php?modulo=principal/cadastro&acao=A&indid=3350&evento=A
