### ISSUE TITLE
[MELHORIA]Relatório-Indicadores por Secretarias-Índice e Gráfico

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#771]
No relatório Indicadores por Secretarias acrescentar as seguintes informações:
- [ ] Inserir calculo de peso para gerar os valores de Realizado, Previsto considerando o mês.
- [ ] Inserir um índice geral por secretaria calculando a partir do peso do indicador.
- [ ] Quando o relatório for por secretaria exibir um gráfico de desempenho da secretaria selecionada.
- [ ] Quando o relatório for geral exibir um gráfico de desempenho do MinC considerando os índices gerais de todas as secretarias.

**Comment by dougs007** [comment]
Demanda fechada.
Motivo: Módulo Descontinuado
