### ISSUE TITLE
Erro - caracteres

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#777]
Módulo Planejamento Orçamentário: alguns caracteres estão saindo com erro, tanto nas telas do Siminc quanto nos relatórios excel.

![Erro caracteres Siminc2.jpg](https://images.zenhubusercontent.com/5aa81f454b5806bc2bcab2bc/02a6764d-8f23-4f31-88be-9bf6dc825f53)

**Comment by JoelSSilva** [comment]
O problema em tela já havia sido relatado em outros issues, e a sua resolução já foi efetuada, portanto este issue será fechado.

**Comment by rafaeljcg20** [comment]
Demanda resolvida na issue abaixo: https://app.zenhub.com/workspaces/siminc2-5a974f9d25b7373ceb1e20d5/issues/culturagovbr/siminc2/751
