### ISSUE TITLE
[MELHORIA]Painel de Acompanhamento-Gráficos

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#78]
Verificar os dados que temos do SIOP são suficientes para desenvolvermos uma tela que mostre com gráfico de barras os valores por exemplo de empenhado mês à mês.

Obs: Se for possível e tivermos dados suficientes pra fazermos as consultas, deveremos cadastrar uma nova demanda pra desenvolver uma nova tela modal para cada uma das barras(Provisionado, Empenhado, liquidado e pago) dos gráficos de Valores por Unidades da tela do Painel de acompanhamento.

**Comment by rafaelfcar** [comment]
Após a análise foi identificado que existe outro método no webservice do SIOP que retorna a execução orçamentária por mês. Sendo assim, para executar a solicitação, serão necessários os seguintes passos:
* Modelar o banco para receber esses dados mensais;
* Alterar a rotina de atualização de dados do SIOP, incluindo essa atualização também;
