### ISSUE TITLE
[MELHORIA]Docker Compose-BD Planejamento Orçamentário

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#784]
- [x] Remover os dados das tabelas do banco do módulo Planejamento no dump para rodar o docker compose.

Obs: Informações de valores.

**Comment by dougs007** [comment]
Nome da branch:

docker-feature

**Comment by leossb36** [comment]
Testado em banco local.
Todas as informações, de importancia, das telas principais e relatorios foram varridas com sucesso!
