### ISSUE TITLE
[MELHORIA]Docker Compose-BD Emendas

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#785]
- [x] Remover os dados das tabelas do banco do módulo Emendas no dump para rodar o docker compose.

Obs: Informações de valores.

**Comment by dougs007** [comment]
Nome da branch:

docker-feature

**Comment by leossb36** [comment]
Testado em banco local.
Todas as telas principais, relatorio e dados importantes foram varridas com sucesso!
