### ISSUE TITLE
[MELHORIA]Docker Compose-BD Monitoramento

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#787]
- [ ] Remover os dados das tabelas do banco do módulo Monitoramento no dump para rodar o docker compose.

Obs: Informações de valores.

**Comment by dougs007** [comment]
Nome da branch:

docker-feature

**Comment by leossb36** [comment]
Testado em banco local.
Todos os dados importantes, relatorios e telas principais foram varridos com sucesso!
@rafaeljcg20 

apenas um caso a resolver
- [ ] limpar metas pnc
![Captura de tela de 2018-12-07 10-36-56.png](https://images.zenhubusercontent.com/59f463e48a75884b908527c3/8240e2f2-656b-44fa-8e7f-125fb35632c2)
