### ISSUE TITLE
[MELHORIA]Docker Compose-BD Gestão Estratégica

### ISSUE THREAD

**Issue by dougs007** [culturagovbr/siminc2#788]
- [x] Remover os dados das tabelas do banco do módulo Gestão Estratégica no dump para rodar o docker compose.

Obs: Informações de valores.

**Comment by dougs007** [comment]
Nome da branch:

hotfix-sql-tabelas-dominio

**Comment by leossb36** [comment]
Testado em banco local.
Todas as informações foram varridas com sucesso!
