### ISSUE TITLE
[MELHORIA] Melhorias no Cadastro de PI

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#79]
Na tela Cadastro de PI e Cadastro de PI FNC:
 - [x] Inserir restrição de 11 dígitos para o campo de Código de PI;
 - [x] Inserir regra para o sistema não permitir salvar novo código de PI que já esteja sendo utilizado em outro projeto/Plano Interno;
 - [x] Ao salvar o novo código de PI, gravar na base de dados a informação do usuário que alterou o código, data de alteração, Código de PI Anterior e Código de PI novo;
 - [x] Criar um ícone com o nome "Histórico de alterações do Código do PI" na frente do campo Código de PI;
 - [x] Criar funcionalidade para que ao clicar no ícone de histórico, exibir uma nova tela modal com a lista de usuários que alteraram o código do PI. A lista deve conter as seguintes colunas: Data, Usuário, Código Anterior, e Código Novo;

Dica de implementação da solução:
* Funcionalidade semelhante ao componente no campo de monitoramento do projeto: http://local.siminc2/acompanhamento/acompanhamento.php?modulo=principal/monitorar-pi&acao=A&pliid=10079

**Comment by dougs007** [comment]
Nome da branch : hotfix-79-planejamento-melhorias-pi

**Comment by rafaelfcar** [comment]
testado em ambiente de homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10000

**Comment by macavalheiro** [comment]
excelente. ficou muito bom
