### ISSUE TITLE
[CORREÇÃO]WEB SERVICE SIOP-Atualizar Dotações FNC

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#793]
Verificar a possibilidade e se possível implementar a funcionalidade de atualizar automaticamente de acordo com o SIOP as dotações das funcionais do Fundo Nacional de Cultura(FNC).

Demandante: Sr. Joel-SPOA( @JoelSSilva )

**Comment by rafaeljcg20** [comment]
Branch: hotfix-793-planejamento-ws-dotacao-fnc

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C

**Comment by rafaeljcg20** [comment]
Demanda publicada pela dificuldade de reproduzir no ambiente de homologação.
Impeditivos: Envio de emails e dados externos.

**Comment by macavalheiro** [comment]
massa, rafa! só o empenhando, liquidado e pago do fnc q não está puxando ainda. isso seria um outra demanda?
