### ISSUE TITLE
[MELHORIA] Criar tela para Documentos importantes

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#80]
nome do menu: Anexos

- [x] Criar tela geral de documentos importantes (para fazer upload e deixar disponíveis arquivos como manual do sistema, portarias, instruções, etc)

**Comment by rafaeljcg20** [comment]
nome: anexos

**Comment by dougs007** [comment]
Nome da Branch : hotfix-80-upload-arquivos

**Comment by leossb36** [comment]
testada em homologação: 
http://homologasiminc2.cultura.gov.br/proposta/proposta.php?modulo=inicio&acao=C

**Comment by macavalheiro** [comment]
só faltou trocar o nome do "botão" de "visualizar regras"  para "anexos" conforme comentando anteriormente. 

Obrigado!

**Comment by rafaelfcar** [comment]
Nome do Botão alterado.

**Comment by rafaelfcar** [comment]
Leo, favor testar novamente.

**Comment by rafaelfcar** [comment]
Branch: hotfix-validacao-perfil-upload-arquivos
