### ISSUE TITLE
[CORREÇÃO]Rotina Diária-Email Alterações de Dotação

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#802]
No e-mail de Alterações de Dotação, na lista "Valor sem PI por Funcional" corrigir a duplicação de funcionais conforme a imagem em anexo.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/62ce4392-f737-4dcd-b5f0-548186c98cf0)

Dica: Tela pra conferência dos valores acessada a partir do menu Principal -> Painel -> Clicar sobre Qualquer Funcional:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/50cb3db0-7aa1-4112-9848-e90a8e60f3aa)

**Comment by rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/50cb3db0-7aa1-4112-9848-e90a8e60f3aa)

**Comment by rafaeljcg20** [comment]
Foi recebida ligação telefônica e a demanda ficou combinada para o dia 26/12/2018

**Comment by rafaeljcg20** [comment]
Branch: hotfix-802-planejamento-rotina-diaria

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C
