### ISSUE TITLE
[CORREÇÃO]Gerar PI

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#803]
No módulo Emendas, tela Cadastro de Beneficiários, delega-se a execução a uma unidade. Depois, ao salvar os dados na aba Cadastro Complementar do PI e Gerar PI, duas coisas acontecem:
1 - a delegação cai e a unidade à qual foi delegada não consegue mais enxergar o PI;
2 - o título do projeto some (campo fica em branco).

Como exemplos do relatado acima, os IDs Beneficiário 8700 e 8581 (já foram corrigidos manualmente).

Demandante: Joel-SPOA

**Comment by leossb36** [comment]
branch: hotfix-803-emendas-gerar-pi

**Comment by leossb36** [comment]
boa tarde @JoelSSilva e @rafaeljcg20,
Foi verificado e simulado a ocorrência dos fatos. O segundo tópico foi resolvido com sucesso.
Quanto ao tratamento do primeiro tópico, após análise do código com @rafaelfcar chegamos a uma conclusão que tentarei exemplifica-la para um melhor entendimento:

O comportamento da delegação, e também todo e qualquer dado inserido na **primeira aba**, será exclusivamente do **formulário da primeira aba**(Cadastro inicial), inclusive o botão de salvar.
Assim também irá seguir a mesma regra para a **segunda aba**(Cadastro complementar do PI).

Um exemplo para esta situação:

formulário 1:
titulo
botão de salvar

formulario 2:
titulo
botão de salvar

Desta forma, pode-se observar que existem dois botões de salvar, ambos apresentam o mesmo comportamento, **porém** para escopos diferentes. Então, conclusão, **Não é possivel** salvar dados da aba de **formulario 1** através do **botão de salvar** do **formulario 2** e assim vice e versa.

Espero ter esclarecido, qualquer coisa se não estiver claro, tentarei novamente.
Obrigado pela atenção.
:)

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8422&aba=1
