### ISSUE TITLE
[CORREÇÃO]Pedido de Alteração-Ajustes

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#805]
Durante o desenvolvimento do módulo Alterações Orçamentárias, foi sugerido as seguintes correções e ou ajustes durante a reunião de planejamento de segunda-feira(03/12/2018):
- [x] Na aba inicial de cadastro de pedido, a opção Unidade deverá ser de múltipla opção(Permitir selecionar várias Unidades);
- [x] Na aba de selecionar PI, o sistema deverá permitir selecionar apenas os PIs das Unidades selecionadas;
- [x] Na aba de Remanejamento Loa, o sistema deverá permitir selecionar qualquer funcional do ano do exercício atual e Unidade(Subunidade) administrada pelo módulo Planejamento Orçamentário.
###### Dica(usar consulta Relatório de Funcionais) http://treinamentosiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=relatorio/funcionais&acao=A
- [x] Na aba de Remanejamento Loa, a opção Categoria só poderá exibir as opções 3 e 4;
- [x] Na aba de Remanejamento Loa, Trocar o nome da coluna de Modalidade para Modalidade de Aplicação(obs: estudar uma forma de abreviação pra não ocupar muito espaço, porém deixar claro o nome da coluna, ex: colocando Títulos(tooltip));
- [x] Na tela Cadastro de PI e Cadastro de PI FNC, trocar a palavra do texto de aviso de alteração orçamentária de Corrija para Adeque-os.

**Comment by rafaeljcg20** [comment]
<b>Resultado parcial de testes:</b>
* Na aba de selecionar PI, ao ter sido selecionado CGCON, o sistema exibe 241 PIs enquanto que no módulo planejamento ao filtrar por CGCON o sistema exibe 23 PIs
* Na aba de Remanejamento LOA, ao ter sido selecionado CGCON, o sistema está exibindo várias funcionais enquanto que no relatório de Funcionais só existe uma funcional associada a Unidade CGCON.

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=principal/cadastro_alteracoes&acao=C&pedid=3&tpdid=269
