### ISSUE TITLE
[Limite Subunidade] Atualizar o valor total da dotação da Subunidade ao digitar e não somente ao recarregar a página.

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#81]

**Comment by rafaelfcar** [comment]
branch: hotfix-81-planejamento-correcao-totais

**Comment by leossb36** [comment]
testado em homolagação: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/unidadegestora-limite&acao=A
