### ISSUE TITLE
[MELHORIA]Inserir Exercício-Anualizar as principais informações

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#823]
Inserir a opção de exercício no módulo Gestão Estratégia, conforme acontece nos outros módulos do sistema onde a opção de exercício fica sempre acessível no cabeçalho das páginas.

Informações mapeadas até o momento que deverão ser anualizadas:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/d0d42169-dd54-474d-b6f1-468eba1392a0)
- [x] Ações Estratégicas;
- [x] Secretarias;
- [x] Objetivos Estratégicos;
- [x] Metas PNC;
- [x] Metas PPA;
- [x] Subações;

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/12a647cd-06d3-461f-9335-b483c52b7c71)

- [x] Indicadores;
- [x] Serie Histórica;
- [x] Metas do Indicador;
- [x] Legendas;
- [x] Avaliação do Gestor.

**Comment by rafaelfcar** [comment]
branch: 
hotfix-823-gestao-exercicio
script:
CREATE TABLE painel.programacaoexercicio (
prsano CHARACTER(4) NOT NULL, 
prsdata_inicial DATE, 
prsdata_termino DATE, 
prsexerccorrente BOOLEAN DEFAULT false, 
prsstatus CHARACTER(1) DEFAULT 'A'::bpchar, 
prsativo SMALLINT DEFAULT 1, 
prsexercicioaberto BOOLEAN DEFAULT true, 
CONSTRAINT pk_programacaosimec PRIMARY KEY (prsano)
);
ALTER TABLE painel.programacaoexercicio OWNER TO postgres;
GRANT ALL ON TABLE painel.programacaoexercicio TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE painel.programacaoexercicio TO usr_simec;

insert into painel.programacaoexercicio
SELECT * FROM planacomorc.programacaoexercicio;

alter table painel.indicador add column indano varchar(4) default to_char(CURRENT_DATE, 'yyyy');

**Comment by leossb36** [comment]
testado em homologação
