### ISSUE TITLE
[MELHORIA]Avaliação do Gestor-Aumentar quantidade de texto

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#828]
Na tela Avaliação do Gestor, aumentar a quantidade máxima de letras da opção Observação do Gestor de 125 para 255.

**Comment by dougs007** [comment]
- [ ] Script para ser executado em produção.

ALTER TABLE painel.avaliacao_gestor ALTER COLUMN indobsgestor TYPE character varying(255);
