### ISSUE TITLE
[CORREÇÃO]Painel de Acompanhamento-Sinalização de Cores

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#835]
Na tela Painel e Painel FNC, o sistema parou de sinalizar através de cores os valores da parte 
Acompanhamento de Plano Interno.
- [x] Alterar o Titulo da Lista de "Acompanhamento de Plano Interno" para "Acompanhamento de Funcionais".

Demandante: Marcelo

**Comment by rafaeljcg20** [comment]
Branch: hotfix-835-planejamento-painel

**Comment by dougs007** [comment]
Testado em homologação: 

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C
