### ISSUE TITLE
[CORREÇÃO]Cadastro de Classificação-Funcionalidade de Excluir e Salvar Medidas

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#837]
Na tela de cadastro de Classificação, ao tentar salvar uma medida com acentuação o sistema insere caracteres ilegíveis, e ao tentar excluir uma medida que está sendo utilizada o sistema não permite a exclusão.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/7882053d-44d1-48ba-afa7-0a2ff28ea4fe)

Demandante: Marcelo

**Comment by dougs007** [comment]
Nome da branch :


hotfix-837-monitoramento-classificacao

**Comment by rafaelfcar** [comment]
testado em hmg:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=apoio/classificacao&acao=A

**Comment by macavalheiro** [comment]
![image.png](https://images.zenhubusercontent.com/5aa819f64b5806bc2bcab1c5/f1974c65-84df-408b-9f50-7e53375b3e42)

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro , é porque a correção que o pessoal fez só vai ser efetiva para os dados que forem salvos e alterados de agora em diante, mas pedi pra o @leossb36 arrumar manualmente editando essas medidas que já foram salvas trocando as letras ilegíveis pelas letras legíveis.

**Comment by rafaeljcg20** [comment]
Ajustes finalizados.

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/276fe524-d69f-437b-b6f2-a00990fb7cd5)
