### ISSUE TITLE
[MELHORIA]Monitorar PPA-Informações de Uso

### ISSUE THREAD

**Issue by JoelSSilva** [culturagovbr/siminc2#838]
Na tela de Monitorar PPA, realizar os seguintes ajustes:

- [x] Alterar o nome da opção de Executado para Quantidade Alcançada; 
- [x] incluir caixa com texto ao posicionar o cursor na opção Quantidade Alcançada: "Valor apurado para a meta considerando sua respectiva unidade de medida, cumulativo desde o início do PPA".
- [x] Na opção Análise Situacional, incluir caixa com texto ao posicionar o cursor no campo: "Avaliação da execução da meta, quantificando, sempre que possível, o valor alcançado acumulado para o período do Plano, destacando-se, em especial, o executado no ano corrente e a projeção para o ano seguinte, o motivo da frustração ou da superação da expectativa, as necessidades existentes para que a meta seja atendida, e/ou outras informações pactuadas."
- [x] Alterar o nome da opção Classificação para Classificação da Meta;
- [x] Na opção Classificação da Meta, incluir caixa com texto ao posicionar o cursor no campo: "Classificação da meta quanto ao seu andamento."

Seguem os ajustes originais em anexo.
[https://app.zenhub.com/files/114924704/afe4cd80-801d-4799-bac2-f34f700eebda/download](https://app.zenhub.com/files/114924704/afe4cd80-801d-4799-bac2-f34f700eebda/download)

Demandante: Joel

**Comment by dougs007** [comment]
Nome da branch :

hotfix-838-monitoramento-ppa

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=principal/monitorar-ppa&acao=A&acoid=7

**Comment by rafaeljcg20** [comment]
Considerando a urgência informada pelo demandante a demanda foi publicada antecipadamente.
