### ISSUE TITLE
[CORREÇÃO]Monitorar PPA-Inserir Anexos

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#845]
Na tela de Monitorar PPA, ao usar o recurso de anexar arquivo o sistema informa que o arquivo foi anexado porém o mesmo não aparece na lista do formulário conforme a imagem abaixo enviada pelo usuário:

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/61d20b08-6c1a-41ed-983a-1a8ee4a91495)

Demandante: Marcelo

**Comment by dougs007** [comment]
Nome da branch :

hotfix-845-monitoramento-monitorar-ppa

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=principal/monitorar-ppa&acao=A&acoid=16

**Comment by rafaeljcg20** [comment]
Demanda publicada antecipadamente por ocasião de urgência informada pelo Demandante.
