### ISSUE TITLE
[MELHORIA]Cadastro de Pedidos-Botão Enviar

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#850]
Na tela de Cadastro de Pedidos, permitir que o botão "Enviar" seja visualizado quando o pedido estiver em situação de "Aguardando Correção" tanto do fluxo Interno quanto Externo e que quando acionado mude a situação para o próximo estado.

**Comment by rafaelfcar** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=principal/cadastro_alteracoes&acao=C&pedid=4&tpdid=270
