### ISSUE TITLE
[CORREÇÃO]Cadastro de Pedido-Restrição de Edição por Estado

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#852]
Na tela de Cadastro de Pedido, só permitir que os dados do pedido sejam modificados ou inseridos quando o mesmo estiver na situação de "Em cadastramento" ou "Aguardando Correção" tanto do fluxo Interno quanto Externo.

**Comment by dougs007** [comment]
Branch: 

feature-alteracoes

**Comment by rafaeljcg20** [comment]
O Sistema está duplicando os PIs após clicar no check para inserir o PI pra realizar a alteração na aba "Selecionar PI"

**Comment by dougs007** [comment]
Corrigido!

**Comment by rafaelfcar** [comment]
Testado em HMG:
http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=principal/cadastro_alteracoes&acao=C&pedid=49&tpdid=269
