### ISSUE TITLE
[MELHORIA]Aviso de Alteração no Cronograma

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#856]
Na tela de Cadastro de PI e Cadastro de PI FNC, retirar o aviso de que o usuário deve ajustar os valores do cronograma em decorrência de pedido de alteração orçamentária, <b>quando</b> os valores totais do cronograma forem iguais os valores(Novo valor Custeio, Capital e Físico após a Efetivação do pedido de alteração orçamentária.) atualizados do PI.

**Comment by leossb36** [comment]
branch: feature-alteracoes

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10001

**Comment by macavalheiro** [comment]
ajustei os cronogramas mas o avisou não saiu

**Comment by rafaeljcg20** [comment]
Obrigado Marcelo( @macavalheiro ) por nos avisar. Vou providenciar a correção.

**Comment by rafaeljcg20** [comment]
Corrigido.

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=10002
