### ISSUE TITLE
[MELHORIA] Criar nova tela Segmento Cultural

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#87]
Na tela de Cadastrar Área Cultural, inserir um CRUD para cadastrar os Segmentos Culturais no módulo Planejamento Orçamentário, utilizando como exemplo a tela de Cadastro de Autor no Módulo Emendas.

**Comment by dougs007** [comment]
Nome da Branch :  hotfix-87-planejamento-segmento-cultural

**Comment by rafaeljcg20** [comment]
@dougs007, obrigado! Excelente passo a passo pra documentar particularidades durante a etapa de publicação da demanda.

**Comment by rafaelfcar** [comment]
[] Ao salvar um novo segmento de uma nova área, quando digitamos o código o sistema salva com outro código.

**Comment by leossb36** [comment]
testada em homologação: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/area_cultural&acao=A
