### ISSUE TITLE
funcionais que não estamos conseguindo excluir nem tirar da SAV

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#871]
![212h.png](https://images.zenhubusercontent.com/5aa819f64b5806bc2bcab1c5/694ce64e-087d-48df-9dda-0a47d9712720)

**Comment by rafaelfcar** [comment]
branch:
hotfix-871-planejamento-funcionais

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C#
