### ISSUE TITLE
[CORREÇÃO]Relatório Proposta-Subunidades

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#877]
Ao acessar o menu Relatórios -> Relatório de Propostas utilizando um usuário com o perfil de Subunidade que tenha várias Unidades vinculadas, o sistema exibi um erro.

Erro monitorado por e-mail:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/34f89a29-130c-4801-b389-81699735a79f)

Demandante: Rafael J

**Comment by leossb36** [comment]
testado em homologação:
- nome da unidade: ademilton
