### ISSUE TITLE
Publicar módulo em produção

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#880]

**Comment by rafaeljcg20** [comment]
Branch: features-alteracoes

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/alteracao/alteracao.php?modulo=inicio&acao=C

**Comment by rafaeljcg20** [comment]
@dougs007 , Por favor, durante a publicação, verificar a correção nos menus que foram indentificados na fase de deploy de homologação e conferir se as constantes geradas estão de acordo com a simulação de publicação realizada semana passada no ambiente de homologação.

**Comment by dougs007** [comment]
Observações para a publicação.

Para o usuário Unidade, mostra-se apenas o menu de relatório. Segue imagem abaixo;

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/103f374f-76b9-41ec-ac69-46eb10923703)

- [ ] Corrigir o menu para o perfil Unidade.


Para o perfil Administrador, mostra-se todos os menus, exceto o principal.
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/a9137234-20a5-4734-8da3-937d59e35ea3)

- [ ] Corrigir os menus para o perfil administrador.
