### ISSUE TITLE
[MELHORIA]Exercício

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#886]
Após autenticar no sistema, ao entrar no módulo Planejamento Orçamentário, fazer com que o exercício 2019 seja o ano inicial(padrão/default) do sistema.

Demandante: Marcelo

**Comment by dougs007** [comment]
Nome da branch :

hotfix-886-planejamento-exercicio

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C
