### ISSUE TITLE
[CORREÇÃO]Painel de Acompanhamento - Limite

### ISSUE THREAD

**Issue by HenriqueOliveiradosAnjos** [culturagovbr/siminc2#887]
- A unidade SADI, que não existe na estrutura do orgão em 2019, está aparecendo no gráfico e ainda tem valor de limite.

- [x] Verificar se ao excluir a Unidade nas telas de Apoio o sistema não exibi a Unidade na tela Painel de Acompanhamento;
- [x] Verificar se ao excluir a Unidade nas telas de Apoio o sistema não exibi a Unidade na Tela de Limites.

**Comment by dougs007** [comment]
Nome da branch :

hotfix-887-planejamento-grafico-inicio

**Comment by dougs007** [comment]
- [  ] Script para publicação após teste.

# Registro do valor que mostra no gráfico.
select * from public.vw_subunidadeorcamentaria where suocod = '420032'

update planacomorc.unidadegestora_limite set lmustatus = 'I' where lmuid = 119

**Comment by dougs007** [comment]
Testado em ambiente de Homologação após trocar para a base de treinamento !

**Comment by macavalheiro** [comment]
em homologação continua aparecendo a sadi no gráfico

**Comment by leossb36** [comment]
Oi @macavalheiro, ja fizemos a correção e já está funcionando em homologação

**Comment by rafaeljcg20** [comment]
Oi @macavalheiro e @JoelSSilva , agora que concluímos as correções o sistema não exibe mais o valor errado pra SADI, mas pra tirar a SADI do gráfico das diretas é necessário acessar a tela Apoio -> Unidade/Subunidade e excluir a SADI da UO Ministério da Cultura.
