### ISSUE TITLE
[MELHORIA]Documentação Módulo Planejamento Orçamentário-Caso de Uso

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#889]
Redigir e publicar caso de uso das principais funcionalidades do módulo Planejamento Orçamentário.

Demandantes: Sr. Ayrton Martinello, Sr. Lindberg, Sr. Marcelo

**Comment by dougs007** [comment]
3 documentos:

[UC01] Listar PI
[UC02] Cadastrar PI
[UC03] Tramitar PI

**Comment by leossb36** [comment]
Planejamento orçamentario:
- [ ] UC001-planejamento orçamentario - regra de negocio para filtro
- [ ] UC001-planejamento orçamentario - pontos de relacionamento
- [ ] UC001-planejamento orçamentario - diagrama de classe

**Comment by rafaeljcg20** [comment]
Boa tarde Pessoal, por favor colocar todas as observações nas tabelas abaixo dos protótipos:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/4ca8fb11-f442-4cf2-8150-bba1baaed8bf)

**Comment by dougs007** [comment]
### Atividades a serem feitas

> Legendas
- [ ] Não feitas
- [x] Feitas 

> Tarefas
<br/>

- [ ] Conferir e verificar o Indíce Analítico (Sumário) do UC001
- [ ] [UC001] Cadastar PI
- [ ] [UC002] Listar PI
- [ ] [UC003] Tramitar PI
- [ ] [UC004] Excluir PI

**Comment by dougs007** [comment]
Pegar quadro do cadastar PI e adicionar no caso de uso 1 no espelho de PI

**Comment by macavalheiro** [comment]
ótimo! só colocar o box "pedido de financeiro" ao lado do box "nota de empenho, para não ficar com "buracos na tela", se for possível!
