### ISSUE TITLE
Testar Funcionalidade da API

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#89]
1-Configurar o config.ini do Zend
2-Logar no sistema
3-Verificar se os dados da tela principal do Planejamento continuam sendo carregados corretamente.

**Comment by macavalheiro** [comment]
o q é isso?

**Comment by rafaeljcg20** [comment]
Demanda será fechada, porque provavelmente era uma anotação pra balizar uma tarefa de desenvolvimento(Provavelmente uma atividade de teste pra avaliar impacto de alguma manutenção no sistema).
