### ISSUE TITLE
[MELHORIA]Documentação Módulo Emendas Parlamentares-Caso de Uso

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#891]
Redigir e publicar caso de uso das principais funcionalidades do módulo Emendas Parlamentares.

Demandantes: Sr. Ayrton Martinello, Sr. Lindberg, Sr. Marcelo

**Comment by dougs007** [comment]
### Atividades a serem feitas

> Legendas
- [ ] Não feitas
- [x] Feitas 

> Tarefas
<br/>

- [ ] [UC001] Listar Emenda
- [ ] [UC002] Cadastar Emenda
- [ ] [UC003] Tramitar Emenda
- [ ] [UC004] Excluir Emenda

**Comment by leossb36** [comment]
Oi @rafaeljcg20,
Todos os documentos foram revisados conforme o padrão estipulado.
