### ISSUE TITLE
[MELHORIA]Documentação Módulo Alterações Orçamentárias-Caso de Uso

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#893]
Redigir e publicar caso de uso das principais funcionalidades do módulo Alterações Orçamentárias.

Demandantes: Sr. Ayrton Martinello, Sr. Lindberg, Sr. Marcelo

**Comment by dougs007** [comment]
Boa Tarde Senhores! @rafaelfcar, @rafaeljcg20 

Ao documentar o módulo, me veio a seguinte dúvida.

Em um fluxo normal de Cadastros de Pedidos de Alteração, em todos os Pedidos as Unidades devem preencher dados Loa ?? Segue imagem abaixo.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/6e799905-c69b-4258-bb85-86249f7e769b)

**Comment by rafaeljcg20** [comment]
Demanda despriorizada pra atender a demanda de Elaboração de Caso de Uso do módulo Planejamento Orçamentário.

**Comment by rafaeljcg20** [comment]
Essa demanda será encerrada porque o módulo aparentemente não será utilizado por enquanto.
