### ISSUE TITLE
[MELHORIA]Carga de PTRES e RP

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#894]
carga de ptres e RP nas funcionais, conforme planilha anexa

**Comment by macavalheiro** [comment]
[https://app.zenhub.com/files/114924704/ea0009d0-d22d-4100-b413-7e9c50d4d741/download](https://app.zenhub.com/files/114924704/ea0009d0-d22d-4100-b413-7e9c50d4d741/download)

**Comment by rafaeljcg20** [comment]
Por telefone o demandante confirmou que a demanda foi solucionada.
