### ISSUE TITLE
[CORREÇÃO] Módulo Alterações Orçamentárias

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#895]
- [x] Trocar a descrição de 'Saldo a Empenhar' para 'Disponível' no cadastro de Pedido de Alterações na aba de Selecionar PI.

- [x] Inverter colunar 'Cancelar' com a 'Suplementar' de ordem, primeiro 'Cancelar' e depois 'Suplementar', na aba de Selecionar PI.

- [x] Mudar descrição da coluna de 'Dotação Incial' para 'Dotação', na aba de Remanejamento Loa.
 
- [x] Inserir o nome do tipo de crédito na tela de cadastro de novo pedido de crédito. (Código - Descrição) Exemplo: "ACT - Alteração de valores X"

- [ ] Corrigir 'Dotação' que não está sendo carregado.

- [x] Corrigir para perfil Unidade ver apenas Unidades vinculadas à ele na tela de cadastro.

- [x] Corrigir botão de visualizar espelho de Pedido no módulo Planejamento.

- [x] Re-ativar o Webservice (Rotina Diária).

- [x] Inverter coluna supl. e cancelado tanto na seleção e pi qto funcional.

- [x] Implementar regras do Custeio e de Capital para o campo de Físico, relacionado a suplementar e cancelar.

**Comment by dougs007** [comment]
Branch: 

feature-alteracoes

**Comment by rafaeljcg20** [comment]
Falta testar as seguintes mudanças:
- [ ] Corrigir 'Dotação' que não está sendo carregado.
- [ ] Implementar regras do Custeio e de Capital para o campo de Físico, relacionado a suplementar e cancelar.
Falta implementar a seguinte funcionalidade:
- [ ] Inserir o nome do tipo de crédito na tela de cadastro de novo pedido de crédito. (Código - Descrição) Exemplo: "ACT - Alteração de valores X"

**Comment by rafaeljcg20** [comment]
No pedido número 5, ao tentar cancelar 2 do PI 10026 o sistema informa que não é possível excluir mais que a quantidade disponível no próprio PI, porém o PI tem saldo positivo(94).

**Comment by rafaeljcg20** [comment]
- [ ] Corrigir a lista do Item 2. Plano Interno que está diferente em relação a lista da aba Selecionar PI. Obs: Coluna Saldo a Empenhar, valores de saldo a empenhar.
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/e94a45ac-8783-4ea9-a113-a1e9c3de05aa)

**Comment by rafaeljcg20** [comment]
- [ ] Corrigir a lista do Item 3. Remanejamento Loa que está diferente em relação a lista da aba Remanejamento Loa da tela de Cadastro de Pedido. Obs: Mudar o nome da coluna Dotação Inicial pra Dotação.
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/7d72961e-f3db-4364-b119-4f86c7f70b0a)

**Comment by rafaeljcg20** [comment]
- [ ] Na Aba de Alterações Orçamentárias da tela de Cadastro de PI, está aparecendo os botões de editar, excluir pedido. Corrigir pra não exibir esses botões. Obs: Já existe uma variável que controlava a exibição desses botões.
- [ ] O botão de visualizar Pedido, ao invés de exibir a tela de espelho de Pedido está exibindo está abrindo a tela de Cadastro de PI.
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/acbef422-3d32-425f-8f0a-21ee5917cfdd)
