### ISSUE TITLE
[MELHORIA] Planejamento-Cadastro PI

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#896]
- [x] Permitir cadastrar PI com Custeio, Capital e Produto zerados.

**Comment by dougs007** [comment]
Nome da branch :
hotfix-896-planejamento-cadastro-pi

**Comment by rafaelfcar** [comment]
branch: hotfix-896-planejamento-cadastro-pi

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A

**Comment by macavalheiro** [comment]
os objetivos 0079, 0788 0783 0785 não estão listando metas no meu perfil
