### ISSUE TITLE
[CORREÇÃO]Relatório PPA com Gráfico

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#899]
>Ao entrar no "Relatório PPA com gráfico"  demora muito para carregar (acho q quase 1 minuto)
> ao filtrar por um objetivo o sistema dá msg de acesso negado e vai para outra tela.

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio-ppa-grafico&acao=A

**Comment by rafaeljcg20** [comment]
Branch: hotfix-899-monitoramento-rel-ppa

**Comment by macavalheiro** [comment]
os objetivos 0779, 0783, 0785, 0788 não estão listando meta nenhuma no meu perfil

nos filtros

**Comment by rafaeljcg20** [comment]
Corrigido. 
@macavalheiro , poderia verificar novamente?
