### ISSUE TITLE
[MELHORIA]Cadastro de Beneficiário-Nota de Empenho

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#901]
- [x] Incluir no formulário de Beneficiário, um campo aberto para unidade inserir (pode colocar várias) 
- [x] incluir no relatório tb, separado por virgula
- [x] O Número deve vir com uma mascara.**

**Obs: Ligar pra o Marcelo pra definir como será essa mascara.

Demandante: Sr. Marcelo

**Comment by rafaelfcar** [comment]
branch:
hotfix-901-emendas-nota-empenho

scripts:
﻿-- DROP SEQUENCE emendas.nota_empenho_neid_seq;
CREATE SEQUENCE emendas.nota_empenho_neid_seq
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER TABLE emendas.nota_empenho_neid_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE emendas.nota_empenho_neid_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE emendas.nota_empenho_neid_seq TO usr_simec;

﻿-- DROP TABLE emendas.nota_empenho
CREATE TABLE emendas.nota_empenho
(
  neid integer NOT NULL DEFAULT nextval('emendas.nota_empenho_neid_seq'::regclass), -- Chave Primária
  benid integer NOT NULL,
  numnotaempenho varchar(20),
  nestatus char(1) NOT NULL default 'A',
  
  CONSTRAINT pk_emendas_nota_emepnho PRIMARY KEY (neid),
  CONSTRAINT fk_nota_empenho_beneficiario FOREIGN KEY (benid) REFERENCES emendas.beneficiario (benid) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
)
WITH (
  OIDS=FALSE
);
ALTER TABLE emendas.nota_empenho OWNER TO postgres;
GRANT ALL ON TABLE emendas.nota_empenho TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE emendas.nota_empenho TO usr_simec;

**Comment by dougs007** [comment]
Observações na hora do teste:

- [ ] Permitir tamanho do campo "Nº nota de Empenho" salve com apenas o máximo de caractere suportado no banco.
- [ ] Estudar uma forma do layout não ficar quebrado.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/43238169-840c-40eb-b791-4f7e6c0a3e56)

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8874

**Comment by macavalheiro** [comment]
se possível colocar o box pedido de financeiro ao lado do nota de empenho, para não ficar aquele buraco na tela

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8421
