### ISSUE TITLE
[MELHORIA]Cadastro de Beneficiário-Pedido de Financeiro

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#902]
Nome do combo: "Pedido de Financeiro FEVEREIRO: 

- [x] Campos:
Valor Custeio
Valor Capital
Vinculação

- [x] Criar tela de apoio simples com descritor apenas

- [x] obs: precisa listar o histórico de todos pedidos 

- [x] [RN001] Período de preenchimento do dia 1 ao dia 10 
- [x] Os campos mostrarão sempre o valor do mês atual
- [x] Dados do responsável pelo salvamento (data, usuario email e telefone)
- [x] Botão de histórico com dados do responsável pelo salvamento (data, usuario email e telefone)

- [x] Incluir no relatório geral as informações de pedido de financeiro do mês atual

**Comment by rafaelfcar** [comment]
branch: hotfix-902-emendas-formulario-beneficiario

**Comment by rafaelfcar** [comment]
Scripts
﻿--DROP SEQUENCE emendas.vinculacao_vinid;
CREATE SEQUENCE emendas.vinculacao_vinid
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE emendas.vinculacao_vinid OWNER TO postgres;
GRANT ALL ON SEQUENCE emendas.vinculacao_vinid TO postgres;
GRANT SELECT, USAGE ON SEQUENCE emendas.vinculacao_vinid TO usr_simec;

--DROP TABLE emendas.vinculacao;
CREATE TABLE emendas.vinculacao
(
  vinid integer NOT NULL DEFAULT nextval('emendas.vinculacao_vinid'::regclass),
  vindsc varchar(100) not NULL,
  vinstatus char(1) not NULL default 'A',
  CONSTRAINT pk_vinculacao PRIMARY KEY (vinid)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE emendas.vinculacao OWNER TO postgres;
GRANT ALL ON TABLE emendas.vinculacao TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE emendas.vinculacao TO usr_simec;



﻿--DROP SEQUENCE emendas.pedido_financeiro_pefid;
CREATE SEQUENCE emendas.pedido_financeiro_pefid
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE emendas.pedido_financeiro_pefid OWNER TO postgres;
GRANT ALL ON SEQUENCE emendas.pedido_financeiro_pefid TO postgres;
GRANT SELECT, USAGE ON SEQUENCE emendas.pedido_financeiro_pefid TO usr_simec;

--DROP TABLE emendas.pedido_financeiro;
CREATE TABLE emendas.pedido_financeiro
(
  pefid integer NOT NULL DEFAULT nextval('emendas.pedido_financeiro_pefid'::regclass),
  benid integer not NULL,
  dtcadastro date not NULL default NOW(),
  usucpf char(11) not NULL,
  vlcusteiopedido numeric(10) NULL,
  vlcapitalpedido numeric(10) NULL,
  nroanoreferencia integer,
  nromesreferencia integer,
  vinid integer NULL,
  CONSTRAINT pk_pedido_financeiro PRIMARY KEY (pefid),
  CONSTRAINT fk_pedido_financeiro_beneficiario FOREIGN KEY (benid) REFERENCES emendas.beneficiario (benid) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_pedido_financeiro_vinculacao FOREIGN KEY (vinid) REFERENCES emendas.vinculacao (vinid) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
)
WITH (
  OIDS=FALSE
);
ALTER TABLE emendas.pedido_financeiro OWNER TO postgres;
GRANT ALL ON TABLE emendas.pedido_financeiro TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE emendas.pedido_financeiro TO usr_simec;

**Comment by rafaelfcar** [comment]
Ativar, para os perfis necessários, os menus

Vinculação
Cadastrar Vinculação

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/beneficiario_form&acao=A&benid=8420

**Comment by macavalheiro** [comment]
tava testando e a tabela de apoio vinculação, que antes tava visivel, sumiu para mim.

nos campos numéricos colocar formatação de moeda, por gentileza

**Comment by rafaeljcg20** [comment]
@rafaelfcar , ajusta pra gente na segunda-feira por favor.

**Comment by dougs007** [comment]
Oi @macavalheiro, alterações implementadas, poderia validar para nós novamente ?
