### ISSUE TITLE
[MELHORIA]Painel de Acompanhamento-Gráficos

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#903]
Na tela de Painel de Acompanhamento, mudar os gráficos para ficarem segundo os protótipos abaixo sendo cada um, em uma aba:

Vinculadas:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/44465f3a-41fc-4f09-b8c8-52708f3a35c2)
Subunidades: ANCINE, FSA, FBN, FCP, FCRB, FUNARTE, IBRAM, IPHAN, RSFNC, AGLO

Área Meio:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/4ca77d74-fd8e-45e1-a00a-b29f93e0f372)

Cultura:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/af30fbf2-7869-45fa-952a-becddf83268a)

Esporte:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/47ceadc2-ee1b-4313-a5d6-68e0d36340e2)

Desenv. Social:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/bea1ddad-0198-445e-8bdb-2eea760a3e3d)

 SESAN e SNPDH:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/85be6711-ca71-4b8a-8f8b-ce9c0cc90736)

SNRC e FNAS:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/04c342fc-819c-47a6-a4c7-ce577014a767)
Subunidades: SNRC, FNAS

**Comment by HenriqueOliveiradosAnjos** [comment]
Foram elaborados modelos de gráficos com as respectivas unidades após mudança de órgão. Não consegui inseri-los, mas segue abaixo o endereço dos mesmos. 
Observação: O gráfico das unidades no Siminc(homologa) está com mais unidades, que seria o mais adequado. 

Z:\GRAFICOS\GraficoUnidades.gif
Z:\GRAFICOS\GraficoAREAMEIO.gif
Z:\GRAFICOS\GraficoSECULT.gif
Z:\GRAFICOS\GraficoEsporte.gif
Z:\GRAFICOS\GraficoDesenvSocial-1.gif
Z:\GRAFICOS\GraficoDesenvSocial-2.gif
Z:\GRAFICOS\GraficoDesenvSocial-3.gif

**Comment by macavalheiro** [comment]
ordem abas:

Unidades
Area Meio
Cultura
Esporte
Os 3 do desenvolvimento Social (sendo o primeiro o que tem mais

**Comment by macavalheiro** [comment]
Se possível, nessa ordem e com esses nomes: 

> Vinculadas
ANCINE
FSA
FBN
FCP
FCRB
FUNARTE
IBRAM
IPHAN
RSFNC
AGLO
> Área Meio
CGLC
COGEP
SE
STI
SAGI

> Cultura
SDAPI
SDC
SEC
DLLLB
SEFIC
SEINFRA
SAV
DEAIN

>  Esporte

ABCD
DIFE
SENEAR
SNELIS
SNFDOT

>  Desenv. Social

SENAS
SENSP
SNCPD

> SNRC e FNAS
SNRC
FNAS

> SESAN e SNPDH
SESAN
SNPDH

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C

**Comment by rafaeljcg20** [comment]
Branch: hotfix-903-planejamento-painel-graficos

**Comment by HenriqueOliveiradosAnjos** [comment]
Correções: 
-no gráfico Desenv. Social retirar a UG 550008 e colocar a UG 550018. (falha minha na hora indicar o código das UGs)
-no gráfico SESAN e SNPDH retirar a UG 550018 e colocar a UG 550008. Alterar a sigla do título "SESAN" para "SNPR".
-no gráfico SNRC E FNAS alterar a sigla do título "SNRC" para "SENARC".

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C

**Comment by macavalheiro** [comment]
Ficou incrível! Parabéns galera!

Esse gráfico é de encher os olhos de qquer gestor!

@dougs007 @rafaeljcg20 @rafaelfcar @leossb36
