### ISSUE TITLE
[MELHORIA]Rotina Diária-Funcionais das UOs Unificadas

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#906]
Incluir atualização automática de Funcionais e Execução Orçamentária referente aos códigos de órgãos 55000 e 51000(Autoridade de Governança do Legado Olímpico - AGLO no WS).

Demandante: Marcelo

**Comment by rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/edf315c5-ec0d-4c60-ad9f-c0a5a37ad5f5)

**Comment by rafaeljcg20** [comment]
Foi verificado que o webservice consulta os dados de acordo com os códigos de órgão do perfil de acesso. Será iniciado a comunicação com a equipe do SIOP pra solicitar a o ajuste do cadastro.

**Comment by rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/8c1ce6f3-7e97-49a2-9a3a-bd5cc6e83c1c)

**Comment by rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/a29e6945-8ca2-461b-9697-5ec8ff86932e)

**Comment by rafaeljcg20** [comment]
Aguardando a resposta do pessoal do SIOP

**Comment by rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/7d8ed6e0-680b-48dc-bf2a-d47e55091ff6)

**Comment by rafaeljcg20** [comment]
Foi enviado uma nova comunicação com ao pessoal do SIOP do Ministério do Planejamento, solicitando ajuste na consulta de execução orçamentária pra que tenhamos os dados do órgão código 55000 e 51000:

![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/9a307191-15f4-4f61-8d2b-89b0cfcef2f3)

**Comment by rafaeljcg20** [comment]
Até a data atual o serviço qualitativo foi corrigido, porém o de execução orçamentária embora não esteja corrigido foi combinado com o P.O de importar os valores do sistema através do relatório de BI do SIOP.

**Comment by rafaeljcg20** [comment]
O problema já foi resolvido junto a equipe de suporte do SIOP.
