### ISSUE TITLE
[CORREÇÃO] Cadastro de Objetivo

### ISSUE THREAD

**Issue by HenriqueOliveiradosAnjos** [culturagovbr/siminc2#909]
- Ao cadastrar um novo OBJETIVO o sistema informa que o procedimento foi realizado mas o novo objetivo não é visualizado na tela. (Tela de Apoio Objetivo PPA)
- Quando alteramos o nome da UO na tabela Unidade/Subunidade de Ministério da Cultura para Ministério da CIDADANIA, esse novo nome não é visualizado na tela de cadastro de AÇÃO, o nome antigo ainda é visualizado. (Tela de Apoio Unidade/SubUnidade e Tela de Apoio de Ação)

- [x] Corrigir cadastro de Objetivo.
- [x] Investigar e corrigir o motivo da divergência de alterar o nome da UO e no cadastro de ação o nome não atualizar.

Demandante: Henrique Oliveira / SPOA

**Comment by dougs007** [comment]
- [ ] Consultar design para melhorar a exibição das opções de Metas na tela de Cadastro de Objetivo PPA.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/f9f37a3d-38df-4b10-bc5b-ec6dc1ddb37b)

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/acao&acao=A
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/objetivoppa&acao=A

**Comment by dougs007** [comment]
Oi @macavalheiro, Bom Dia!
Poderia validar para nós ?

**Comment by HenriqueOliveiradosAnjos** [comment]
O cadastro de objetivos continua apresentando falhas, percebi que o erro está relacionado a quantidade de caracteres.

**Comment by dougs007** [comment]
Oi Henrique, boa tarde!
Acabei de realizar a a correção. Poderia validar para nós novamente ?

**Comment by HenriqueOliveiradosAnjos** [comment]
ok. demanda finalizada.
