### ISSUE TITLE
[TRAMITAÇÃO] Gerar PI na pós ação do Botão Gerar PI do Fluxo do Emendas

### ISSUE THREAD

**Issue by g-adler** [culturagovbr/siminc2#91]
Checklist  1  -------------------------------------------------------------
- [x] Verificar se o enquadramento de despesa será sempre "6 - Emendas"
- [x] Criar campo na tabela de emendas: Título
- [x] Criar campo na tabela de emendas: Descrição/Finalidade
- [x] Criar campo na tabela de emendas: Objetivo PPA
- [x] Criar campo na tabela de emendas: Metas PPA
- [x] Criar campo na tabela de emendas: Iniciativa PPA
- [x] Criar campo na tabela de emendas: Meta PNC
- [x] Criar campo na tabela de emendas: Indicador PNC
- [x] Criar campo na tabela de emendas: Produto
- [x] Criar campo na tabela de emendas: Unidade Medida
- [x] Criar campo na tabela de emendas: Quantidade
- [x] Desenvolver/Implementar condição do workflow para não permitir gerar pi sem os campos obrigatórios definidos pelo Sr. Marcelo em reunião: Título, Descrição/Finalidade, Unidade, SubUnidade, Enquadramento, Funcional, PTRES, Produto, Unidade Medida, Quantidade, Área Cultural, Segmento Cultura, Modalidade de Pactuação, Número Siconv, TED.
- [x] Criar campo na tabela de emendas: Anexos
- [x] Criar campo na tabela de emendas: Vinculações Eventuais do Projeto: SNIIC
- [x] Criar campo na tabela de emendas: Vinculações Eventuais do Projeto: Pronac

Desenvolver/Implementar formulário de cadastro no formato de abas com as seguintes opções:
- [x] Título
- [x] Descrição/Finalidade
- [x] Objetivo PPA
- [x] Metas PPA
- [x] Iniciativa PPA
- [x] Meta PNC
- [x] Indicador PNC
- [x] Produto
- [x] Unidade Medida
- [x] Quantidade
- [x] Anexos
- [x] Vinculações Eventuais do Projeto: SNIIC
- [x] Vinculações Eventuais do Projeto: Pronac

Desenvolver/Implementar novas regras de visualização no formulário de cadastro de PI para a exibição de PIs do enquadramento do tipo Emendas exibindo apenas os campos usados na emenda(Sem cronogramas) e com regras de cálculos de valores conforme o seguinte documento: https://docs.google.com/spreadsheets/d/1zBtQqDh042gld1LMuuw9dW1Y641yRjre822wbnVX2bw/edit?ts=5a53d1c0#gid=0
- [x] Limite Autorizado na Unidade
- [x] Autorizado na Funcional
- [x] Saldo Disponível na Funcional
- [x] Valor Projeto Custeio
- [x] Valor Projeto Capital
- [x] Cronograma

**Comment by macavalheiro** [comment]
ao tentar gerar pi deu o seguinte erro


Parse error: syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION) in /var/www/html/treinamentosiminc2/monitora/classes/Pi_PlanoInterno.class.inc on line 1448
