### ISSUE TITLE
[CORREÇÃO]Manter Funcionais-Importar RP e PTRES

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#917]
Importar os códigos de resultado primário(RP) e código de plano de trabalho resumido(PTRES) para as novas funcionais do Ministério da Cidadania. Foi enviada uma planilha via e-mail contendo os dados pra realizar a importação.

Demandante: Marcelo

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/funcionais&acao=A
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/fc86265c-8063-41eb-8c04-4722d16f3e5b)
