### ISSUE TITLE
[CORREÇÃO]Relatório Geral-Construtor de Relatórios

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#919]
Na tela de Relatório Geral do módulo Emendas e na tela Construtor de Relatórios do módulo Monitoramento, inserir os novos dados do cadastro de beneficiário(Pedido de Financeiro e Nota de Empenho).

Demandante: Sr. Marcelo

**Comment by rafaelfcar** [comment]
branch: hotfix-919-monitoramento-construtor-relatorio

**Comment by dougs007** [comment]
Segue observações na hora do teste:

- [ ] Nota de empenho deve trazer 1 registro para cada nota que ele tiver ou qual é a regra ?
![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/cf2ca16e-ee8a-4182-a4ea-ac6ae6b96ad3)

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=relatorio/relatorio_principal_form&acao=A

http://homologasiminc2.cultura.gov.br/emendas/emendas.php?modulo=principal/emenda&acao=A
