### ISSUE TITLE
Novas Unidades cadastradas não aparecem na tela de vincular PTRES

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#922]
em produção

**Comment by macavalheiro** [comment]
essa tela já era bem pesada com as unidades que tinhamos. agora vão mais ou menos dobrar o número de unidade (acho q a maioria já está cadastrada). funcionais tb vão aumentar bastante

talvez seja o caso de repensarmos ela caso ela comece a ficar muito lenta.

Mas de forma geral o mais importante é que independente como eu consigo vincular as funcionais com as subunidades.

**Comment by dougs007** [comment]
Nome da branch :

hotfix-922-planejamento-vincular-ptres

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/vincular-ptres&acao=A
