### ISSUE TITLE
[MELHORIA]Vincular Funciona(PTRES)-Aumentar performance

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#929]
Na tela de Vincular Funcional(PTRES), substituir as listas existentes por uma lista simples contendo a coluna Funcional com a descrição da funcional e a coluna Subunidade possibilitando o preenchimento multiplo de Subunidades.

Exemplo de exibição dos dados na coluna Funcional da nova lista de Vincular Funcional(PTRES):
<i>0089.0181.0033..0000 - Aposentadorias e Pensões Civis da União: Aposentadorias e Pensões Civis da União (RP 1) (ptres:160257)</i>

Dica de código: <b>Utilizar consulta da tela Apoio -> Funcional e utilizar exemplo de comportamentos e funcionalidades da tela Configuração -> Vincular Metas PPA.</b>

Observações, anexos ou Informações complementares:
Melhorar tela de vincular ptres;
hoje está extremamente lenta, quase inviável.

Demanda: Sr. Marcelo

**Comment by rafaelfcar** [comment]
branch: hotfix-929-planejamento-vincular_ptres

**Comment by rafaeljcg20** [comment]
Paralisada em fase de teste pra atendimento das demandas urgentes.

**Comment by leossb36** [comment]
testada em homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/vincular-ptres&acao=A

comparação feita com treinamento:
http://treinamentosiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/vincular-ptres&acao=A
