### ISSUE TITLE
[MELHORIA]Painel de Acompanhamento-Lista de Funcionais

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#931]
Na tela de Painel de Acompanhamento, na lista de Acompanhamento de Funcionais, exibir os códigos de PTRES entre parenteses na descrição da funcional.

Exemplo: 0089.0181.0033..0000 - Aposentadorias e Pensões Civis da União: Aposentadorias e Pensões Civis da União (RP 1) (ptres: XXXXXX)

Demandante: Sr. Marcelo

**Comment by rafaelfcar** [comment]
branch: hotfix-931-planejamento-lista-funcionais

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C
