### ISSUE TITLE
[CORREÇÃO]Ajuste dos Perfil´s

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#932]
*Poder atribuir ao perfil de usuário as novas subunidades incluídas
*Trocar os textos onde aparece a palavra minc ou sistema minc substituir por Ministério da Cidadania
*Ao selecionar UO no cadastro de solicitar acesso aparecer só um "MINISTÉRIO DA CIDADANIA" para a UO 55101

(para todos os módulos)

Demandante: Sr Marcelo

**Comment by rafaelfcar** [comment]
branch: hotfix-932-ajuste-perfis

**Comment by dougs007** [comment]
Testado em homologação!

**Comment by macavalheiro** [comment]
perfeito, só faltou trocar trocar a a palavra minc ou sistema minc por Ministério da Cidadania na no texto de explicação da tela de pedido de acesso a novos usuários, qdo seleciona módulo planejamento, gestão estratégica e alterações orçamentarias

**Comment by dougs007** [comment]
Oi @macavalheiro, poderia validar para nós novamente ?

**Comment by macavalheiro** [comment]
perfeito, Douglas! eu estava olhando em homologação... já ia falar q não tinha arrumado, mas vi aqui q já está direto em produção.

só um ultimo detalhe: 

no menu de solicitação do menu do módulo planejamento ficou "sistema Ministério da Cidadania"  e dois lugares

se der para deixar só "Ministério da Cidadania", agradeço!

**Comment by dougs007** [comment]
Oi @macavalheiro, corrigi tanto em produção quanto em homologação!
