### ISSUE TITLE
[MELHORIA]Cadastro de PI-Enquadramento Não Orçamentária

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#934]
Na tela de Cadastro de PI, quando o usuário selecionar o item Não Orçamentário da opção Enquadramento de Despesa, o sistema deverá ocultar as opções Meta PNC, Indicador PNC, Área Cultural, Segmento Cultural, Modalidade de Pactuação, TED, Número SNIIC e Número PRONAC, além de exibir as opções Programas, Etapas(Múltipla opção onde o usuário deverá preencher Descrição e Data(Inserir Calendário)), Recursos Necessários e Anexos(Essa última já existe, só habilitar).

- [x] Desenvolver tela de Apoio -> Programas

Anexos e informações complementares:
Ajustar formulário de quanto seleciona enquadramento: "não orçamentária" conforme planilha abaixo:
https://docs.google.com/spreadsheets/d/1c7fRlJ49lxho8AIKJGVZksMRRU2VrD8n_5XnYM1v1_I/edit#gid=0

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Protótipo do Box de Etapas.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/5dfb4df6-82c9-4da6-94a3-88edadca3d23)

**Comment by dougs007** [comment]
Nome da branch :

hotfix-934-planejamento-cadastro-pi

**Comment by dougs007** [comment]
- [ ] OTRS do Script

-- DROP SEQUENCE planacomorc.etapas_etaid_seq;
CREATE SEQUENCE planacomorc.etapas_etaid_seq
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER TABLE planacomorc.etapas_etaid_seq
OWNER TO postgres;
GRANT ALL ON SEQUENCE planacomorc.etapas_etaid_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE planacomorc.etapas_etaid_seq TO usr_simec;

**Comment by dougs007** [comment]
Segue erro encontrado ao testar a demanda!
- [ ] 1- O sistema esperava um pliid, porém trata-se de um cadastro novo.
- [ ] 2- Aparentemente, o sistema está a exibir a combo de etapas quando abre o formulário, deveria ser somente ao selecionar o enquadramento como Não Orçamentária.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/4e4b6bd1-e46e-4ace-bf1d-c79ec36b3cb5)

**Comment by dougs007** [comment]
Ao tentar criar um novo PI, o sistema informa que devemos preencher os campos dos quais removemos nessa demanda. Segue anexo da mensagem exibida.

- [ ] 1 - Identificar validação do javascript e retirar obrigatoriedade para caso de enquadramento de despesa do tipo Não Orçamentária para os campos listados na descrição dessa issue.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/5f7b7e55-d364-4881-8e53-645fd26e2636)

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=11384

**Comment by rafaeljcg20** [comment]
Correções solicitadas pelo Demandante:
* Os espaços vagos da tela do formulário;
* Retirar a Caixa de Valor de Custeio e Capital do Projeto. Obs: Os dados de valor do projeto não apareciam pra o Enquadramento não orçamentário e passou a aparecer depois da manutenção; 
* Atualizar a versão do Javascript do Cadastro de PI e FNC. Obs: Inserir v=5 na URL externa do arquivo de javascript;
* Em caso de outros enquadramentos como por exemplo Finalístico, o sistema exibe as opções novas opções do formulario Programa, Etapas e Recursos Necessários, por favor ocultar essas opções para os demais enquadramentos.

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A

**Comment by macavalheiro** [comment]
sistema não deixa gravar pois cobra o preenchimento de campos que já foram retirados

se possível retirar a obrigatoriedade de todos os campos, com exceção de Título e Descrição e Produto

**Comment by dougs007** [comment]
Oi @macavalheiro, corrigido. Poderia validar para nós novamente ?

**Comment by macavalheiro** [comment]
ainda está solicitando campos q foram retirados ao tentar salvar

**Comment by rafaeljcg20** [comment]
- [ ] Retirar sinalização de obrigatoriedade(*) de Descrição e Data de Etapas;
- [ ] Retirar obrigatoriedade de preenchimento de Etapas;

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=11409
