### ISSUE TITLE
[MELHORIA]Cadastro de PI-Alterar código de Subunidades

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#936]
Na tela de cadastro de PI, por meio de script de banco de dados, alterar todos os PIs que têm os códigos de Subunidade 420008, 420009 e 420020 para respectivamente 550006, 550005 e 550016.

Conforme a planilha abaixo:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/02abd5a6-5711-48a4-8337-ef58494802d8)

https://docs.google.com/spreadsheets/d/15pajHcbRBmcyMAIwbsdAoe4LBhi3ayC4nPtHTUw6eak/edit?usp=sharing

**Comment by rafaeljcg20** [comment]
Analisar erro de dados no painel oriundo da mudança de PIs da CGTI pra STI:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/369f60be-9325-4012-a6cc-a727d2428279)

**Comment by rafaeljcg20** [comment]
Correções efetuadas nos vinculos de subunidades/funcionais:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/01e75d78-0d3c-48a7-8ffa-b398ea46e468)

@macavalheiro , poderia validar?

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C

**Comment by rafaeljcg20** [comment]
Demandante informou que a demanda estava resolvida por telefone e foi solicitada a publicação.
