### ISSUE TITLE
[CORREÇÃO]Cadastro de PI-Unidade Orçamentária

### ISSUE THREAD

**Issue by leossb36** [culturagovbr/siminc2#937]
Na tela Cadastro de PI e na tela espelho de PI, sempre que a UO preenchida for 55101 exibir sempre a informação MINISTÉRIO DA CIDADANIA - ADMINISTRAÇÃO DIRETA.

Obs: Solução paliativa.

Demandante: Sr. Marcelo

**Comment by leossb36** [comment]
nome da branch:
hotfix-937-planejamento-cadastro-pi-uo

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=11214

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C
