### ISSUE TITLE
[MELHORIA]Mostrar Hint com dotação inicial no painel

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#943]
Ao passar o mouse no campo de valor da coluna dotação (para custeio, capital e total) de cada funcional, mostrar a dotação inicial correspondente no seguinte formato:

"Dotação Inicial: 123.456"  por exemplo

Demandante: Sr. Marcelo

**Comment by rafaelfcar** [comment]
branch:
hotfix-943-planejamento-painel

scripts:
alter table monitora.ptres add column ptrdotacaoinicialcapital numeric(10);
alter table monitora.ptres add column ptrdotacaoinicialcusteio numeric(10);

**Comment by leossb36** [comment]
testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C#

**Comment by macavalheiro** [comment]
por gentileza, tirar apenas a as palavras custeio, capital e total de dentro dos rint´s

**Comment by dougs007** [comment]
Oi @macavalheiro, poderia validar novamente ?
