### ISSUE TITLE
[MELHORIA]Cadastro de Funcional-Função e Subfunção

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#950]
Na tela de Cadastro de Funcional(Apoio -> Funcional -> Cadastro de Funcional), criar as novas opções Função e Subfunção.

Anexos, Observações ou informações adicionais:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/32bf1a48-89b8-4712-b512-85e681b86794)

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch:

hotfix-950-cadastro-funcionais

**Comment by dougs007** [comment]
- [ ] OTRS do script.



ALTER TABLE public.ppafuncao ADD COLUMN funstatus character(1) NOT NULL DEFAULT 'A'::bpchar;
ALTER TABLE public.ppasubfuncao ADD COLUMN sfustatus character(1) NOT NULL DEFAULT 'A'::bpchar;

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/funcionais_form&acao=A&ptrid=3719
