### ISSUE TITLE
[CORREÇÃO]Monitoramento PNC-Lista de Indicadores

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#951]
Na tela MONITORAMENTO DAS METAS PNC, corrigir a visualização da lista de Indicadores PNC, pois caso o usuário não vincule nenhuma Subunidade à Meta ou à Iniciativa, o sistema deveria considerar a Meta ou Iniciativa vinculada pra todas as Subunidades e exibir os indicadores corretamente na lista.

Anexos, informações complementares ou observações:
<b>O erro foi reproduzido utilizando o recurso de simular usuário com o perfil Unidade.</b>
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/22c0ad89-1675-4bd5-90b2-19eda37c03c0)

Também realizar as seguintes correções:
- [x] Ao preencher a meta 03 com o perfil Unidade vinculado a Ancine o demandante notou que a meta 03 ficou preenchida pra o usuário com perfil Unidade da MINC - SECRETARIA DO AUDIOVISUAL - SAV.
- [x] Ao visualizar a meta 03 da Ancine com o perfil de Super Usuário o demandante notou que haviam mais indicadores do que simulando o usuário Unidade da própria Ancine na mesma meta.

Demandante: Sr. Marcelo

**Comment by rafaelfcar** [comment]
branch:
hotfix-951-monitoramento-metas-pnc

**Comment by leossb36** [comment]
testado em homologação:
http://homologasiminc2.cultura.gov.br/acompanhamento/acompanhamento.php?modulo=principal/monitorar-pnc&acao=A&suoid=522&janid=4&mpnid=946
