### ISSUE TITLE
[MELHORIA] Rotina Diária-Atualizar dados das Funcionais

### ISSUE THREAD

**Issue by leossb36** [culturagovbr/siminc2#961]
- [ ] Na tela de Funcional do módulo Planejamento Orçamentário, atualizar dados automaticamente de Função e Subfunção através da rotina diária de consulta ao Web Service.

Situação atual:
![captura de tela de 2019-02-26 15-16-48](https://user-images.githubusercontent.com/26796127/53438213-2fdc4b00-39de-11e9-82b5-1e5d677478bf.png)

**Comment by leossb36** [comment]
Branch:
hotfix-961-planejamento-dados-funcionais

**Comment by rafaeljcg20** [comment]
branch: hotfix-961-planejamento-funcao-subfuncao

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=apoio/funcionais&acao=A

**Comment by rafaeljcg20** [comment]
Demandante validou a modificação.
