### ISSUE TITLE
[MELHORIA]Execução Orçamentária de funcionais

### ISSUE THREAD

**Issue by leossb36** [culturagovbr/siminc2#962]
- [ ] Na funcionalidade de Atualizar Execução Orçamentária do sistema, atualmente o sistema busca os dados de dotações para definir Limites através do código de UO, Programa, Ação, Localizador e PO, mas é necessário buscar também por Função e Subfunção.

Demandante: Sr. Marcelo

**Comment by macavalheiro** [comment]
Rafa, na verdade o sistema hoje não busca pelo PTRES, mas sim pela funcional o conjunto de (Unidade Orçamentária, Programa, Ação, Localizador, PO).  a demanda é incluir função e subfunção

**Comment by leossb36** [comment]
branch: hotfix-962-planejamento-execucao-orcamentaria-funcionais

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/cd2097e3-6999-4157-9c6a-ab1c39f7cd6b)
