### ISSUE TITLE
[CORREÇÃO]Solicitação de Cadastro de Usuários-Email

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#972]
os seguintes pedidos de acesso, dia 27/02 não foram notificados via e-mail
cpf 61424187010[email: cavalheiro@gmail.com] (pedido de acesso para o módulo monitoramento)
cpf 392.325.640-09[email: cavalheiro@gmail.com] (pedido par ao módulo planejamento) 

já o pedido de acesso do dia 25/02  cpf 915.117.060-40 veio e-mail.

Precisava descobrir pq as vezes vem e-mail outra não e resolver, pois tá acontecendo de gente pedir acesso e a gente acabar não sabendo e isso é ruim.
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/9cf2d550-b248-4a65-907e-d06a41ee3028)

Demandante: Sr. Marcelo

**Comment by rafaeljcg20** [comment]
Obs: Pra o módulo de Monitoramento, segundo as regras configuradas de envio de emails de solicitação de novos acessos, apenas os usuários com perfil de Administrador receberão os avisos:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/1b41a7a3-3c00-435d-ab5c-4dc7bc290283)

No caso pra o módulo Monitoramento somente os usuários abaixo estão recebendo o e-mail de pedido de solicitação de acesso:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/6fec5eb0-3034-4b62-a4a8-da1d71c15c09)

**Comment by rafaeljcg20** [comment]
Demanda paralisada pra atender as demandas urgentes.

**Comment by dougs007** [comment]
Teste com perfil de Administrador.


![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/467481ca-6b35-4068-a514-43d53316f3c6)

**Comment by dougs007** [comment]
Teste do email solicitante:

PS: Gmail.

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/275ce3d5-8951-4942-bbba-0fa82a21aacf)

**Comment by dougs007** [comment]
Solução:

Atribuir o perfil que deveria mas não está recebendo e-mail como perfil Administrador para o Módulo Planejamento.
