### ISSUE TITLE
[MELHORIA]Cadastro de PI-Não Orçamentário-Obrigatoriedades

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#976]
Na tela Cadastro de PI, ao selecionar a opção de Enquadramento Não Orçamentário, retirar obrigatoriedade de preencher as seguintes opções pra salvar os dados do PI:
* Responsável;
* Objetivo PPA;
* Metas PPA.

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch:

hotfix-976-planejamento-cadastro-pi

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=11419
