### ISSUE TITLE
[CORREÇÃO]Cadastro de PI-Monitoramento

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#978]
Na tela cadastro de PI, ao editar o PI com identificador 11411 no exercicio 2019 o sistema não exibe a aba de Monitoramento, descobrir a causa e habilitar a aba de monitoramento pra o PI 11411.

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch :
hotfix-978-monitoramento-cadastro-pi

**Comment by dougs007** [comment]
UPDATE acompanhamento.programacaoexercicio SET prsexerccorrente = 'f' WHERE prsano = '2018';

INSERT INTO acompanhamento.programacaoexercicio 
(prsano, prsdata_inicial, prsdata_termino, prsexerccorrente, prsstatus, prsativo, prsexercicioaberto) VALUES 
('2019', '2019-01-01', '2019-12-31', 't', 'A', 1, 't');

**Comment by leossb36** [comment]
testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/cadastro_pi&acao=A&pliid=11411
