### ISSUE TITLE
[CORREÇÃO]Painel de Acompanhamento-Acompanhamento de Funcionais

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#984]
Na Lista de Funcionais das Subunidades localizado na Tela Painel de Acompanhamento o sistema não está exibindo o valor de Planejado Custeio conforme a imagem abaixo:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/8654cee4-d4a6-43f8-ad65-3a2becf1531e)

Demandante: Sr. Marcelo

**Comment by dougs007** [comment]
Nome da branch :

hotfix-984-planejamento-painel-funcionais

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C

**Comment by macavalheiro** [comment]
amém!
