### ISSUE TITLE
[CORREÇÃO]Cadastro de PI-Não orçamentário

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#990]
ao tentar salvar um pi não orçamentário com o cpf 058.472.586-82 (unidade: sav) dá a seguinte msg

Valor do projeto superior ao limite disponível da Unidade.

creio que faltou tirar apenas essa trava que é relacionada a unidade.

**Comment by rafaeljcg20** [comment]
branch: hotfix-990-planejamento-pi
