### ISSUE TITLE
[CORREÇÃO]Painel de Acompanhamento-Acompanhamento de Funcionais

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#992]
Na lista de Acompanhamento de Funcionais da tela Painel de Acompanhamento, após os usuários preencherem os limites das subunidades aconteceu duplicação de valores planejados conforme a imagem abaixo:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/686df36c-97d6-4745-a7cd-45bee0b4930a)

Demandante: Sr. Henrique

**Comment by rafaeljcg20** [comment]
- [ ] Script em anexo <b>chamado 8218495</b>

**Comment by rafaeljcg20** [comment]
Testado em: http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C

**Comment by macavalheiro** [comment]
@dougs007 será que alguém consegue publicar essa para gente, hoje ou amanhã?

Valeu!

**Comment by dougs007** [comment]
Oi @macavalheiro, acredito que conseguiremos publicar ela amanhã !
