### ISSUE TITLE
[MELHORIA]Mudanças no módulo Planejamento

### ISSUE THREAD

**Issue by macavalheiro** [culturagovbr/siminc2#998]
> Tela Principal módulo planejamento

- [x] Trocar nome do módulo de "Planejamento Orçamentário" para "Planejamento"

- [x] Trocar nome do botão "Lista de PI" para "Lista de PA"
- [x] Trocar nome do botão "Criar PI" para "Criar PA"

> Tela de Cadastro (antigo criar pi)

- [x] "Cadastro de PI" por "Cadastro de Plano de Ação"

- [x] "Criar PI por proposta por "Criar PA por proposta"

- [x] "Plano Interno(projeto) por "Plano de Ação(projeto)"

> Tela antiga lista PI "Código ou ID do PI" por Código PI ou Id do PA

- [x] Lista de PIs por Lista de Planos de Ação

**Comment by macavalheiro** [comment]
@dougs007 ligo para comentar

**Comment by dougs007** [comment]
Oi @macavalheiro, Bom dia !
Como a demanda envolve trocar nome de botões, preciso fazer em homologação e depois subir para produção.

**Comment by dougs007** [comment]
Nome da branch: 

hotfix-planejamento-mudanca-nomes

**Comment by dougs007** [comment]
Tela de Apoio de vira "Produtos PA" também ?

![image.png](https://images.zenhubusercontent.com/5aa678cb4b5806bc2bca71de/4fd93979-2029-4e13-8145-991a6cb9949c)

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=principal/unidade/listapimanter&acao=A

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=inicio&acao=C
